package schedulerhelper

import "context"

// ExecutionContext carries scheduler-only correlation metadata to an executor
// without changing the executor interface.
type ExecutionContext struct {
	ExecutionID  string
	JobID        string
	Attempt      int
	ExecutorName string
}

type executionContextKey struct{}

// WithExecutionContext attaches scheduler correlation metadata to an executor
// context. The ID is generated by the scheduler and remains stable across
// retries. jobID is optional for compatibility with direct callers that do not
// have a Job instance.
func WithExecutionContext(ctx context.Context, executionID string, attempt int, executorName string, jobIDs ...string) context.Context {
	if ctx == nil {
		ctx = context.Background()
	}
	jobID := ""
	if len(jobIDs) > 0 {
		jobID = jobIDs[0]
	}
	return context.WithValue(ctx, executionContextKey{}, ExecutionContext{
		ExecutionID:  executionID,
		JobID:        jobID,
		Attempt:      attempt,
		ExecutorName: executorName,
	})
}

// ExecutionContextFromContext returns scheduler correlation metadata when the
// context was created by WithExecutionContext.
func ExecutionContextFromContext(ctx context.Context) (ExecutionContext, bool) {
	if ctx == nil {
		return ExecutionContext{}, false
	}
	value, ok := ctx.Value(executionContextKey{}).(ExecutionContext)
	if !ok || value.ExecutionID == "" {
		return ExecutionContext{}, false
	}
	return value, true
}
