package schedulerhelper

import "context"

// ExecutionContext carries scheduler-only correlation metadata to an executor
// without changing the executor interface.
type ExecutionContext struct {
	ExecutionID  string
	Attempt      int
	ExecutorName string
}

type executionContextKey struct{}

// WithExecutionContext attaches the execution ID and attempt to an executor
// context. The ID is generated by the scheduler and remains stable across
// retries.
func WithExecutionContext(ctx context.Context, executionID string, attempt int, executorName string) context.Context {
	if ctx == nil {
		ctx = context.Background()
	}
	return context.WithValue(ctx, executionContextKey{}, ExecutionContext{
		ExecutionID:  executionID,
		Attempt:      attempt,
		ExecutorName: executorName,
	})
}

// ExecutionContextFromContext returns scheduler correlation metadata when the
// context was created by WithExecutionContext.
func ExecutionContextFromContext(ctx context.Context) (ExecutionContext, bool) {
	if ctx == nil {
		return ExecutionContext{}, false
	}
	value, ok := ctx.Value(executionContextKey{}).(ExecutionContext)
	if !ok || value.ExecutionID == "" {
		return ExecutionContext{}, false
	}
	return value, true
}
