package upgrade

import (
	"context"
	"testing"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	gbmodels "uvplatform.cn/uvp-gb28181/app/gb28181/models"
	"uvplatform.cn/uvp-gb28181/app/gb28181/protocol"
)

// mockFirmwareRepoService 实现 FirmwareRepositoryService 接口
type mockFirmwareRepoService struct {
	firmware *gbmodels.GbFirmwareRepository
	err      error
}

func (m *mockFirmwareRepoService) GetByFirmwareID(c *gin.Context, firmwareID string) (*gbmodels.GbFirmwareRepository, error) {
	if m.err != nil {
		return nil, m.err
	}
	return m.firmware, nil
}

// mockDownloadTokenService 实现 DownloadTokenService 接口
type mockDownloadTokenService struct {
	token       string
	downloadURL string
	expiresAt   time.Time
	err         error
}

func (m *mockDownloadTokenService) Generate(ctx context.Context, firmwareID string, userID, deptID uint64) (token, downloadURL string, expiresAt time.Time, err error) {
	if m.err != nil {
		return "", "", time.Time{}, m.err
	}
	return m.token, m.downloadURL, m.expiresAt, nil
}

// TC6.1: 固件仓库模式 - FileURL 自动生成
func TestFirmwareRepositoryMode_FileURLAutoGenerated(t *testing.T) {
	// 不启动完整的 service，只测试 validateRequest 的条件分支
	t.Run("validateRequest allows empty FileURL when FirmwareID is provided", func(t *testing.T) {
		request := Request{
			Confirmed:  true,
			FirmwareID: "firmware-123",
			// FileURL, Firmware, Manufacturer 全部为空（由后续注入逻辑填充）
		}
		target := Target{
			DeviceID:   1,
			DeviceCode: "34020000001320000001",
			Profile:    protocol.Profile{Version: protocol.Version2022},
		}

		err := validateRequest(target, request)
		assert.NoError(t, err, "固件仓库模式应跳过 FileURL 校验")
	})

	t.Run("validateRequest requires FileURL when FirmwareID is empty", func(t *testing.T) {
		request := Request{
			Confirmed:    true,
			Firmware:     "V5.9.0",      // 提供 Firmware
			Manufacturer: "海康",         // 提供 Manufacturer
			FileURL:      "",            // 空 URL 应该报错
			// FirmwareID 为空，进入手填模式
		}
		target := Target{
			DeviceID:   1,
			DeviceCode: "34020000001320000001",
			Profile:    protocol.Profile{Version: protocol.Version2022},
		}

		err := validateRequest(target, request)
		assert.Error(t, err, "手填模式必须提供 FileURL")
		assert.Contains(t, err.Error(), "FileURL")
	})
}

// TC6.2: 手填 URL 模式 - 保持兼容
func TestManualURLMode_BackwardCompatible(t *testing.T) {
	request := Request{
		Confirmed:    true,
		FileURL:      "http://user-server.com/firmware.bin",
		Firmware:     "V5.9.0",
		Manufacturer: "海康",
		// FirmwareID 为空，手填模式
	}
	target := Target{
		DeviceID:   1,
		DeviceCode: "34020000001320000001",
		Profile:    protocol.Profile{Version: protocol.Version2022},
	}

	err := validateRequest(target, request)
	assert.NoError(t, err, "手填模式应通过校验")
}

// TC6.3: validateRequest 条件校验
func TestValidateRequest_ConditionalChecks(t *testing.T) {
	tests := []struct {
		name      string
		request   Request
		wantError bool
		errorMsg  string
	}{
		{
			name: "固件仓库模式：FirmwareID 非空，跳过 URL 格式校验",
			request: Request{
				Confirmed:  true,
				FirmwareID: "fw-123",
				FileURL:    "", // 空 URL，但固件仓库模式不校验
			},
			wantError: false,
		},
		{
			name: "手填模式：FileURL 为空报错",
			request: Request{
				Confirmed:    true,
				FirmwareID:   "",
				Firmware:     "V5.9.0",
				Manufacturer: "海康",
				FileURL:      "",
			},
			wantError: true,
			errorMsg:  "FileURL",
		},
		{
			name: "手填模式：Firmware 为空报错",
			request: Request{
				Confirmed:  true,
				FileURL:    "http://example.com/fw.bin",
				Firmware:   "",
			},
			wantError: true,
			errorMsg:  "Firmware",
		},
		{
			name: "手填模式：Manufacturer 为空报错",
			request: Request{
				Confirmed:    true,
				FileURL:      "http://example.com/fw.bin",
				Firmware:     "V5.9.0",
				Manufacturer: "",
			},
			wantError: true,
			errorMsg:  "Manufacturer",
		},
		{
			name: "手填模式：完整参数通过校验",
			request: Request{
				Confirmed:    true,
				FileURL:      "http://example.com/fw.bin",
				Firmware:     "V5.9.0",
				Manufacturer: "海康",
			},
			wantError: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			target := Target{
				DeviceID:   1,
				DeviceCode: "34020000001320000001",
				Profile:    protocol.Profile{Version: protocol.Version2022},
			}

			err := validateRequest(target, tt.request)
			if tt.wantError {
				require.Error(t, err)
				assert.Contains(t, err.Error(), tt.errorMsg)
			} else {
				assert.NoError(t, err)
			}
		})
	}
}

// 测试 firmware repository service 查询失败的场景
func TestFirmwareRepositoryMode_QueryFailure(t *testing.T) {
	// 这个测试需要集成测试环境，暂时 skip
	// 因为需要 mock gin.Context 和 datascope，比较复杂
	t.Skip("需要完整的 gin.Context 和数据库环境，暂时跳过")
}

// 测试 download token 生成失败的场景
func TestFirmwareRepositoryMode_TokenGenerationFailure(t *testing.T) {
	// 同样需要集成测试环境
	t.Skip("需要完整的集成测试环境，暂时跳过")
}
