"""Generate the three SQL dialects from the audited button catalog.

Usage: python3 scripts/button-catalog.py [--check]
This only generates repository files; it never connects to a database.
"""
import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from api_groups import API_GROUP_OVERRIDES, GROUP_BY_PAGE, group_for_api, group_of  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
DATABASE = ROOT / "server/resource/database"
VERSION = "2026-09-05-button-permission-catalog"
START = "-- button-permission-catalog:start"
END = "-- button-permission-catalog:end"

# 分组映射见 scripts/api_groups.py。
# ⛔ 这里过去写死过一个兜底分组 `按钮权限目录`，结果每加一批按钮就长一批进去，
#    开发库里漂到 87 行、跨度 36 个页面，把「接口管理」的分组维度彻底搞坏。
#    现在按按钮所属页面落模块，未映射的页面直接报错，不再兜底。



def generate(catalog, dialect):
    def q(value):
        prefix = "N" if dialect == "sqlserver" else ""
        return prefix + "'" + str(value).replace("'", "''") + "'"

    def parent(path):
        # The derived aggregate avoids MySQL target-table UPDATE restrictions.
        return "(SELECT id FROM (SELECT MIN(id) AS id FROM sys_menu WHERE path=" + q(path) + " AND type IN (1,2) AND deleted_at IS NULL) AS catalog_parent)"

    out = [START, "-- Generated by scripts/button-catalog.py. Add catalog metadata only; do not grant roles or rebuild policies."]
    for page in catalog.get("dormantPages", []):
        out.append("INSERT INTO sys_menu(parent_id,path,name,component,title,hide,disable,sort,type,permission,icon,created_at,updated_at,created_by) SELECT "
                   + ",".join([parent(page["parentPath"]), q(page["path"]), q(page["name"]), q(page["component"]), q(page["title"]), "1", "1", "100", "2", q(""), q(""), "CURRENT_TIMESTAMP", "CURRENT_TIMESTAMP", "1"])
                   + " WHERE " + parent(page["parentPath"]) + " IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys_menu WHERE path=" + q(page["path"]) + " AND deleted_at IS NULL);")
    apis = {}
    titles = {}
    for button in catalog["buttons"]:
        for api in button["apis"]:
            key = (api["method"], api["path"])
            apis.setdefault(key, []).append(button)
            if api.get("title"):
                titles.setdefault(key, set()).add(api["title"])
    for (method, path), owners in sorted(apis.items()):
        # 接口级 title（apis[].title）优先；缺失才回落归属按钮名。
        # ⛔ 列语义说明：sys_api.title 的库注释是「权限名称」，但接口管理页把它当
        #    「API标题」展示 —— 回落按钮名时，一个按钮挂 N 个接口会让 N 行同名
        #    （历史上「查看仪表盘」5 行、全库 70 行）。所以凡「1 按钮挂多接口」的
        #    接口都必须在 json 里显式命名，由 scripts/button-catalog.test.py 强制。
        explicit = titles.get((method, path), set())
        if len(explicit) > 1:
            raise SystemExit("接口 %s %s 被赋了多个不同的接口名 %s；请在 json 里统一"
                             % (method, path, sorted(explicit)))
        title = explicit.pop() if explicit else owners[0]["title"]
        available = " OR ".join(parent(path) + " IS NOT NULL" for path in sorted({b["parentPath"] for b in owners}))
        out.append("INSERT INTO sys_api(title,path,method,api_group,created_at,updated_at,created_by) SELECT "
                   + ",".join([q(title), q(path), q(method), q(group_for_api(method, path, owners)), "CURRENT_TIMESTAMP", "CURRENT_TIMESTAMP", "1"])
                   + " WHERE (" + available + ") AND NOT EXISTS (SELECT 1 FROM sys_api WHERE path=" + q(path) + " AND method=" + q(method) + " AND deleted_at IS NULL);")
    for button in catalog["buttons"]:
        permission = q(button["permission"])
        target = parent(button["parentPath"])
        name = "Permission_" + button["permission"].replace(":", "_").replace("-", "_")
        out.append("INSERT INTO sys_menu(parent_id,path,name,component,title,hide,disable,sort,type,permission,icon,created_at,updated_at,created_by) SELECT "
                   + ",".join([target, q(""), q(name), q(""), q(button["title"]), "1", "0", "100", "3", permission, q(""), "CURRENT_TIMESTAMP", "CURRENT_TIMESTAMP", "1"])
                   + " WHERE " + target + " IS NOT NULL AND NOT EXISTS (SELECT 1 FROM sys_menu WHERE permission=" + permission + " AND deleted_at IS NULL);")
        repair = "parent_id=0 OR parent_id NOT IN (SELECT id FROM (SELECT DISTINCT id FROM sys_menu WHERE deleted_at IS NULL) AS catalog_existing_parent)"
        old_paths = button.get("repairParentPaths", [])
        if old_paths:
            repair += " OR parent_id IN (SELECT id FROM (SELECT DISTINCT id FROM sys_menu WHERE path IN (" + ",".join(map(q, old_paths)) + ")) AS catalog_legacy_parent)"
        out.append("UPDATE sys_menu SET parent_id=" + target + " WHERE permission=" + permission
                   + " AND type=3 AND deleted_at IS NULL AND " + target + " IS NOT NULL AND parent_id<>" + target + " AND (" + repair + ");")
        for api in button["apis"]:
            out.append("INSERT INTO sys_menu_api(menu_id,api_id) SELECT m.id,a.id FROM sys_menu m CROSS JOIN sys_api a WHERE m.permission="
                       + permission + " AND m.type=3 AND m.deleted_at IS NULL AND a.path=" + q(api["path"])
                       + " AND a.method=" + q(api["method"]) + " AND a.deleted_at IS NULL AND NOT EXISTS (SELECT 1 FROM sys_menu_api ma WHERE ma.menu_id=m.id AND ma.api_id=a.id);")
    out.append(END)
    return "\n\n".join(out) + "\n"


def outputs(catalog):
    for dialect, suffix, baseline in [("mysql", "", "uvp-gb28181.sql"), ("postgresql", "-postgresql", "postgresql_converted.sql"), ("sqlserver", "-sqlserver", "sqlserver_converted.sql")]:
        sql = generate(catalog, dialect)
        yield DATABASE / "gb28181/migrations" / (VERSION + suffix + ".sql"), sql
        # Forward-only metadata expansion: deleting catalog IDs could destroy later assignments.
        yield DATABASE / "gb28181/migrations" / (VERSION + suffix + "-down.sql"), "-- Forward-only catalog expansion; retain metadata and any later role assignments.\nSELECT 1;\n"
        path = DATABASE / baseline
        original = path.read_text()
        if START in original:
            start, end = original.index(START), original.index(END) + len(END)
            updated = original[:start] + sql.rstrip() + original[end:]
        else:
            updated = original.rstrip() + "\n\n" + sql
        yield path, updated


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    catalog = json.loads((DATABASE / "gb28181/button-permissions.json").read_text())
    stale = []
    for path, content in outputs(catalog):
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(content)
    if stale:
        raise SystemExit("Catalog output drift:\n" + "\n".join(stale))
    print("Catalog outputs match" if args.check else "Generated catalog migrations and baseline sections")


if __name__ == "__main__":
    main()
