-- GB28181 国标通道表(设备下的视频通道,Catalog 目录查询填充)
DROP TABLE IF EXISTS `gb_channel`;
CREATE TABLE `gb_channel` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `channel_id` varchar(20) NOT NULL DEFAULT '' COMMENT '通道国标编码',
  `device_id` varchar(20) NOT NULL DEFAULT '' COMMENT '所属设备国标编码',
  `name` varchar(255) NOT NULL DEFAULT '' COMMENT '通道名称',
  `manufacturer` varchar(255) NOT NULL DEFAULT '' COMMENT '厂商',
  `model` varchar(255) NOT NULL DEFAULT '' COMMENT '型号',
  `owner` varchar(64) NOT NULL DEFAULT '' COMMENT '设备归属',
  `civil_code` varchar(32) NOT NULL DEFAULT '' COMMENT '行政区划',
  `parent_id` varchar(20) NOT NULL DEFAULT '' COMMENT '父节点编码(目录树)',
  `ptz_type` tinyint DEFAULT '0' COMMENT '云台类型 0未知 1球机 2半球 3固定枪机 4遥控枪机 5遥控半球 6多目全景/拼接通道 7多目分割通道(5-7 为 2022 新增)',
  `room_type` tinyint NOT NULL DEFAULT '0' COMMENT '室内外 0未上报 1室外 2室内(两版编码一致)',
  `supply_light_type` tinyint NOT NULL DEFAULT '0' COMMENT '补光方式 0未上报 1无补光 2红外 3白光 4激光 9其他',
  `direction_type` tinyint NOT NULL DEFAULT '0' COMMENT '方向 0未上报',
  `resolution` varchar(32) NOT NULL DEFAULT '' COMMENT '分辨率,如 1920*1080',
  `ip_address` varchar(64) NOT NULL DEFAULT '' COMMENT '设备声明的通道 IP(Catalog Item 层)',
  `port` int NOT NULL DEFAULT '0' COMMENT '设备声明的通道端口(Catalog Item 层)',
  `position_type` tinyint NOT NULL DEFAULT '0' COMMENT '位置类型 0未上报 2016独有 1省际检查站…10交通干线',
  `use_type` tinyint NOT NULL DEFAULT '0' COMMENT '用途 0未上报 2016独有 1治安 2交通 3重点',
  `photoelectric_imaging_type` varchar(32) NOT NULL DEFAULT '' COMMENT '光电成像类型 2022独有,可多值 / 分隔',
  `capture_position_type` varchar(32) NOT NULL DEFAULT '' COMMENT '采集部位类型 2022独有,见附录O',
  `stream_number_list` varchar(32) NOT NULL DEFAULT '' COMMENT '支持的码流编号 2022独有,可多值 / 分隔,如 0/1 或 0/1/2',
  `longitude` decimal(10,6) DEFAULT '0.000000' COMMENT '经度',
  `latitude` decimal(10,6) DEFAULT '0.000000' COMMENT '纬度',
  `status` tinyint(1) DEFAULT '0' COMMENT '通道在线 0离线 1在线',
  `stream_id` varchar(64) NOT NULL DEFAULT '' COMMENT '当前播放流ID(ZLM app/stream),空=未点播',
  `current_ssrc` varchar(10) NOT NULL DEFAULT '' COMMENT '当前实时媒体会话SSRC',
  `on_demand_live` tinyint(1) NOT NULL DEFAULT '1' COMMENT '按需直播 1=无人观看自动关闭',
  `audio_enabled` tinyint(1) NOT NULL DEFAULT '1' COMMENT '点播是否接收音频',
  `recording_mode` varchar(16) NOT NULL DEFAULT 'off' COMMENT '录像模式 off/continuous/scheduled',
  `cloud_recording_enabled` tinyint(1) NOT NULL DEFAULT '0' COMMENT '云端录像期望开关',
  `cloud_recording_state` varchar(20) NOT NULL DEFAULT 'disabled' COMMENT '云端录像运行状态',
  `cloud_recording_error` varchar(500) NOT NULL DEFAULT '' COMMENT '云端录像最近错误',
  `cloud_recording_updated_at` datetime DEFAULT NULL COMMENT '云端录像状态更新时间',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `owner_dept_id` int unsigned NOT NULL DEFAULT '0' COMMENT '所属部门ID',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_device_channel` (`device_id`, `channel_id`) USING BTREE,
  KEY `idx_device_id` (`device_id`),
  KEY `idx_stream_id` (`stream_id`),
  KEY `idx_owner_dept_deleted` (`owner_dept_id`, `deleted_at`),
  KEY `idx_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='GB28181国标通道表';
