CREATE TABLE `gb_device_subscription` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `device_id` int unsigned NOT NULL,
  `kind` varchar(32) NOT NULL,
  `enabled` tinyint(1) NOT NULL DEFAULT 0,
  `status` varchar(16) NOT NULL DEFAULT 'disabled',
  `expires_seconds` int NOT NULL DEFAULT 3600,
  `interval_seconds` int NOT NULL DEFAULT 0,
  `event` varchar(32) NOT NULL,
  `call_id` varchar(255) DEFAULT NULL,
  `local_tag` varchar(128) DEFAULT NULL,
  `remote_tag` varchar(128) DEFAULT NULL,
  `cseq` int unsigned NOT NULL DEFAULT 0,
  `expires_at` datetime DEFAULT NULL,
  `last_subscribe_at` datetime DEFAULT NULL,
  `last_notify_at` datetime DEFAULT NULL,
  `next_action_at` datetime DEFAULT NULL,
  `retry_count` int NOT NULL DEFAULT 0,
  `last_status_code` int NOT NULL DEFAULT 0,
  `last_error` text DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_device_subscription_kind` (`device_id`, `kind`),
  KEY `idx_subscription_call_id` (`call_id`),
  KEY `idx_subscription_due` (`enabled`, `next_action_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='GB28181 device subscriptions';

CREATE TABLE `gb_mobile_position_latest` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `device_id` int unsigned NOT NULL,
  `source_code` varchar(20) NOT NULL,
  `channel_id` int unsigned DEFAULT NULL,
  `event_time` datetime NOT NULL,
  `received_at` datetime NOT NULL,
  `longitude` decimal(10,6) NOT NULL,
  `latitude` decimal(10,6) NOT NULL,
  `speed` double DEFAULT NULL,
  `direction` double DEFAULT NULL,
  `altitude` double DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_position_device_source` (`device_id`, `source_code`),
  KEY `idx_channel_id` (`channel_id`),
  KEY `idx_event_time` (`event_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='GB28181 latest mobile positions';

CREATE TABLE `gb_mobile_position_history` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `device_id` int unsigned NOT NULL,
  `source_code` varchar(20) NOT NULL,
  `channel_id` int unsigned DEFAULT NULL,
  `event_time` datetime NOT NULL,
  `received_at` datetime NOT NULL,
  `longitude` decimal(10,6) NOT NULL,
  `latitude` decimal(10,6) NOT NULL,
  `speed` double DEFAULT NULL,
  `direction` double DEFAULT NULL,
  `altitude` double DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_position_history_device_source_time` (`device_id`, `source_code`, `event_time`),
  KEY `idx_position_history_channel_time` (`channel_id`, `event_time`),
  KEY `idx_position_history_received_at` (`received_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='GB28181 mobile position history';

CREATE TABLE `gb_alarm_event` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `device_id` int unsigned NOT NULL,
  `channel_id` int unsigned DEFAULT NULL,
  `source_code` varchar(20) NOT NULL,
  `sn` varchar(64) DEFAULT NULL,
  `alarm_time` datetime DEFAULT NULL,
  `priority` int DEFAULT NULL,
  `method` int DEFAULT NULL,
  `alarm_type` int DEFAULT NULL,
  `alarm_type_param` varchar(255) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `longitude` decimal(10,6) DEFAULT NULL,
  `latitude` decimal(10,6) DEFAULT NULL,
  `call_id` varchar(255) DEFAULT NULL,
  `cseq` varchar(64) DEFAULT NULL,
  `dedupe_key` varchar(128) NOT NULL,
  `raw_digest` varchar(64) DEFAULT NULL,
  `raw_summary` text DEFAULT NULL,
  `received_at` datetime NOT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dedupe_key` (`dedupe_key`),
  KEY `idx_alarm_device_time` (`device_id`, `alarm_time`),
  KEY `idx_channel_id` (`channel_id`),
  KEY `idx_received_at` (`received_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='GB28181 alarm events';
