-- 接口标题（sys_api.title）归一化。
--
-- 背景：sys_api.title 的**列语义是「权限名称」**（库注释 `COMMENT '权限名称'`），
-- 而「接口管理」页把它当「API标题」展示。生成器过去直接拿归属按钮名填 ——
-- 一个按钮挂 N 个接口时 N 行同名，页面无法区分（如「查看仪表盘」下 5 个接口
-- 分别查 summary / layout / 3 个 drilldown，全叫「查看仪表盘」）。
--
-- 新口径：接口名 = **接口自己的功能名**，由目录显式声明：
--   server/resource/database/gb28181/button-permissions.json 的 buttons[].apis[].title
--   server/resource/database/gb28181/guest-permissions.json 的 bindings[].apis[].title
-- 生成器（scripts/button-catalog.py / scripts/guest-permissions.py）优先取它，
-- 缺失才回落按钮名；「1 按钮挂多接口」的接口缺声明会被 button-catalog.test.py 拦下。
--
-- ⛔ 定位键是 (path, method) 而不是 id：各库 id 不同，path+method 才跨库稳定。
-- ⛔ title 不参与鉴权（鉴权走 casbin 的 path+method 与 sys_menu.permission），
--    纯展示元数据；本迁移只改名字，不动授权。
-- ⛔ 两个生成器的 sys_api INSERT 只有 WHERE NOT EXISTS、没有 UPDATE 分支
--    ⇒ 光改生成器修不了已有行，必须靠本迁移。

UPDATE `sys_api` SET `title`='获取指定数据库中的表集合' WHERE `path`='/api/codegen/tables' AND `method`='GET' AND `title`<>'获取指定数据库中的表集合';
UPDATE `sys_api` SET `title`='物理删除单条告警' WHERE `path`='/api/gb28181/alarms/:id' AND `method`='DELETE' AND `title`<>'物理删除单条告警';
UPDATE `sys_api` SET `title`='批量物理删除告警' WHERE `path`='/api/gb28181/alarms/batch-delete' AND `method`='POST' AND `title`<>'批量物理删除告警';
UPDATE `sys_api` SET `title`='查看级联平台列表' WHERE `path`='/api/gb28181/cascade/platforms' AND `method`='GET' AND `title`<>'查看级联平台列表';
UPDATE `sys_api` SET `title`='创建级联平台' WHERE `path`='/api/gb28181/cascade/platforms' AND `method`='POST' AND `title`<>'创建级联平台';
UPDATE `sys_api` SET `title`='删除级联平台' WHERE `path`='/api/gb28181/cascade/platforms/:id' AND `method`='DELETE' AND `title`<>'删除级联平台';
UPDATE `sys_api` SET `title`='查看级联平台' WHERE `path`='/api/gb28181/cascade/platforms/:id' AND `method`='GET' AND `title`<>'查看级联平台';
UPDATE `sys_api` SET `title`='修改级联平台' WHERE `path`='/api/gb28181/cascade/platforms/:id' AND `method`='PUT' AND `title`<>'修改级联平台';
UPDATE `sys_api` SET `title`='启用级联平台' WHERE `path`='/api/gb28181/cascade/platforms/:id/enable' AND `method`='POST' AND `title`<>'启用级联平台';
UPDATE `sys_api` SET `title`='更新级联启用状态' WHERE `path`='/api/gb28181/cascade/platforms/:id/enabled' AND `method`='PUT' AND `title`<>'更新级联启用状态';
UPDATE `sys_api` SET `title`='查看级联共享' WHERE `path`='/api/gb28181/cascade/platforms/:id/shares' AND `method`='GET' AND `title`<>'查看级联共享';
UPDATE `sys_api` SET `title`='更新级联共享' WHERE `path`='/api/gb28181/cascade/platforms/:id/shares' AND `method`='PUT' AND `title`<>'更新级联共享';
UPDATE `sys_api` SET `title`='查询通道收藏组' WHERE `path`='/api/gb28181/channel-favorite-groups' AND `method`='GET' AND `title`<>'查询通道收藏组';
UPDATE `sys_api` SET `title`='新建通道收藏组' WHERE `path`='/api/gb28181/channel-favorite-groups' AND `method`='POST' AND `title`<>'新建通道收藏组';
UPDATE `sys_api` SET `title`='删除通道收藏组' WHERE `path`='/api/gb28181/channel-favorite-groups/:id' AND `method`='DELETE' AND `title`<>'删除通道收藏组';
UPDATE `sys_api` SET `title`='移除通道收藏' WHERE `path`='/api/gb28181/channel-favorite-groups/:id/channels' AND `method`='DELETE' AND `title`<>'移除通道收藏';
UPDATE `sys_api` SET `title`='追加通道收藏' WHERE `path`='/api/gb28181/channel-favorite-groups/:id/channels' AND `method`='POST' AND `title`<>'追加通道收藏';
UPDATE `sys_api` SET `title`='取消云端录像下载' WHERE `path`='/api/gb28181/cloud-recordings/downloads/:taskId' AND `method`='DELETE' AND `title`<>'取消云端录像下载';
UPDATE `sys_api` SET `title`='查询云端录像下载' WHERE `path`='/api/gb28181/cloud-recordings/downloads/:taskId' AND `method`='GET' AND `title`<>'查询云端录像下载';
UPDATE `sys_api` SET `title`='删除单个云端录像' WHERE `path`='/api/gb28181/cloud-recordings/files/:id' AND `method`='DELETE' AND `title`<>'删除单个云端录像';
UPDATE `sys_api` SET `title`='创建云端录像下载' WHERE `path`='/api/gb28181/cloud-recordings/files/:id/downloads' AND `method`='POST' AND `title`<>'创建云端录像下载';
UPDATE `sys_api` SET `title`='批量删除云端录像' WHERE `path`='/api/gb28181/cloud-recordings/files/batch-delete' AND `method`='POST' AND `title`<>'批量删除云端录像';
UPDATE `sys_api` SET `title`='查询录像对账状态' WHERE `path`='/api/gb28181/cloud-recordings/reconciliations' AND `method`='GET' AND `title`<>'查询录像对账状态';
UPDATE `sys_api` SET `title`='触发录像对账' WHERE `path`='/api/gb28181/cloud-recordings/reconciliations' AND `method`='POST' AND `title`<>'触发录像对账';
UPDATE `sys_api` SET `title`='查询目录树' WHERE `path`='/api/gb28181/device-mgmt/catalog/tree' AND `method`='GET' AND `title`<>'查询目录树';
UPDATE `sys_api` SET `title`='读取目录节点详情' WHERE `path`='/api/gb28181/device-mgmt/catalog/tree/:id' AND `method`='GET' AND `title`<>'读取目录节点详情';
UPDATE `sys_api` SET `title`='读取目录子节点' WHERE `path`='/api/gb28181/device-mgmt/catalog/tree/:id/children' AND `method`='GET' AND `title`<>'读取目录子节点';
UPDATE `sys_api` SET `title`='删除单个通道' WHERE `path`='/api/gb28181/device-mgmt/channel/:id' AND `method`='DELETE' AND `title`<>'删除单个通道';
UPDATE `sys_api` SET `title`='读取通道详情' WHERE `path`='/api/gb28181/device-mgmt/channel/:id' AND `method`='GET' AND `title`<>'读取通道详情';
UPDATE `sys_api` SET `title`='读取设备控制能力' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/control-capabilities' AND `method`='GET' AND `title`<>'读取设备控制能力';
UPDATE `sys_api` SET `title`='读取通道运行状态' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/device-status' AND `method`='GET' AND `title`<>'读取通道运行状态';
UPDATE `sys_api` SET `title`='读取通道挂载点' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/mounts' AND `method`='GET' AND `title`<>'读取通道挂载点';
UPDATE `sys_api` SET `title`='创建回放会话' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/playback-sessions' AND `method`='POST' AND `title`<>'创建回放会话';
UPDATE `sys_api` SET `title`='停止回放会话' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/playback-sessions/:sessionId' AND `method`='DELETE' AND `title`<>'停止回放会话';
UPDATE `sys_api` SET `title`='读取回放会话' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/playback-sessions/:sessionId' AND `method`='GET' AND `title`<>'读取回放会话';
UPDATE `sys_api` SET `title`='控制回放（暂停/续播/倍速）' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/playback-sessions/:sessionId/actions' AND `method`='POST' AND `title`<>'控制回放（暂停/续播/倍速）';
UPDATE `sys_api` SET `title`='云台基础控制' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/ptz' AND `method`='POST' AND `title`<>'云台基础控制';
UPDATE `sys_api` SET `title`='下发巡航指令' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/ptz/cruise' AND `method`='POST' AND `title`<>'下发巡航指令';
UPDATE `sys_api` SET `title`='查询巡航轨迹列表' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/ptz/cruise-tracks' AND `method`='GET' AND `title`<>'查询巡航轨迹列表';
UPDATE `sys_api` SET `title`='读取巡航轨迹详情' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/ptz/cruise-tracks/:trackId' AND `method`='GET' AND `title`<>'读取巡航轨迹详情';
UPDATE `sys_api` SET `title`='保存巡航轨迹' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/ptz/cruise/tracks' AND `method`='POST' AND `title`<>'保存巡航轨迹';
UPDATE `sys_api` SET `title`='云台扩展控制' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/ptz/extended' AND `method`='POST' AND `title`<>'云台扩展控制';
UPDATE `sys_api` SET `title`='查询看守位' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/ptz/home-position' AND `method`='GET' AND `title`<>'查询看守位';
UPDATE `sys_api` SET `title`='查询云台操作结果' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/ptz/operations/:operationId' AND `method`='GET' AND `title`<>'查询云台操作结果';
UPDATE `sys_api` SET `title`='云台精准控制' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/ptz/precise' AND `method`='POST' AND `title`<>'云台精准控制';
UPDATE `sys_api` SET `title`='查询精准控制状态' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/ptz/precise-status' AND `method`='GET' AND `title`<>'查询精准控制状态';
UPDATE `sys_api` SET `title`='查询预置位列表' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/ptz/presets' AND `method`='GET' AND `title`<>'查询预置位列表';
UPDATE `sys_api` SET `title`='查询设备录像' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/record-query' AND `method`='POST' AND `title`<>'查询设备录像';
UPDATE `sys_api` SET `title`='查询录像查询条件' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/record-query/options' AND `method`='GET' AND `title`<>'查询录像查询条件';
UPDATE `sys_api` SET `title`='创建抓拍会话' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/snapshot-sessions' AND `method`='POST' AND `title`<>'创建抓拍会话';
UPDATE `sys_api` SET `title`='读取抓拍会话' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/snapshot-sessions/:sessionId' AND `method`='GET' AND `title`<>'读取抓拍会话';
UPDATE `sys_api` SET `title`='创建对讲会话' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/talk-sessions' AND `method`='POST' AND `title`<>'创建对讲会话';
UPDATE `sys_api` SET `title`='停止对讲会话' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/talk-sessions/:sessionId' AND `method`='DELETE' AND `title`<>'停止对讲会话';
UPDATE `sys_api` SET `title`='读取对讲会话' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/talk-sessions/:sessionId' AND `method`='GET' AND `title`<>'读取对讲会话';
UPDATE `sys_api` SET `title`='查询通道时间轴' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/timeline' AND `method`='GET' AND `title`<>'查询通道时间轴';
UPDATE `sys_api` SET `title`='批量删除通道' WHERE `path`='/api/gb28181/device-mgmt/channel/batch-delete' AND `method`='POST' AND `title`<>'批量删除通道';
UPDATE `sys_api` SET `title`='查询通道列表' WHERE `path`='/api/gb28181/device-mgmt/channels' AND `method`='GET' AND `title`<>'查询通道列表';
UPDATE `sys_api` SET `title`='创建自定义分组' WHERE `path`='/api/gb28181/device-mgmt/custom-groups' AND `method`='POST' AND `title`<>'创建自定义分组';
UPDATE `sys_api` SET `title`='删除自定义分组' WHERE `path`='/api/gb28181/device-mgmt/custom-groups/:id' AND `method`='DELETE' AND `title`<>'删除自定义分组';
UPDATE `sys_api` SET `title`='修改自定义分组' WHERE `path`='/api/gb28181/device-mgmt/custom-groups/:id' AND `method`='PATCH' AND `title`<>'修改自定义分组';
UPDATE `sys_api` SET `title`='添加分组设备' WHERE `path`='/api/gb28181/device-mgmt/custom-groups/:id/devices' AND `method`='POST' AND `title`<>'添加分组设备';
UPDATE `sys_api` SET `title`='移除分组设备' WHERE `path`='/api/gb28181/device-mgmt/custom-groups/:id/devices/remove' AND `method`='POST' AND `title`<>'移除分组设备';
UPDATE `sys_api` SET `title`='移动自定义分组' WHERE `path`='/api/gb28181/device-mgmt/custom-groups/:id/move' AND `method`='POST' AND `title`<>'移动自定义分组';
UPDATE `sys_api` SET `title`='删除单个设备' WHERE `path`='/api/gb28181/device-mgmt/device/:id' AND `method`='DELETE' AND `title`<>'删除单个设备';
UPDATE `sys_api` SET `title`='读取设备详情' WHERE `path`='/api/gb28181/device-mgmt/device/:id' AND `method`='GET' AND `title`<>'读取设备详情';
UPDATE `sys_api` SET `title`='查看设备升级' WHERE `path`='/api/gb28181/device-mgmt/device/:id/firmware-upgrades' AND `method`='GET' AND `title`<>'查看设备升级';
UPDATE `sys_api` SET `title`='查询设备维护操作' WHERE `path`='/api/gb28181/device-mgmt/device/:id/maintenance-operations' AND `method`='GET' AND `title`<>'查询设备维护操作';
UPDATE `sys_api` SET `title`='查询设备状态事件' WHERE `path`='/api/gb28181/device-mgmt/device/:id/status-events' AND `method`='GET' AND `title`<>'查询设备状态事件';
UPDATE `sys_api` SET `title`='查询设备订阅' WHERE `path`='/api/gb28181/device-mgmt/device/:id/subscriptions' AND `method`='GET' AND `title`<>'查询设备订阅';
UPDATE `sys_api` SET `title`='更新设备订阅' WHERE `path`='/api/gb28181/device-mgmt/device/:id/subscriptions/:kind' AND `method`='PATCH' AND `title`<>'更新设备订阅';
UPDATE `sys_api` SET `title`='续订设备订阅' WHERE `path`='/api/gb28181/device-mgmt/device/:id/subscriptions/:kind/renew' AND `method`='POST' AND `title`<>'续订设备订阅';
UPDATE `sys_api` SET `title`='批量删除设备' WHERE `path`='/api/gb28181/device-mgmt/device/batch-delete' AND `method`='POST' AND `title`<>'批量删除设备';
UPDATE `sys_api` SET `title`='查询设备列表' WHERE `path`='/api/gb28181/device-mgmt/devices' AND `method`='GET' AND `title`<>'查询设备列表';
UPDATE `sys_api` SET `title`='查询组织目录树' WHERE `path`='/api/gb28181/device-mgmt/directory/tree' AND `method`='GET' AND `title`<>'查询组织目录树';
UPDATE `sys_api` SET `title`='查询地图聚合点' WHERE `path`='/api/gb28181/device-mgmt/map/clusters' AND `method`='GET' AND `title`<>'查询地图聚合点';
UPDATE `sys_api` SET `title`='查询地图标记点' WHERE `path`='/api/gb28181/device-mgmt/map/markers' AND `method`='GET' AND `title`<>'查询地图标记点';
UPDATE `sys_api` SET `title`='调整设备归属' WHERE `path`='/api/gb28181/device-mgmt/permission-workbench/assignments' AND `method`='POST' AND `title`<>'调整设备归属';
UPDATE `sys_api` SET `title`='整部门调整设备归属' WHERE `path`='/api/gb28181/device-mgmt/permission-workbench/assignments/departments' AND `method`='POST' AND `title`<>'整部门调整设备归属';
UPDATE `sys_api` SET `title`='解析工作台设备' WHERE `path`='/api/gb28181/device-mgmt/permission-workbench/devices/resolve' AND `method`='POST' AND `title`<>'解析工作台设备';
UPDATE `sys_api` SET `title`='查询共享目标' WHERE `path`='/api/gb28181/device-mgmt/permission-workbench/grant-targets' AND `method`='GET' AND `title`<>'查询共享目标';
UPDATE `sys_api` SET `title`='应用设备共享授权' WHERE `path`='/api/gb28181/device-mgmt/permission-workbench/grants/apply' AND `method`='POST' AND `title`<>'应用设备共享授权';
UPDATE `sys_api` SET `title`='查询设备共享授权' WHERE `path`='/api/gb28181/device-mgmt/permission-workbench/grants/query' AND `method`='POST' AND `title`<>'查询设备共享授权';
UPDATE `sys_api` SET `title`='查询统计覆盖率' WHERE `path`='/api/gb28181/device-traffic/coverage' AND `method`='GET' AND `title`<>'查询统计覆盖率';
UPDATE `sys_api` SET `title`='查询实时流量' WHERE `path`='/api/gb28181/device-traffic/realtime' AND `method`='GET' AND `title`<>'查询实时流量';
UPDATE `sys_api` SET `title`='查询流量会话' WHERE `path`='/api/gb28181/device-traffic/sessions' AND `method`='GET' AND `title`<>'查询流量会话';
UPDATE `sys_api` SET `title`='查询流量汇总' WHERE `path`='/api/gb28181/device-traffic/summary' AND `method`='GET' AND `title`<>'查询流量汇总';
UPDATE `sys_api` SET `title`='查询流量趋势' WHERE `path`='/api/gb28181/device-traffic/trend' AND `method`='GET' AND `title`<>'查询流量趋势';
UPDATE `sys_api` SET `title`='查询当前观看' WHERE `path`='/api/gb28181/device-traffic/viewers' AND `method`='GET' AND `title`<>'查询当前观看';
UPDATE `sys_api` SET `title`='下钻播放指标' WHERE `path`='/api/gb28181/home/drilldown/play' AND `method`='GET' AND `title`<>'下钻播放指标';
UPDATE `sys_api` SET `title`='下钻 SIP 指标' WHERE `path`='/api/gb28181/home/drilldown/sip' AND `method`='GET' AND `title`<>'下钻 SIP 指标';
UPDATE `sys_api` SET `title`='下钻流量指标' WHERE `path`='/api/gb28181/home/drilldown/traffic' AND `method`='GET' AND `title`<>'下钻流量指标';
UPDATE `sys_api` SET `title`='读取仪表盘布局' WHERE `path`='/api/gb28181/home/layout' AND `method`='GET' AND `title`<>'读取仪表盘布局';
UPDATE `sys_api` SET `title`='读取首页汇总' WHERE `path`='/api/gb28181/home/summary' AND `method`='GET' AND `title`<>'读取首页汇总';
UPDATE `sys_api` SET `title`='发起实时点播' WHERE `path`='/api/gb28181/play/:deviceId/:channelId' AND `method`='POST' AND `title`<>'发起实时点播';
UPDATE `sys_api` SET `title`='申请固定播放地址授权' WHERE `path`='/api/gb28181/play/:deviceId/:channelId/authorization' AND `method`='POST' AND `title`<>'申请固定播放地址授权';
UPDATE `sys_api` SET `title`='查询播放方案' WHERE `path`='/api/gb28181/playback-schemes' AND `method`='GET' AND `title`<>'查询播放方案';
UPDATE `sys_api` SET `title`='创建播放方案' WHERE `path`='/api/gb28181/playback-schemes' AND `method`='POST' AND `title`<>'创建播放方案';
UPDATE `sys_api` SET `title`='删除播放方案' WHERE `path`='/api/gb28181/playback-schemes/:id' AND `method`='DELETE' AND `title`<>'删除播放方案';
UPDATE `sys_api` SET `title`='查看播放方案' WHERE `path`='/api/gb28181/playback-schemes/:id' AND `method`='GET' AND `title`<>'查看播放方案';
UPDATE `sys_api` SET `title`='重命名播放方案' WHERE `path`='/api/gb28181/playback-schemes/:id' AND `method`='PATCH' AND `title`<>'重命名播放方案';
UPDATE `sys_api` SET `title`='覆盖播放方案' WHERE `path`='/api/gb28181/playback-schemes/:id/layout' AND `method`='PUT' AND `title`<>'覆盖播放方案';
UPDATE `sys_api` SET `title`='新建录像计划' WHERE `path`='/api/gb28181/recording-plans' AND `method`='POST' AND `title`<>'新建录像计划';
UPDATE `sys_api` SET `title`='删除录像计划' WHERE `path`='/api/gb28181/recording-plans/:id' AND `method`='DELETE' AND `title`<>'删除录像计划';
UPDATE `sys_api` SET `title`='查看录像计划' WHERE `path`='/api/gb28181/recording-plans/:id' AND `method`='GET' AND `title`<>'查看录像计划';
UPDATE `sys_api` SET `title`='编辑录像计划' WHERE `path`='/api/gb28181/recording-plans/:id' AND `method`='PUT' AND `title`<>'编辑录像计划';
UPDATE `sys_api` SET `title`='搜索分配通道' WHERE `path`='/api/gb28181/recording-plans/:id/assignment-options/channels' AND `method`='GET' AND `title`<>'搜索分配通道';
UPDATE `sys_api` SET `title`='搜索分配设备' WHERE `path`='/api/gb28181/recording-plans/:id/assignment-options/devices' AND `method`='GET' AND `title`<>'搜索分配设备';
UPDATE `sys_api` SET `title`='提交录像计划分配' WHERE `path`='/api/gb28181/recording-plans/:id/assignments' AND `method`='POST' AND `title`<>'提交录像计划分配';
UPDATE `sys_api` SET `title`='启停录像计划' WHERE `path`='/api/gb28181/recording-plans/:id/status' AND `method`='PATCH' AND `title`<>'启停录像计划';
UPDATE `sys_api` SET `title`='切换通道录像模式' WHERE `path`='/api/gb28181/recording-plans/channels/:channelId/recording-mode' AND `method`='PATCH' AND `title`<>'切换通道录像模式';
UPDATE `sys_api` SET `title`='SIP Trace 报文详情' WHERE `path`='/api/gb28181/sip-traces/messages/:id' AND `method`='GET' AND `title`<>'SIP Trace 报文详情';
UPDATE `sys_api` SET `title`='SIP Trace 会话报文' WHERE `path`='/api/gb28181/sip-traces/sessions/:callId/messages' AND `method`='GET' AND `title`<>'SIP Trace 会话报文';
UPDATE `sys_api` SET `title`='读取 SIP 仪表盘快照' WHERE `path`='/api/gb28181/sip/dashboard/snapshot' AND `method`='GET' AND `title`<>'读取 SIP 仪表盘快照';
UPDATE `sys_api` SET `title`='读取 SIP 平台信息' WHERE `path`='/api/gb28181/sip/platform' AND `method`='GET' AND `title`<>'读取 SIP 平台信息';
UPDATE `sys_api` SET `title`='生成设备接入二维码' WHERE `path`='/api/gb28181/sip/qr/token' AND `method`='POST' AND `title`<>'生成设备接入二维码';
UPDATE `sys_api` SET `title`='读取全局通道音频配置' WHERE `path`='/api/gb28181/sip/service-config/default-channel-audio' AND `method`='GET' AND `title`<>'读取全局通道音频配置';
UPDATE `sys_api` SET `title`='修改全局通道音频配置' WHERE `path`='/api/gb28181/sip/service-config/default-channel-audio' AND `method`='PUT' AND `title`<>'修改全局通道音频配置';
UPDATE `sys_api` SET `title`='设置默认码流传输方式' WHERE `path`='/api/gb28181/sip/service-config/default-channel-stream-transport' AND `method`='PUT' AND `title`<>'设置默认码流传输方式';
UPDATE `sys_api` SET `title`='读取默认播放协议' WHERE `path`='/api/gb28181/sip/service-config/default-playback-protocol' AND `method`='GET' AND `title`<>'读取默认播放协议';
UPDATE `sys_api` SET `title`='修改默认播放协议' WHERE `path`='/api/gb28181/sip/service-config/default-playback-protocol' AND `method`='PUT' AND `title`<>'修改默认播放协议';
UPDATE `sys_api` SET `title`='读取固定地址播放配置' WHERE `path`='/api/gb28181/sip/service-config/fixed-address-playback' AND `method`='GET' AND `title`<>'读取固定地址播放配置';
UPDATE `sys_api` SET `title`='修改固定地址播放配置' WHERE `path`='/api/gb28181/sip/service-config/fixed-address-playback' AND `method`='PUT' AND `title`<>'修改固定地址播放配置';
UPDATE `sys_api` SET `title`='读取全局订阅项目' WHERE `path`='/api/gb28181/sip/service-config/global-subscriptions' AND `method`='GET' AND `title`<>'读取全局订阅项目';
UPDATE `sys_api` SET `title`='修改全局订阅项目' WHERE `path`='/api/gb28181/sip/service-config/global-subscriptions' AND `method`='PUT' AND `title`<>'修改全局订阅项目';
UPDATE `sys_api` SET `title`='读取忽略通道离线异常通知配置' WHERE `path`='/api/gb28181/sip/service-config/ignore-channel-offline-status-notify' AND `method`='GET' AND `title`<>'读取忽略通道离线异常通知配置';
UPDATE `sys_api` SET `title`='修改忽略通道离线异常通知配置' WHERE `path`='/api/gb28181/sip/service-config/ignore-channel-offline-status-notify' AND `method`='PUT' AND `title`<>'修改忽略通道离线异常通知配置';
UPDATE `sys_api` SET `title`='读取收到心跳恢复设备上线配置' WHERE `path`='/api/gb28181/sip/service-config/online-on-heartbeat' AND `method`='GET' AND `title`<>'读取收到心跳恢复设备上线配置';
UPDATE `sys_api` SET `title`='修改收到心跳恢复设备上线配置' WHERE `path`='/api/gb28181/sip/service-config/online-on-heartbeat' AND `method`='PUT' AND `title`<>'修改收到心跳恢复设备上线配置';
UPDATE `sys_api` SET `title`='读取播放鉴权配置' WHERE `path`='/api/gb28181/sip/service-config/play-auth' AND `method`='GET' AND `title`<>'读取播放鉴权配置';
UPDATE `sys_api` SET `title`='修改播放鉴权配置' WHERE `path`='/api/gb28181/sip/service-config/play-auth' AND `method`='PUT' AND `title`<>'修改播放鉴权配置';
UPDATE `sys_api` SET `title`='读取回放参数' WHERE `path`='/api/gb28181/sip/service-config/playback-settings' AND `method`='GET' AND `title`<>'读取回放参数';
UPDATE `sys_api` SET `title`='修改回放参数' WHERE `path`='/api/gb28181/sip/service-config/playback-settings' AND `method`='PUT' AND `title`<>'修改回放参数';
UPDATE `sys_api` SET `title`='修改移动位置历史轨迹配置' WHERE `path`='/api/gb28181/sip/service-config/position-history' AND `method`='PUT' AND `title`<>'修改移动位置历史轨迹配置';
UPDATE `sys_api` SET `title`='读取预分配模式' WHERE `path`='/api/gb28181/sip/service-config/preallocation-mode' AND `method`='GET' AND `title`<>'读取预分配模式';
UPDATE `sys_api` SET `title`='修改预分配模式' WHERE `path`='/api/gb28181/sip/service-config/preallocation-mode' AND `method`='PUT' AND `title`<>'修改预分配模式';
UPDATE `sys_api` SET `title`='读取云台默认速度配置' WHERE `path`='/api/gb28181/sip/service-config/ptz-default-speed' AND `method`='GET' AND `title`<>'读取云台默认速度配置';
UPDATE `sys_api` SET `title`='修改云台默认速度配置' WHERE `path`='/api/gb28181/sip/service-config/ptz-default-speed' AND `method`='PUT' AND `title`<>'修改云台默认速度配置';
UPDATE `sys_api` SET `title`='读取报警消息存储配置' WHERE `path`='/api/gb28181/sip/service-config/save-alarm-messages' AND `method`='GET' AND `title`<>'读取报警消息存储配置';
UPDATE `sys_api` SET `title`='修改报警消息存储配置' WHERE `path`='/api/gb28181/sip/service-config/save-alarm-messages' AND `method`='PUT' AND `title`<>'修改报警消息存储配置';
UPDATE `sys_api` SET `title`='设置 SDP 扩展参数' WHERE `path`='/api/gb28181/sip/service-config/sdp-extension' AND `method`='PUT' AND `title`<>'设置 SDP 扩展参数';
UPDATE `sys_api` SET `title`='读取 SIP 命令超时时间' WHERE `path`='/api/gb28181/sip/service-config/sip-command-timeout' AND `method`='GET' AND `title`<>'读取 SIP 命令超时时间';
UPDATE `sys_api` SET `title`='修改 SIP 命令超时时间' WHERE `path`='/api/gb28181/sip/service-config/sip-command-timeout' AND `method`='PUT' AND `title`<>'修改 SIP 命令超时时间';
UPDATE `sys_api` SET `title`='读取 SIP 日志配置' WHERE `path`='/api/gb28181/sip/service-config/sip-log' AND `method`='GET' AND `title`<>'读取 SIP 日志配置';
UPDATE `sys_api` SET `title`='修改 SIP 日志配置' WHERE `path`='/api/gb28181/sip/service-config/sip-log' AND `method`='PUT' AND `title`<>'修改 SIP 日志配置';
UPDATE `sys_api` SET `title`='读取设备上线同步通道配置' WHERE `path`='/api/gb28181/sip/service-config/sync-channels-on-online' AND `method`='GET' AND `title`<>'读取设备上线同步通道配置';
UPDATE `sys_api` SET `title`='修改设备上线同步通道配置' WHERE `path`='/api/gb28181/sip/service-config/sync-channels-on-online' AND `method`='PUT' AND `title`<>'修改设备上线同步通道配置';
UPDATE `sys_api` SET `title`='保存 SIP 配置' WHERE `path`='/api/gb28181/sip/setup/config' AND `method`='PUT' AND `title`<>'保存 SIP 配置';
UPDATE `sys_api` SET `title`='读取本机网络接口' WHERE `path`='/api/gb28181/sip/setup/network-interfaces' AND `method`='GET' AND `title`<>'读取本机网络接口';
UPDATE `sys_api` SET `title`='暂缓 SIP 配置' WHERE `path`='/api/gb28181/sip/setup/skip' AND `method`='POST' AND `title`<>'暂缓 SIP 配置';
UPDATE `sys_api` SET `title`='读取 SIP 配置状态' WHERE `path`='/api/gb28181/sip/setup/status' AND `method`='GET' AND `title`<>'读取 SIP 配置状态';
UPDATE `sys_api` SET `title`='发起视频探针检测' WHERE `path`='/api/gb28181/stream-probes/:streamId' AND `method`='POST' AND `title`<>'发起视频探针检测';
UPDATE `sys_api` SET `title`='查询探针检测结果' WHERE `path`='/api/gb28181/stream-probes/operations/:operationId' AND `method`='GET' AND `title`<>'查询探针检测结果';
UPDATE `sys_api` SET `title`='查看媒体节点列表' WHERE `path`='/api/gb28181/zlm/nodes' AND `method`='GET' AND `title`<>'查看媒体节点列表';
UPDATE `sys_api` SET `title`='新增媒体节点' WHERE `path`='/api/gb28181/zlm/nodes' AND `method`='POST' AND `title`<>'新增媒体节点';
UPDATE `sys_api` SET `title`='删除媒体节点' WHERE `path`='/api/gb28181/zlm/nodes/:id' AND `method`='DELETE' AND `title`<>'删除媒体节点';
UPDATE `sys_api` SET `title`='查看媒体节点详情' WHERE `path`='/api/gb28181/zlm/nodes/:id' AND `method`='GET' AND `title`<>'查看媒体节点详情';
UPDATE `sys_api` SET `title`='更新媒体节点' WHERE `path`='/api/gb28181/zlm/nodes/:id' AND `method`='PUT' AND `title`<>'更新媒体节点';
UPDATE `sys_api` SET `title`='激活媒体节点' WHERE `path`='/api/gb28181/zlm/nodes/:id/activate' AND `method`='POST' AND `title`<>'激活媒体节点';
UPDATE `sys_api` SET `title`='查看媒体服务配置' WHERE `path`='/api/gb28181/zlm/nodes/:id/config' AND `method`='GET' AND `title`<>'查看媒体服务配置';
UPDATE `sys_api` SET `title`='更新媒体服务配置' WHERE `path`='/api/gb28181/zlm/nodes/:id/config' AND `method`='PUT' AND `title`<>'更新媒体服务配置';
UPDATE `sys_api` SET `title`='测试媒体节点连接' WHERE `path`='/api/gb28181/zlm/nodes/:id/config/test-connection' AND `method`='POST' AND `title`<>'测试媒体节点连接';
UPDATE `sys_api` SET `title`='停用媒体节点' WHERE `path`='/api/gb28181/zlm/nodes/:id/disable' AND `method`='POST' AND `title`<>'停用媒体节点';
UPDATE `sys_api` SET `title`='启用媒体节点' WHERE `path`='/api/gb28181/zlm/nodes/:id/enable' AND `method`='POST' AND `title`<>'启用媒体节点';
UPDATE `sys_api` SET `title`='查看 FFmpeg 源列表' WHERE `path`='/api/gb28181/zlm/nodes/:id/ffmpeg-sources' AND `method`='GET' AND `title`<>'查看 FFmpeg 源列表';
UPDATE `sys_api` SET `title`='新增 FFmpeg 源' WHERE `path`='/api/gb28181/zlm/nodes/:id/ffmpeg-sources' AND `method`='POST' AND `title`<>'新增 FFmpeg 源';
UPDATE `sys_api` SET `title`='删除 FFmpeg 源' WHERE `path`='/api/gb28181/zlm/nodes/:id/ffmpeg-sources/:key' AND `method`='DELETE' AND `title`<>'删除 FFmpeg 源';
UPDATE `sys_api` SET `title`='FFmpeg 源预检' WHERE `path`='/api/gb28181/zlm/nodes/:id/ffmpeg-sources/:key/preflight' AND `method`='POST' AND `title`<>'FFmpeg 源预检';
UPDATE `sys_api` SET `title`='踢除节点上的全部会话' WHERE `path`='/api/gb28181/zlm/nodes/:id/kick' AND `method`='POST' AND `title`<>'踢除节点上的全部会话';
UPDATE `sys_api` SET `title`='媒体节点维护' WHERE `path`='/api/gb28181/zlm/nodes/:id/maintenance' AND `method`='POST' AND `title`<>'媒体节点维护';
UPDATE `sys_api` SET `title`='查看拉流代理列表' WHERE `path`='/api/gb28181/zlm/nodes/:id/proxies/pull' AND `method`='GET' AND `title`<>'查看拉流代理列表';
UPDATE `sys_api` SET `title`='新增拉流代理' WHERE `path`='/api/gb28181/zlm/nodes/:id/proxies/pull' AND `method`='POST' AND `title`<>'新增拉流代理';
UPDATE `sys_api` SET `title`='删除拉流代理' WHERE `path`='/api/gb28181/zlm/nodes/:id/proxies/pull/:key' AND `method`='DELETE' AND `title`<>'删除拉流代理';
UPDATE `sys_api` SET `title`='查看拉流代理详情' WHERE `path`='/api/gb28181/zlm/nodes/:id/proxies/pull/:key' AND `method`='GET' AND `title`<>'查看拉流代理详情';
UPDATE `sys_api` SET `title`='拉流代理预检' WHERE `path`='/api/gb28181/zlm/nodes/:id/proxies/pull/:key/preflight' AND `method`='POST' AND `title`<>'拉流代理预检';
UPDATE `sys_api` SET `title`='查看推流代理列表' WHERE `path`='/api/gb28181/zlm/nodes/:id/proxies/push' AND `method`='GET' AND `title`<>'查看推流代理列表';
UPDATE `sys_api` SET `title`='新增推流代理' WHERE `path`='/api/gb28181/zlm/nodes/:id/proxies/push' AND `method`='POST' AND `title`<>'新增推流代理';
UPDATE `sys_api` SET `title`='删除推流代理' WHERE `path`='/api/gb28181/zlm/nodes/:id/proxies/push/:key' AND `method`='DELETE' AND `title`<>'删除推流代理';
UPDATE `sys_api` SET `title`='查看推流代理详情' WHERE `path`='/api/gb28181/zlm/nodes/:id/proxies/push/:key' AND `method`='GET' AND `title`<>'查看推流代理详情';
UPDATE `sys_api` SET `title`='推流代理预检' WHERE `path`='/api/gb28181/zlm/nodes/:id/proxies/push/:key/preflight' AND `method`='POST' AND `title`<>'推流代理预检';
UPDATE `sys_api` SET `title`='强制停止录制' WHERE `path`='/api/gb28181/zlm/nodes/:id/recordings/runtime/force-stop' AND `method`='POST' AND `title`<>'强制停止录制';
UPDATE `sys_api` SET `title`='强制停止录制预检' WHERE `path`='/api/gb28181/zlm/nodes/:id/recordings/runtime/force-stop/preflight' AND `method`='POST' AND `title`<>'强制停止录制预检';
UPDATE `sys_api` SET `title`='开始录制' WHERE `path`='/api/gb28181/zlm/nodes/:id/recordings/runtime/start' AND `method`='POST' AND `title`<>'开始录制';
UPDATE `sys_api` SET `title`='开始录制预检' WHERE `path`='/api/gb28181/zlm/nodes/:id/recordings/runtime/start/preflight' AND `method`='POST' AND `title`<>'开始录制预检';
UPDATE `sys_api` SET `title`='查询录制运行状态' WHERE `path`='/api/gb28181/zlm/nodes/:id/recordings/runtime/status' AND `method`='GET' AND `title`<>'查询录制运行状态';
UPDATE `sys_api` SET `title`='停止录制' WHERE `path`='/api/gb28181/zlm/nodes/:id/recordings/runtime/stop' AND `method`='POST' AND `title`<>'停止录制';
UPDATE `sys_api` SET `title`='停止录制预检' WHERE `path`='/api/gb28181/zlm/nodes/:id/recordings/runtime/stop/preflight' AND `method`='POST' AND `title`<>'停止录制预检';
UPDATE `sys_api` SET `title`='查询媒体服务重启状态' WHERE `path`='/api/gb28181/zlm/nodes/:id/restart' AND `method`='GET' AND `title`<>'查询媒体服务重启状态';
UPDATE `sys_api` SET `title`='重启媒体服务' WHERE `path`='/api/gb28181/zlm/nodes/:id/restart' AND `method`='POST' AND `title`<>'重启媒体服务';
UPDATE `sys_api` SET `title`='查看 RTP 服务列表' WHERE `path`='/api/gb28181/zlm/nodes/:id/rtp-servers' AND `method`='GET' AND `title`<>'查看 RTP 服务列表';
UPDATE `sys_api` SET `title`='新增 RTP 服务' WHERE `path`='/api/gb28181/zlm/nodes/:id/rtp-servers' AND `method`='POST' AND `title`<>'新增 RTP 服务';
UPDATE `sys_api` SET `title`='关闭 RTP 服务' WHERE `path`='/api/gb28181/zlm/nodes/:id/rtp-servers/close' AND `method`='POST' AND `title`<>'关闭 RTP 服务';
UPDATE `sys_api` SET `title`='关闭 RTP 服务预检' WHERE `path`='/api/gb28181/zlm/nodes/:id/rtp-servers/close/preflight' AND `method`='POST' AND `title`<>'关闭 RTP 服务预检';
UPDATE `sys_api` SET `title`='强制关闭 RTP 服务' WHERE `path`='/api/gb28181/zlm/nodes/:id/rtp-servers/force-close' AND `method`='POST' AND `title`<>'强制关闭 RTP 服务';
UPDATE `sys_api` SET `title`='查询媒体节点运行状态' WHERE `path`='/api/gb28181/zlm/nodes/:id/runtime' AND `method`='GET' AND `title`<>'查询媒体节点运行状态';
UPDATE `sys_api` SET `title`='踢除指定播放会话' WHERE `path`='/api/gb28181/zlm/nodes/:id/sessions/kick' AND `method`='POST' AND `title`<>'踢除指定播放会话';
UPDATE `sys_api` SET `title`='查询会话网络信息' WHERE `path`='/api/gb28181/zlm/nodes/:id/sessions/network' AND `method`='GET' AND `title`<>'查询会话网络信息';
UPDATE `sys_api` SET `title`='查看节点会话观看者' WHERE `path`='/api/gb28181/zlm/nodes/:id/sessions/viewers' AND `method`='GET' AND `title`<>'查看节点会话观看者';
UPDATE `sys_api` SET `title`='查看媒体节点流列表' WHERE `path`='/api/gb28181/zlm/nodes/:id/streams' AND `method`='GET' AND `title`<>'查看媒体节点流列表';
UPDATE `sys_api` SET `title`='关闭媒体流' WHERE `path`='/api/gb28181/zlm/nodes/:id/streams/close' AND `method`='POST' AND `title`<>'关闭媒体流';
UPDATE `sys_api` SET `title`='批量关闭媒体流' WHERE `path`='/api/gb28181/zlm/nodes/:id/streams/close/batch' AND `method`='POST' AND `title`<>'批量关闭媒体流';
UPDATE `sys_api` SET `title`='批量关闭媒体流预检' WHERE `path`='/api/gb28181/zlm/nodes/:id/streams/close/batch/preflight' AND `method`='POST' AND `title`<>'批量关闭媒体流预检';
UPDATE `sys_api` SET `title`='关闭媒体流预检' WHERE `path`='/api/gb28181/zlm/nodes/:id/streams/close/preflight' AND `method`='POST' AND `title`<>'关闭媒体流预检';
UPDATE `sys_api` SET `title`='查看媒体流详情' WHERE `path`='/api/gb28181/zlm/nodes/:id/streams/detail' AND `method`='GET' AND `title`<>'查看媒体流详情';
UPDATE `sys_api` SET `title`='强制关闭媒体流' WHERE `path`='/api/gb28181/zlm/nodes/:id/streams/force-close' AND `method`='POST' AND `title`<>'强制关闭媒体流';
UPDATE `sys_api` SET `title`='发放播放授权' WHERE `path`='/api/gb28181/zlm/nodes/:id/streams/playback-grant' AND `method`='POST' AND `title`<>'发放播放授权';
UPDATE `sys_api` SET `title`='截取媒体流快照' WHERE `path`='/api/gb28181/zlm/nodes/:id/streams/snapshot' AND `method`='GET' AND `title`<>'截取媒体流快照';
UPDATE `sys_api` SET `title`='查询媒体流观看者' WHERE `path`='/api/gb28181/zlm/nodes/:id/streams/viewers' AND `method`='GET' AND `title`<>'查询媒体流观看者';
UPDATE `sys_api` SET `title`='探测媒体节点' WHERE `path`='/api/gb28181/zlm/nodes/probe' AND `method`='POST' AND `title`<>'探测媒体节点';
UPDATE `sys_api` SET `title`='查看媒体服务总览' WHERE `path`='/api/gb28181/zlm/overview' AND `method`='GET' AND `title`<>'查看媒体服务总览';
UPDATE `sys_api` SET `title`='查看媒体调度策略' WHERE `path`='/api/gb28181/zlm/scheduler' AND `method`='GET' AND `title`<>'查看媒体调度策略';
UPDATE `sys_api` SET `title`='更新媒体调度策略' WHERE `path`='/api/gb28181/zlm/scheduler' AND `method`='PUT' AND `title`<>'更新媒体调度策略';
UPDATE `sys_api` SET `title`='查询媒体调度日志' WHERE `path`='/api/gb28181/zlm/scheduler/logs' AND `method`='GET' AND `title`<>'查询媒体调度日志';
UPDATE `sys_api` SET `title`='查看媒体流列表' WHERE `path`='/api/gb28181/zlm/streams' AND `method`='GET' AND `title`<>'查看媒体流列表';
UPDATE `sys_api` SET `title`='查询单条数据' WHERE `path`='/api/plugins/example/:id' AND `method`='GET' AND `title`<>'查询单条数据';
UPDATE `sys_api` SET `title`='新增插件示例' WHERE `path`='/api/plugins/example/add' AND `method`='POST' AND `title`<>'新增插件示例';
UPDATE `sys_api` SET `title`='删除插件示例' WHERE `path`='/api/plugins/example/delete' AND `method`='DELETE' AND `title`<>'删除插件示例';
UPDATE `sys_api` SET `title`='修改' WHERE `path`='/api/plugins/example/edit' AND `method`='PUT' AND `title`<>'修改';
UPDATE `sys_api` SET `title`='分片上传取消上传' WHERE `path`='/api/sysAffix/chunk/cancel' AND `method`='DELETE' AND `title`<>'分片上传取消上传';
UPDATE `sys_api` SET `title`='分片上传初始化' WHERE `path`='/api/sysAffix/chunk/init' AND `method`='POST' AND `title`<>'分片上传初始化';
UPDATE `sys_api` SET `title`='分片上传合并分片' WHERE `path`='/api/sysAffix/chunk/merge' AND `method`='POST' AND `title`<>'分片上传合并分片';
UPDATE `sys_api` SET `title`='分片上传上传分片' WHERE `path`='/api/sysAffix/chunk/upload' AND `method`='POST' AND `title`<>'分片上传上传分片';
UPDATE `sys_api` SET `title`='下载文件' WHERE `path`='/api/sysAffix/download/:id' AND `method`='GET' AND `title`<>'下载文件';
UPDATE `sys_api` SET `title`='上传文件' WHERE `path`='/api/sysAffix/upload' AND `method`='POST' AND `title`<>'上传文件';
UPDATE `sys_api` SET `title`='根据ID获取API信息' WHERE `path`='/api/sysApi/:id' AND `method`='GET' AND `title`<>'根据ID获取API信息';
UPDATE `sys_api` SET `title`='新增API' WHERE `path`='/api/sysApi/add' AND `method`='POST' AND `title`<>'新增API';
UPDATE `sys_api` SET `title`='删除API' WHERE `path`='/api/sysApi/delete' AND `method`='DELETE' AND `title`<>'删除API';
UPDATE `sys_api` SET `title`='更新API' WHERE `path`='/api/sysApi/edit' AND `method`='PUT' AND `title`<>'更新API';
UPDATE `sys_api` SET `title`='API列表' WHERE `path`='/api/sysApi/list' AND `method`='GET' AND `title`<>'API列表';
UPDATE `sys_api` SET `title`='获取部门列表' WHERE `path`='/api/sysDepartment/getDivision' AND `method`='GET' AND `title`<>'获取部门列表';
UPDATE `sys_api` SET `title`='新增字典' WHERE `path`='/api/sysDict/add' AND `method`='POST' AND `title`<>'新增字典';
UPDATE `sys_api` SET `title`='删除字典' WHERE `path`='/api/sysDict/delete' AND `method`='DELETE' AND `title`<>'删除字典';
UPDATE `sys_api` SET `title`='更新字典' WHERE `path`='/api/sysDict/edit' AND `method`='PUT' AND `title`<>'更新字典';
UPDATE `sys_api` SET `title`='根据字典编码获取字典项列表' WHERE `path`='/api/sysDictItem/getByDictCode/:dictCode' AND `method`='GET' AND `title`<>'根据字典编码获取字典项列表';
UPDATE `sys_api` SET `title`='删除代码生成配置和字段信息' WHERE `path`='/api/sysGen/:id' AND `method`='DELETE' AND `title`<>'删除代码生成配置和字段信息';
UPDATE `sys_api` SET `title`='获取代码生成配置详情' WHERE `path`='/api/sysGen/:id' AND `method`='GET' AND `title`<>'获取代码生成配置详情';
UPDATE `sys_api` SET `title`=' 批量创建代码生成配置' WHERE `path`='/api/sysGen/batchInsert' AND `method`='POST' AND `title`<>' 批量创建代码生成配置';
UPDATE `sys_api` SET `title`='更新代码生成配置和字段信息' WHERE `path`='/api/sysGen/update' AND `method`='PUT' AND `title`<>'更新代码生成配置和字段信息';
UPDATE `sys_api` SET `title`='定时任务日志删除' WHERE `path`='/api/sysJobResults/delete' AND `method`='DELETE' AND `title`<>'定时任务日志删除';
UPDATE `sys_api` SET `title`='定时任务获取数据' WHERE `path`='/api/sysJobs/:id' AND `method`='GET' AND `title`<>'定时任务获取数据';
UPDATE `sys_api` SET `title`='定时任务新增' WHERE `path`='/api/sysJobs/add' AND `method`='POST' AND `title`<>'定时任务新增';
UPDATE `sys_api` SET `title`='定时任务删除' WHERE `path`='/api/sysJobs/delete' AND `method`='DELETE' AND `title`<>'定时任务删除';
UPDATE `sys_api` SET `title`='定时任务编辑' WHERE `path`='/api/sysJobs/edit' AND `method`='PUT' AND `title`<>'定时任务编辑';
UPDATE `sys_api` SET `title`='定时任务设置任务状态' WHERE `path`='/api/sysJobs/setStatus' AND `method`='PUT' AND `title`<>'定时任务设置任务状态';
UPDATE `sys_api` SET `title`='新增菜单' WHERE `path`='/api/sysMenu/add' AND `method`='POST' AND `title`<>'新增菜单';
UPDATE `sys_api` SET `title`='根据菜单ID获取API的ID集合' WHERE `path`='/api/sysMenu/apis/:id' AND `method`='GET' AND `title`<>'根据菜单ID获取API的ID集合';
UPDATE `sys_api` SET `title`='批量删除' WHERE `path`='/api/sysMenu/batchDelete' AND `method`='DELETE' AND `title`<>'批量删除';
UPDATE `sys_api` SET `title`='删除菜单' WHERE `path`='/api/sysMenu/delete' AND `method`='DELETE' AND `title`<>'删除菜单';
UPDATE `sys_api` SET `title`='更新菜单' WHERE `path`='/api/sysMenu/edit' AND `method`='PUT' AND `title`<>'更新菜单';
UPDATE `sys_api` SET `title`='导出菜单' WHERE `path`='/api/sysMenu/export' AND `method`='GET' AND `title`<>'导出菜单';
UPDATE `sys_api` SET `title`='获取完整菜单列表' WHERE `path`='/api/sysMenu/getMenuList' AND `method`='GET' AND `title`<>'获取完整菜单列表';
UPDATE `sys_api` SET `title`='获取用户权限菜单' WHERE `path`='/api/sysMenu/getRouters' AND `method`='GET' AND `title`<>'获取用户权限菜单';
UPDATE `sys_api` SET `title`='设置菜单API权限' WHERE `path`='/api/sysMenu/setApis' AND `method`='POST' AND `title`<>'设置菜单API权限';
UPDATE `sys_api` SET `title`='日志删除' WHERE `path`='/api/sysOperationLog/delete' AND `method`='DELETE' AND `title`<>'日志删除';
UPDATE `sys_api` SET `title`='日志导出' WHERE `path`='/api/sysOperationLog/export' AND `method`='GET' AND `title`<>'日志导出';
UPDATE `sys_api` SET `title`='新增角色' WHERE `path`='/api/sysRole/add' AND `method`='POST' AND `title`<>'新增角色';
UPDATE `sys_api` SET `title`='添加角色的菜单权限' WHERE `path`='/api/sysRole/addRoleMenu' AND `method`='POST' AND `title`<>'添加角色的菜单权限';
UPDATE `sys_api` SET `title`='设置数据权限' WHERE `path`='/api/sysRole/dataScope' AND `method`='PUT' AND `title`<>'设置数据权限';
UPDATE `sys_api` SET `title`='删除角色' WHERE `path`='/api/sysRole/delete' AND `method`='DELETE' AND `title`<>'删除角色';
UPDATE `sys_api` SET `title`='更新角色' WHERE `path`='/api/sysRole/edit' AND `method`='PUT' AND `title`<>'更新角色';
UPDATE `sys_api` SET `title`='根据角色ID获取角色菜单权限' WHERE `path`='/api/sysRole/getUserPermission/:roleId' AND `method`='GET' AND `title`<>'根据角色ID获取角色菜单权限';
UPDATE `sys_api` SET `title`='新增用户' WHERE `path`='/api/users/add' AND `method`='POST' AND `title`<>'新增用户';
UPDATE `sys_api` SET `title`='删除用户' WHERE `path`='/api/users/delete' AND `method`='DELETE' AND `title`<>'删除用户';
UPDATE `sys_api` SET `title`='更新用户信息' WHERE `path`='/api/users/edit' AND `method`='PUT' AND `title`<>'更新用户信息';
UPDATE `sys_api` SET `title`='用户登出' WHERE `path`='/api/users/logout' AND `method`='POST' AND `title`<>'用户登出';
UPDATE `sys_api` SET `title`='获取当前用户信息' WHERE `path`='/api/users/profile' AND `method`='GET' AND `title`<>'获取当前用户信息';
