-- GB28181 cascade tables. MySQL 5.7+, repeatable for a new cascade installation.
CREATE TABLE IF NOT EXISTS `gb_cascade_platform` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(128) NOT NULL,
  `upstream_server_id` varchar(20) NOT NULL,
  `upstream_domain` varchar(255) NOT NULL,
  `host` varchar(255) NOT NULL,
  `port` int NOT NULL,
  `local_device_id` varchar(20) NOT NULL,
  `local_domain` varchar(255) NOT NULL,
  `local_sip_ip` varchar(45) NOT NULL,
  `local_sip_port` int NOT NULL,
  `media_advertise_ip` varchar(45) DEFAULT NULL,
  `auth_username` varchar(255) DEFAULT NULL,
  `secret_nonce` varbinary(64) DEFAULT NULL,
  `secret_ciphertext` blob,
  `secret_alg` varchar(32) DEFAULT NULL,
  `secret_key_version` varchar(64) DEFAULT NULL,
  `profile_override` varchar(16) NOT NULL DEFAULT 'auto',
  `reported_gb_version` varchar(16) DEFAULT NULL,
  `reported_gb_version_at` datetime(3) DEFAULT NULL,
  `effective_version` varchar(16) NOT NULL DEFAULT '2016',
  `effective_version_source` varchar(32) NOT NULL DEFAULT 'default',
  `effective_version_at` datetime(3) DEFAULT NULL,
  `charset_override` varchar(32) DEFAULT NULL,
  `register_expires` int NOT NULL DEFAULT 3600,
  `keepalive_interval` int NOT NULL DEFAULT 60,
  `retry_policy` text,
  `transport` varchar(16) NOT NULL DEFAULT 'UDP',
  `catalog_batch_size` int NOT NULL DEFAULT 100,
  `publish_platform` tinyint(1) NOT NULL DEFAULT 0,
  `publish_civil` tinyint(1) NOT NULL DEFAULT 0,
  `publish_group` tinyint(1) NOT NULL DEFAULT 0,
  `max_streams` int NOT NULL DEFAULT 1,
  `ptz_enabled` tinyint(1) NOT NULL DEFAULT 0,
  `register_at` datetime(3) DEFAULT NULL,
  `register_expires_at` datetime(3) DEFAULT NULL,
  `heartbeat_at` datetime(3) DEFAULT NULL,
  `last_error_code` varchar(64) DEFAULT NULL,
  `last_error_message` text,
  `last_error_at` datetime(3) DEFAULT NULL,
  `enabled` tinyint(1) NOT NULL DEFAULT 0,
  `config_revision` bigint unsigned NOT NULL DEFAULT 1,
  `projection_revision` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cascade_platform_name` (`name`),
  UNIQUE KEY `uk_cascade_platform_local_identity` (`local_device_id`, `local_domain`),
  KEY `idx_cascade_platform_enabled` (`enabled`),
  KEY `idx_cascade_platform_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `gb_cascade_device_projection` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `platform_id` bigint unsigned NOT NULL,
  `source_device_id` bigint unsigned NOT NULL,
  `published_device_id` varchar(20) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `manufacturer` varchar(255) DEFAULT NULL,
  `model` varchar(255) DEFAULT NULL,
  `owner` varchar(255) DEFAULT NULL,
  `civil_code` varchar(32) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `parental` int NOT NULL DEFAULT 0,
  `secrecy` int NOT NULL DEFAULT 0,
  `active` tinyint(1) NOT NULL DEFAULT 1,
  `revision` bigint unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cascade_device_source` (`platform_id`, `source_device_id`),
  UNIQUE KEY `uk_cascade_device_published` (`platform_id`, `published_device_id`),
  KEY `idx_cascade_device_platform_active` (`platform_id`, `active`),
  KEY `idx_cascade_device_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `gb_cascade_channel_projection` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `platform_id` bigint unsigned NOT NULL,
  `device_projection_id` bigint unsigned NOT NULL,
  `source_channel_id` bigint unsigned NOT NULL,
  `published_channel_id` varchar(20) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `parent_override` varchar(20) DEFAULT NULL,
  `ptz_allowed` tinyint(1) NOT NULL DEFAULT 0,
  `active` tinyint(1) NOT NULL DEFAULT 1,
  `revision` bigint unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cascade_channel_source` (`platform_id`, `source_channel_id`),
  UNIQUE KEY `uk_cascade_channel_published` (`platform_id`, `published_channel_id`),
  KEY `idx_cascade_channel_platform_active` (`platform_id`, `active`),
  KEY `idx_cascade_channel_device_projection` (`device_projection_id`),
  KEY `idx_cascade_channel_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `gb_cascade_media_session` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `platform_id` bigint unsigned NOT NULL,
  `dialog_key` varchar(512) NOT NULL,
  `call_id` varchar(255) NOT NULL,
  `local_tag` varchar(255) DEFAULT NULL,
  `remote_tag` varchar(255) DEFAULT NULL,
  `cseq` bigint unsigned NOT NULL DEFAULT 0,
  `source_device_id` bigint unsigned NOT NULL,
  `source_channel_id` bigint unsigned NOT NULL,
  `published_channel_id` varchar(20) NOT NULL,
  `profile_version` varchar(16) DEFAULT NULL,
  `profile_charset` varchar(32) DEFAULT NULL,
  `sdp_summary` text,
  `zlm_node_id` bigint NOT NULL DEFAULT 0,
  `zlm_vhost` varchar(128) DEFAULT NULL,
  `zlm_app` varchar(64) DEFAULT NULL,
  `zlm_stream` varchar(128) DEFAULT NULL,
  `sender_ssrc` varchar(32) DEFAULT NULL,
  `transport` varchar(16) DEFAULT NULL,
  `remote_ip` varchar(45) DEFAULT NULL,
  `remote_port` int NOT NULL DEFAULT 0,
  `state` varchar(16) NOT NULL DEFAULT 'received',
  `failure_code` varchar(64) DEFAULT NULL,
  `failure_message` text,
  `received_at` datetime(3) DEFAULT NULL,
  `answered_at` datetime(3) DEFAULT NULL,
  `active_at` datetime(3) DEFAULT NULL,
  `closed_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cascade_media_dialog` (`dialog_key`),
  KEY `idx_cascade_media_platform_state` (`platform_id`, `state`),
  KEY `idx_cascade_media_call_id` (`call_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
