SET @schema_name := DATABASE();
SET @sql := IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = @schema_name AND table_name = 'gb_sip_trace_message' AND column_name = 'from_id') = 0, 'ALTER TABLE `gb_sip_trace_message` ADD COLUMN `from_id` varchar(64) NOT NULL DEFAULT ''''', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = @schema_name AND table_name = 'gb_sip_trace_message' AND column_name = 'to_id') = 0, 'ALTER TABLE `gb_sip_trace_message` ADD COLUMN `to_id` varchar(64) NOT NULL DEFAULT ''''', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = @schema_name AND table_name = 'gb_sip_trace_message' AND column_name = 'business_code') = 0, 'ALTER TABLE `gb_sip_trace_message` ADD COLUMN `business_code` varchar(64) NOT NULL DEFAULT ''unknown''', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = @schema_name AND table_name = 'gb_sip_trace_message' AND column_name = 'business_type') = 0, 'ALTER TABLE `gb_sip_trace_message` ADD COLUMN `business_type` varchar(64) NOT NULL DEFAULT ''未知业务''', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = @schema_name AND table_name = 'gb_sip_trace_message' AND column_name = 'business_confidence') = 0, 'ALTER TABLE `gb_sip_trace_message` ADD COLUMN `business_confidence` varchar(16) NOT NULL DEFAULT ''none''', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema = @schema_name AND table_name = 'gb_sip_trace_message' AND index_name = 'idx_gb_sip_trace_business_occurred') = 0, 'CREATE INDEX `idx_gb_sip_trace_business_occurred` ON `gb_sip_trace_message` (`business_code`, `occurred_at`)', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
