SET @schema_name := DATABASE();
SET @sql := IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = @schema_name AND table_name = 'gb_sip_trace_message' AND column_name = 'business_confidence') > 0, 'ALTER TABLE `gb_sip_trace_message` DROP COLUMN `business_confidence`', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = @schema_name AND table_name = 'gb_sip_trace_message' AND column_name = 'business_type') > 0, 'ALTER TABLE `gb_sip_trace_message` DROP COLUMN `business_type`', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = @schema_name AND table_name = 'gb_sip_trace_message' AND column_name = 'business_code') > 0, 'ALTER TABLE `gb_sip_trace_message` DROP COLUMN `business_code`', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = @schema_name AND table_name = 'gb_sip_trace_message' AND column_name = 'to_id') > 0, 'ALTER TABLE `gb_sip_trace_message` DROP COLUMN `to_id`', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = @schema_name AND table_name = 'gb_sip_trace_message' AND column_name = 'from_id') > 0, 'ALTER TABLE `gb_sip_trace_message` DROP COLUMN `from_id`', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
