-- 接口标题（sys_api.title）归一化。
--
-- 背景：sys_api.title 的**列语义是「权限名称」**（库注释 `COMMENT '权限名称'`），
-- 而「接口管理」页把它当「API标题」展示。生成器过去直接拿归属按钮名填 ——
-- 一个按钮挂 N 个接口时 N 行同名，页面无法区分（如「查看仪表盘」下 5 个接口
-- 分别查 summary / layout / 3 个 drilldown，全叫「查看仪表盘」）。
--
-- 新口径：接口名 = **接口自己的功能名**，由目录显式声明：
--   server/resource/database/gb28181/button-permissions.json 的 buttons[].apis[].title
--   server/resource/database/gb28181/guest-permissions.json 的 bindings[].apis[].title
-- 生成器（scripts/button-catalog.py / scripts/guest-permissions.py）优先取它，
-- 缺失才回落按钮名；「1 按钮挂多接口」的接口缺声明会被 button-catalog.test.py 拦下。
--
-- ⛔ 定位键是 (path, method) 而不是 id：各库 id 不同，path+method 才跨库稳定。
-- ⛔ title 不参与鉴权（鉴权走 casbin 的 path+method 与 sys_menu.permission），
--    纯展示元数据；本迁移只改名字，不动授权。
-- ⛔ 两个生成器的 sys_api INSERT 只有 WHERE NOT EXISTS、没有 UPDATE 分支
--    ⇒ 光改生成器修不了已有行，必须靠本迁移。

UPDATE [sys_api] SET [title]=N'获取指定数据库中的表集合' WHERE [path]=N'/api/codegen/tables' AND [method]=N'GET' AND [title]<>N'获取指定数据库中的表集合';
UPDATE [sys_api] SET [title]=N'物理删除单条告警' WHERE [path]=N'/api/gb28181/alarms/:id' AND [method]=N'DELETE' AND [title]<>N'物理删除单条告警';
UPDATE [sys_api] SET [title]=N'批量物理删除告警' WHERE [path]=N'/api/gb28181/alarms/batch-delete' AND [method]=N'POST' AND [title]<>N'批量物理删除告警';
UPDATE [sys_api] SET [title]=N'查看级联平台列表' WHERE [path]=N'/api/gb28181/cascade/platforms' AND [method]=N'GET' AND [title]<>N'查看级联平台列表';
UPDATE [sys_api] SET [title]=N'创建级联平台' WHERE [path]=N'/api/gb28181/cascade/platforms' AND [method]=N'POST' AND [title]<>N'创建级联平台';
UPDATE [sys_api] SET [title]=N'删除级联平台' WHERE [path]=N'/api/gb28181/cascade/platforms/:id' AND [method]=N'DELETE' AND [title]<>N'删除级联平台';
UPDATE [sys_api] SET [title]=N'查看级联平台' WHERE [path]=N'/api/gb28181/cascade/platforms/:id' AND [method]=N'GET' AND [title]<>N'查看级联平台';
UPDATE [sys_api] SET [title]=N'修改级联平台' WHERE [path]=N'/api/gb28181/cascade/platforms/:id' AND [method]=N'PUT' AND [title]<>N'修改级联平台';
UPDATE [sys_api] SET [title]=N'启用级联平台' WHERE [path]=N'/api/gb28181/cascade/platforms/:id/enable' AND [method]=N'POST' AND [title]<>N'启用级联平台';
UPDATE [sys_api] SET [title]=N'更新级联启用状态' WHERE [path]=N'/api/gb28181/cascade/platforms/:id/enabled' AND [method]=N'PUT' AND [title]<>N'更新级联启用状态';
UPDATE [sys_api] SET [title]=N'查看级联共享' WHERE [path]=N'/api/gb28181/cascade/platforms/:id/shares' AND [method]=N'GET' AND [title]<>N'查看级联共享';
UPDATE [sys_api] SET [title]=N'更新级联共享' WHERE [path]=N'/api/gb28181/cascade/platforms/:id/shares' AND [method]=N'PUT' AND [title]<>N'更新级联共享';
UPDATE [sys_api] SET [title]=N'查询通道收藏组' WHERE [path]=N'/api/gb28181/channel-favorite-groups' AND [method]=N'GET' AND [title]<>N'查询通道收藏组';
UPDATE [sys_api] SET [title]=N'新建通道收藏组' WHERE [path]=N'/api/gb28181/channel-favorite-groups' AND [method]=N'POST' AND [title]<>N'新建通道收藏组';
UPDATE [sys_api] SET [title]=N'删除通道收藏组' WHERE [path]=N'/api/gb28181/channel-favorite-groups/:id' AND [method]=N'DELETE' AND [title]<>N'删除通道收藏组';
UPDATE [sys_api] SET [title]=N'移除通道收藏' WHERE [path]=N'/api/gb28181/channel-favorite-groups/:id/channels' AND [method]=N'DELETE' AND [title]<>N'移除通道收藏';
UPDATE [sys_api] SET [title]=N'追加通道收藏' WHERE [path]=N'/api/gb28181/channel-favorite-groups/:id/channels' AND [method]=N'POST' AND [title]<>N'追加通道收藏';
UPDATE [sys_api] SET [title]=N'取消云端录像下载' WHERE [path]=N'/api/gb28181/cloud-recordings/downloads/:taskId' AND [method]=N'DELETE' AND [title]<>N'取消云端录像下载';
UPDATE [sys_api] SET [title]=N'查询云端录像下载' WHERE [path]=N'/api/gb28181/cloud-recordings/downloads/:taskId' AND [method]=N'GET' AND [title]<>N'查询云端录像下载';
UPDATE [sys_api] SET [title]=N'删除单个云端录像' WHERE [path]=N'/api/gb28181/cloud-recordings/files/:id' AND [method]=N'DELETE' AND [title]<>N'删除单个云端录像';
UPDATE [sys_api] SET [title]=N'创建云端录像下载' WHERE [path]=N'/api/gb28181/cloud-recordings/files/:id/downloads' AND [method]=N'POST' AND [title]<>N'创建云端录像下载';
UPDATE [sys_api] SET [title]=N'批量删除云端录像' WHERE [path]=N'/api/gb28181/cloud-recordings/files/batch-delete' AND [method]=N'POST' AND [title]<>N'批量删除云端录像';
UPDATE [sys_api] SET [title]=N'查询录像对账状态' WHERE [path]=N'/api/gb28181/cloud-recordings/reconciliations' AND [method]=N'GET' AND [title]<>N'查询录像对账状态';
UPDATE [sys_api] SET [title]=N'触发录像对账' WHERE [path]=N'/api/gb28181/cloud-recordings/reconciliations' AND [method]=N'POST' AND [title]<>N'触发录像对账';
UPDATE [sys_api] SET [title]=N'查询目录树' WHERE [path]=N'/api/gb28181/device-mgmt/catalog/tree' AND [method]=N'GET' AND [title]<>N'查询目录树';
UPDATE [sys_api] SET [title]=N'读取目录节点详情' WHERE [path]=N'/api/gb28181/device-mgmt/catalog/tree/:id' AND [method]=N'GET' AND [title]<>N'读取目录节点详情';
UPDATE [sys_api] SET [title]=N'读取目录子节点' WHERE [path]=N'/api/gb28181/device-mgmt/catalog/tree/:id/children' AND [method]=N'GET' AND [title]<>N'读取目录子节点';
UPDATE [sys_api] SET [title]=N'删除单个通道' WHERE [path]=N'/api/gb28181/device-mgmt/channel/:id' AND [method]=N'DELETE' AND [title]<>N'删除单个通道';
UPDATE [sys_api] SET [title]=N'读取通道详情' WHERE [path]=N'/api/gb28181/device-mgmt/channel/:id' AND [method]=N'GET' AND [title]<>N'读取通道详情';
UPDATE [sys_api] SET [title]=N'读取设备控制能力' WHERE [path]=N'/api/gb28181/device-mgmt/channel/:id/control-capabilities' AND [method]=N'GET' AND [title]<>N'读取设备控制能力';
UPDATE [sys_api] SET [title]=N'读取通道运行状态' WHERE [path]=N'/api/gb28181/device-mgmt/channel/:id/device-status' AND [method]=N'GET' AND [title]<>N'读取通道运行状态';
UPDATE [sys_api] SET [title]=N'读取通道挂载点' WHERE [path]=N'/api/gb28181/device-mgmt/channel/:id/mounts' AND [method]=N'GET' AND [title]<>N'读取通道挂载点';
UPDATE [sys_api] SET [title]=N'创建回放会话' WHERE [path]=N'/api/gb28181/device-mgmt/channel/:id/playback-sessions' AND [method]=N'POST' AND [title]<>N'创建回放会话';
UPDATE [sys_api] SET [title]=N'停止回放会话' WHERE [path]=N'/api/gb28181/device-mgmt/channel/:id/playback-sessions/:sessionId' AND [method]=N'DELETE' AND [title]<>N'停止回放会话';
UPDATE [sys_api] SET [title]=N'读取回放会话' WHERE [path]=N'/api/gb28181/device-mgmt/channel/:id/playback-sessions/:sessionId' AND [method]=N'GET' AND [title]<>N'读取回放会话';
UPDATE [sys_api] SET [title]=N'控制回放（暂停/续播/倍速）' WHERE [path]=N'/api/gb28181/device-mgmt/channel/:id/playback-sessions/:sessionId/actions' AND [method]=N'POST' AND [title]<>N'控制回放（暂停/续播/倍速）';
UPDATE [sys_api] SET [title]=N'云台基础控制' WHERE [path]=N'/api/gb28181/device-mgmt/channel/:id/ptz' AND [method]=N'POST' AND [title]<>N'云台基础控制';
UPDATE [sys_api] SET [title]=N'下发巡航指令' WHERE [path]=N'/api/gb28181/device-mgmt/channel/:id/ptz/cruise' AND [method]=N'POST' AND [title]<>N'下发巡航指令';
UPDATE [sys_api] SET [title]=N'查询巡航轨迹列表' WHERE [path]=N'/api/gb28181/device-mgmt/channel/:id/ptz/cruise-tracks' AND [method]=N'GET' AND [title]<>N'查询巡航轨迹列表';
UPDATE [sys_api] SET [title]=N'读取巡航轨迹详情' WHERE [path]=N'/api/gb28181/device-mgmt/channel/:id/ptz/cruise-tracks/:trackId' AND [method]=N'GET' AND [title]<>N'读取巡航轨迹详情';
UPDATE [sys_api] SET [title]=N'保存巡航轨迹' WHERE [path]=N'/api/gb28181/device-mgmt/channel/:id/ptz/cruise/tracks' AND [method]=N'POST' AND [title]<>N'保存巡航轨迹';
UPDATE [sys_api] SET [title]=N'云台扩展控制' WHERE [path]=N'/api/gb28181/device-mgmt/channel/:id/ptz/extended' AND [method]=N'POST' AND [title]<>N'云台扩展控制';
UPDATE [sys_api] SET [title]=N'查询看守位' WHERE [path]=N'/api/gb28181/device-mgmt/channel/:id/ptz/home-position' AND [method]=N'GET' AND [title]<>N'查询看守位';
UPDATE [sys_api] SET [title]=N'查询云台操作结果' WHERE [path]=N'/api/gb28181/device-mgmt/channel/:id/ptz/operations/:operationId' AND [method]=N'GET' AND [title]<>N'查询云台操作结果';
UPDATE [sys_api] SET [title]=N'云台精准控制' WHERE [path]=N'/api/gb28181/device-mgmt/channel/:id/ptz/precise' AND [method]=N'POST' AND [title]<>N'云台精准控制';
UPDATE [sys_api] SET [title]=N'查询精准控制状态' WHERE [path]=N'/api/gb28181/device-mgmt/channel/:id/ptz/precise-status' AND [method]=N'GET' AND [title]<>N'查询精准控制状态';
UPDATE [sys_api] SET [title]=N'查询预置位列表' WHERE [path]=N'/api/gb28181/device-mgmt/channel/:id/ptz/presets' AND [method]=N'GET' AND [title]<>N'查询预置位列表';
UPDATE [sys_api] SET [title]=N'查询设备录像' WHERE [path]=N'/api/gb28181/device-mgmt/channel/:id/record-query' AND [method]=N'POST' AND [title]<>N'查询设备录像';
UPDATE [sys_api] SET [title]=N'查询录像查询条件' WHERE [path]=N'/api/gb28181/device-mgmt/channel/:id/record-query/options' AND [method]=N'GET' AND [title]<>N'查询录像查询条件';
UPDATE [sys_api] SET [title]=N'创建抓拍会话' WHERE [path]=N'/api/gb28181/device-mgmt/channel/:id/snapshot-sessions' AND [method]=N'POST' AND [title]<>N'创建抓拍会话';
UPDATE [sys_api] SET [title]=N'读取抓拍会话' WHERE [path]=N'/api/gb28181/device-mgmt/channel/:id/snapshot-sessions/:sessionId' AND [method]=N'GET' AND [title]<>N'读取抓拍会话';
UPDATE [sys_api] SET [title]=N'创建对讲会话' WHERE [path]=N'/api/gb28181/device-mgmt/channel/:id/talk-sessions' AND [method]=N'POST' AND [title]<>N'创建对讲会话';
UPDATE [sys_api] SET [title]=N'停止对讲会话' WHERE [path]=N'/api/gb28181/device-mgmt/channel/:id/talk-sessions/:sessionId' AND [method]=N'DELETE' AND [title]<>N'停止对讲会话';
UPDATE [sys_api] SET [title]=N'读取对讲会话' WHERE [path]=N'/api/gb28181/device-mgmt/channel/:id/talk-sessions/:sessionId' AND [method]=N'GET' AND [title]<>N'读取对讲会话';
UPDATE [sys_api] SET [title]=N'查询通道时间轴' WHERE [path]=N'/api/gb28181/device-mgmt/channel/:id/timeline' AND [method]=N'GET' AND [title]<>N'查询通道时间轴';
UPDATE [sys_api] SET [title]=N'批量删除通道' WHERE [path]=N'/api/gb28181/device-mgmt/channel/batch-delete' AND [method]=N'POST' AND [title]<>N'批量删除通道';
UPDATE [sys_api] SET [title]=N'查询通道列表' WHERE [path]=N'/api/gb28181/device-mgmt/channels' AND [method]=N'GET' AND [title]<>N'查询通道列表';
UPDATE [sys_api] SET [title]=N'创建自定义分组' WHERE [path]=N'/api/gb28181/device-mgmt/custom-groups' AND [method]=N'POST' AND [title]<>N'创建自定义分组';
UPDATE [sys_api] SET [title]=N'删除自定义分组' WHERE [path]=N'/api/gb28181/device-mgmt/custom-groups/:id' AND [method]=N'DELETE' AND [title]<>N'删除自定义分组';
UPDATE [sys_api] SET [title]=N'修改自定义分组' WHERE [path]=N'/api/gb28181/device-mgmt/custom-groups/:id' AND [method]=N'PATCH' AND [title]<>N'修改自定义分组';
UPDATE [sys_api] SET [title]=N'添加分组设备' WHERE [path]=N'/api/gb28181/device-mgmt/custom-groups/:id/devices' AND [method]=N'POST' AND [title]<>N'添加分组设备';
UPDATE [sys_api] SET [title]=N'移除分组设备' WHERE [path]=N'/api/gb28181/device-mgmt/custom-groups/:id/devices/remove' AND [method]=N'POST' AND [title]<>N'移除分组设备';
UPDATE [sys_api] SET [title]=N'移动自定义分组' WHERE [path]=N'/api/gb28181/device-mgmt/custom-groups/:id/move' AND [method]=N'POST' AND [title]<>N'移动自定义分组';
UPDATE [sys_api] SET [title]=N'删除单个设备' WHERE [path]=N'/api/gb28181/device-mgmt/device/:id' AND [method]=N'DELETE' AND [title]<>N'删除单个设备';
UPDATE [sys_api] SET [title]=N'读取设备详情' WHERE [path]=N'/api/gb28181/device-mgmt/device/:id' AND [method]=N'GET' AND [title]<>N'读取设备详情';
UPDATE [sys_api] SET [title]=N'查看设备升级' WHERE [path]=N'/api/gb28181/device-mgmt/device/:id/firmware-upgrades' AND [method]=N'GET' AND [title]<>N'查看设备升级';
UPDATE [sys_api] SET [title]=N'查询设备维护操作' WHERE [path]=N'/api/gb28181/device-mgmt/device/:id/maintenance-operations' AND [method]=N'GET' AND [title]<>N'查询设备维护操作';
UPDATE [sys_api] SET [title]=N'查询设备状态事件' WHERE [path]=N'/api/gb28181/device-mgmt/device/:id/status-events' AND [method]=N'GET' AND [title]<>N'查询设备状态事件';
UPDATE [sys_api] SET [title]=N'查询设备订阅' WHERE [path]=N'/api/gb28181/device-mgmt/device/:id/subscriptions' AND [method]=N'GET' AND [title]<>N'查询设备订阅';
UPDATE [sys_api] SET [title]=N'更新设备订阅' WHERE [path]=N'/api/gb28181/device-mgmt/device/:id/subscriptions/:kind' AND [method]=N'PATCH' AND [title]<>N'更新设备订阅';
UPDATE [sys_api] SET [title]=N'续订设备订阅' WHERE [path]=N'/api/gb28181/device-mgmt/device/:id/subscriptions/:kind/renew' AND [method]=N'POST' AND [title]<>N'续订设备订阅';
UPDATE [sys_api] SET [title]=N'批量删除设备' WHERE [path]=N'/api/gb28181/device-mgmt/device/batch-delete' AND [method]=N'POST' AND [title]<>N'批量删除设备';
UPDATE [sys_api] SET [title]=N'查询设备列表' WHERE [path]=N'/api/gb28181/device-mgmt/devices' AND [method]=N'GET' AND [title]<>N'查询设备列表';
UPDATE [sys_api] SET [title]=N'查询组织目录树' WHERE [path]=N'/api/gb28181/device-mgmt/directory/tree' AND [method]=N'GET' AND [title]<>N'查询组织目录树';
UPDATE [sys_api] SET [title]=N'查询地图聚合点' WHERE [path]=N'/api/gb28181/device-mgmt/map/clusters' AND [method]=N'GET' AND [title]<>N'查询地图聚合点';
UPDATE [sys_api] SET [title]=N'查询地图标记点' WHERE [path]=N'/api/gb28181/device-mgmt/map/markers' AND [method]=N'GET' AND [title]<>N'查询地图标记点';
UPDATE [sys_api] SET [title]=N'调整设备归属' WHERE [path]=N'/api/gb28181/device-mgmt/permission-workbench/assignments' AND [method]=N'POST' AND [title]<>N'调整设备归属';
UPDATE [sys_api] SET [title]=N'整部门调整设备归属' WHERE [path]=N'/api/gb28181/device-mgmt/permission-workbench/assignments/departments' AND [method]=N'POST' AND [title]<>N'整部门调整设备归属';
UPDATE [sys_api] SET [title]=N'解析工作台设备' WHERE [path]=N'/api/gb28181/device-mgmt/permission-workbench/devices/resolve' AND [method]=N'POST' AND [title]<>N'解析工作台设备';
UPDATE [sys_api] SET [title]=N'查询共享目标' WHERE [path]=N'/api/gb28181/device-mgmt/permission-workbench/grant-targets' AND [method]=N'GET' AND [title]<>N'查询共享目标';
UPDATE [sys_api] SET [title]=N'应用设备共享授权' WHERE [path]=N'/api/gb28181/device-mgmt/permission-workbench/grants/apply' AND [method]=N'POST' AND [title]<>N'应用设备共享授权';
UPDATE [sys_api] SET [title]=N'查询设备共享授权' WHERE [path]=N'/api/gb28181/device-mgmt/permission-workbench/grants/query' AND [method]=N'POST' AND [title]<>N'查询设备共享授权';
UPDATE [sys_api] SET [title]=N'查询统计覆盖率' WHERE [path]=N'/api/gb28181/device-traffic/coverage' AND [method]=N'GET' AND [title]<>N'查询统计覆盖率';
UPDATE [sys_api] SET [title]=N'查询实时流量' WHERE [path]=N'/api/gb28181/device-traffic/realtime' AND [method]=N'GET' AND [title]<>N'查询实时流量';
UPDATE [sys_api] SET [title]=N'查询流量会话' WHERE [path]=N'/api/gb28181/device-traffic/sessions' AND [method]=N'GET' AND [title]<>N'查询流量会话';
UPDATE [sys_api] SET [title]=N'查询流量汇总' WHERE [path]=N'/api/gb28181/device-traffic/summary' AND [method]=N'GET' AND [title]<>N'查询流量汇总';
UPDATE [sys_api] SET [title]=N'查询流量趋势' WHERE [path]=N'/api/gb28181/device-traffic/trend' AND [method]=N'GET' AND [title]<>N'查询流量趋势';
UPDATE [sys_api] SET [title]=N'查询当前观看' WHERE [path]=N'/api/gb28181/device-traffic/viewers' AND [method]=N'GET' AND [title]<>N'查询当前观看';
UPDATE [sys_api] SET [title]=N'下钻播放指标' WHERE [path]=N'/api/gb28181/home/drilldown/play' AND [method]=N'GET' AND [title]<>N'下钻播放指标';
UPDATE [sys_api] SET [title]=N'下钻 SIP 指标' WHERE [path]=N'/api/gb28181/home/drilldown/sip' AND [method]=N'GET' AND [title]<>N'下钻 SIP 指标';
UPDATE [sys_api] SET [title]=N'下钻流量指标' WHERE [path]=N'/api/gb28181/home/drilldown/traffic' AND [method]=N'GET' AND [title]<>N'下钻流量指标';
UPDATE [sys_api] SET [title]=N'读取仪表盘布局' WHERE [path]=N'/api/gb28181/home/layout' AND [method]=N'GET' AND [title]<>N'读取仪表盘布局';
UPDATE [sys_api] SET [title]=N'读取首页汇总' WHERE [path]=N'/api/gb28181/home/summary' AND [method]=N'GET' AND [title]<>N'读取首页汇总';
UPDATE [sys_api] SET [title]=N'发起实时点播' WHERE [path]=N'/api/gb28181/play/:deviceId/:channelId' AND [method]=N'POST' AND [title]<>N'发起实时点播';
UPDATE [sys_api] SET [title]=N'申请固定播放地址授权' WHERE [path]=N'/api/gb28181/play/:deviceId/:channelId/authorization' AND [method]=N'POST' AND [title]<>N'申请固定播放地址授权';
UPDATE [sys_api] SET [title]=N'查询播放方案' WHERE [path]=N'/api/gb28181/playback-schemes' AND [method]=N'GET' AND [title]<>N'查询播放方案';
UPDATE [sys_api] SET [title]=N'创建播放方案' WHERE [path]=N'/api/gb28181/playback-schemes' AND [method]=N'POST' AND [title]<>N'创建播放方案';
UPDATE [sys_api] SET [title]=N'删除播放方案' WHERE [path]=N'/api/gb28181/playback-schemes/:id' AND [method]=N'DELETE' AND [title]<>N'删除播放方案';
UPDATE [sys_api] SET [title]=N'查看播放方案' WHERE [path]=N'/api/gb28181/playback-schemes/:id' AND [method]=N'GET' AND [title]<>N'查看播放方案';
UPDATE [sys_api] SET [title]=N'重命名播放方案' WHERE [path]=N'/api/gb28181/playback-schemes/:id' AND [method]=N'PATCH' AND [title]<>N'重命名播放方案';
UPDATE [sys_api] SET [title]=N'覆盖播放方案' WHERE [path]=N'/api/gb28181/playback-schemes/:id/layout' AND [method]=N'PUT' AND [title]<>N'覆盖播放方案';
UPDATE [sys_api] SET [title]=N'新建录像计划' WHERE [path]=N'/api/gb28181/recording-plans' AND [method]=N'POST' AND [title]<>N'新建录像计划';
UPDATE [sys_api] SET [title]=N'删除录像计划' WHERE [path]=N'/api/gb28181/recording-plans/:id' AND [method]=N'DELETE' AND [title]<>N'删除录像计划';
UPDATE [sys_api] SET [title]=N'查看录像计划' WHERE [path]=N'/api/gb28181/recording-plans/:id' AND [method]=N'GET' AND [title]<>N'查看录像计划';
UPDATE [sys_api] SET [title]=N'编辑录像计划' WHERE [path]=N'/api/gb28181/recording-plans/:id' AND [method]=N'PUT' AND [title]<>N'编辑录像计划';
UPDATE [sys_api] SET [title]=N'搜索分配通道' WHERE [path]=N'/api/gb28181/recording-plans/:id/assignment-options/channels' AND [method]=N'GET' AND [title]<>N'搜索分配通道';
UPDATE [sys_api] SET [title]=N'搜索分配设备' WHERE [path]=N'/api/gb28181/recording-plans/:id/assignment-options/devices' AND [method]=N'GET' AND [title]<>N'搜索分配设备';
UPDATE [sys_api] SET [title]=N'提交录像计划分配' WHERE [path]=N'/api/gb28181/recording-plans/:id/assignments' AND [method]=N'POST' AND [title]<>N'提交录像计划分配';
UPDATE [sys_api] SET [title]=N'启停录像计划' WHERE [path]=N'/api/gb28181/recording-plans/:id/status' AND [method]=N'PATCH' AND [title]<>N'启停录像计划';
UPDATE [sys_api] SET [title]=N'切换通道录像模式' WHERE [path]=N'/api/gb28181/recording-plans/channels/:channelId/recording-mode' AND [method]=N'PATCH' AND [title]<>N'切换通道录像模式';
UPDATE [sys_api] SET [title]=N'SIP Trace 报文详情' WHERE [path]=N'/api/gb28181/sip-traces/messages/:id' AND [method]=N'GET' AND [title]<>N'SIP Trace 报文详情';
UPDATE [sys_api] SET [title]=N'SIP Trace 会话报文' WHERE [path]=N'/api/gb28181/sip-traces/sessions/:callId/messages' AND [method]=N'GET' AND [title]<>N'SIP Trace 会话报文';
UPDATE [sys_api] SET [title]=N'读取 SIP 仪表盘快照' WHERE [path]=N'/api/gb28181/sip/dashboard/snapshot' AND [method]=N'GET' AND [title]<>N'读取 SIP 仪表盘快照';
UPDATE [sys_api] SET [title]=N'读取 SIP 平台信息' WHERE [path]=N'/api/gb28181/sip/platform' AND [method]=N'GET' AND [title]<>N'读取 SIP 平台信息';
UPDATE [sys_api] SET [title]=N'生成设备接入二维码' WHERE [path]=N'/api/gb28181/sip/qr/token' AND [method]=N'POST' AND [title]<>N'生成设备接入二维码';
UPDATE [sys_api] SET [title]=N'读取全局通道音频配置' WHERE [path]=N'/api/gb28181/sip/service-config/default-channel-audio' AND [method]=N'GET' AND [title]<>N'读取全局通道音频配置';
UPDATE [sys_api] SET [title]=N'修改全局通道音频配置' WHERE [path]=N'/api/gb28181/sip/service-config/default-channel-audio' AND [method]=N'PUT' AND [title]<>N'修改全局通道音频配置';
UPDATE [sys_api] SET [title]=N'设置默认码流传输方式' WHERE [path]=N'/api/gb28181/sip/service-config/default-channel-stream-transport' AND [method]=N'PUT' AND [title]<>N'设置默认码流传输方式';
UPDATE [sys_api] SET [title]=N'读取默认播放协议' WHERE [path]=N'/api/gb28181/sip/service-config/default-playback-protocol' AND [method]=N'GET' AND [title]<>N'读取默认播放协议';
UPDATE [sys_api] SET [title]=N'修改默认播放协议' WHERE [path]=N'/api/gb28181/sip/service-config/default-playback-protocol' AND [method]=N'PUT' AND [title]<>N'修改默认播放协议';
UPDATE [sys_api] SET [title]=N'读取固定地址播放配置' WHERE [path]=N'/api/gb28181/sip/service-config/fixed-address-playback' AND [method]=N'GET' AND [title]<>N'读取固定地址播放配置';
UPDATE [sys_api] SET [title]=N'修改固定地址播放配置' WHERE [path]=N'/api/gb28181/sip/service-config/fixed-address-playback' AND [method]=N'PUT' AND [title]<>N'修改固定地址播放配置';
UPDATE [sys_api] SET [title]=N'读取全局订阅项目' WHERE [path]=N'/api/gb28181/sip/service-config/global-subscriptions' AND [method]=N'GET' AND [title]<>N'读取全局订阅项目';
UPDATE [sys_api] SET [title]=N'修改全局订阅项目' WHERE [path]=N'/api/gb28181/sip/service-config/global-subscriptions' AND [method]=N'PUT' AND [title]<>N'修改全局订阅项目';
UPDATE [sys_api] SET [title]=N'读取忽略通道离线异常通知配置' WHERE [path]=N'/api/gb28181/sip/service-config/ignore-channel-offline-status-notify' AND [method]=N'GET' AND [title]<>N'读取忽略通道离线异常通知配置';
UPDATE [sys_api] SET [title]=N'修改忽略通道离线异常通知配置' WHERE [path]=N'/api/gb28181/sip/service-config/ignore-channel-offline-status-notify' AND [method]=N'PUT' AND [title]<>N'修改忽略通道离线异常通知配置';
UPDATE [sys_api] SET [title]=N'读取收到心跳恢复设备上线配置' WHERE [path]=N'/api/gb28181/sip/service-config/online-on-heartbeat' AND [method]=N'GET' AND [title]<>N'读取收到心跳恢复设备上线配置';
UPDATE [sys_api] SET [title]=N'修改收到心跳恢复设备上线配置' WHERE [path]=N'/api/gb28181/sip/service-config/online-on-heartbeat' AND [method]=N'PUT' AND [title]<>N'修改收到心跳恢复设备上线配置';
UPDATE [sys_api] SET [title]=N'读取播放鉴权配置' WHERE [path]=N'/api/gb28181/sip/service-config/play-auth' AND [method]=N'GET' AND [title]<>N'读取播放鉴权配置';
UPDATE [sys_api] SET [title]=N'修改播放鉴权配置' WHERE [path]=N'/api/gb28181/sip/service-config/play-auth' AND [method]=N'PUT' AND [title]<>N'修改播放鉴权配置';
UPDATE [sys_api] SET [title]=N'读取回放参数' WHERE [path]=N'/api/gb28181/sip/service-config/playback-settings' AND [method]=N'GET' AND [title]<>N'读取回放参数';
UPDATE [sys_api] SET [title]=N'修改回放参数' WHERE [path]=N'/api/gb28181/sip/service-config/playback-settings' AND [method]=N'PUT' AND [title]<>N'修改回放参数';
UPDATE [sys_api] SET [title]=N'修改移动位置历史轨迹配置' WHERE [path]=N'/api/gb28181/sip/service-config/position-history' AND [method]=N'PUT' AND [title]<>N'修改移动位置历史轨迹配置';
UPDATE [sys_api] SET [title]=N'读取预分配模式' WHERE [path]=N'/api/gb28181/sip/service-config/preallocation-mode' AND [method]=N'GET' AND [title]<>N'读取预分配模式';
UPDATE [sys_api] SET [title]=N'修改预分配模式' WHERE [path]=N'/api/gb28181/sip/service-config/preallocation-mode' AND [method]=N'PUT' AND [title]<>N'修改预分配模式';
UPDATE [sys_api] SET [title]=N'读取云台默认速度配置' WHERE [path]=N'/api/gb28181/sip/service-config/ptz-default-speed' AND [method]=N'GET' AND [title]<>N'读取云台默认速度配置';
UPDATE [sys_api] SET [title]=N'修改云台默认速度配置' WHERE [path]=N'/api/gb28181/sip/service-config/ptz-default-speed' AND [method]=N'PUT' AND [title]<>N'修改云台默认速度配置';
UPDATE [sys_api] SET [title]=N'读取报警消息存储配置' WHERE [path]=N'/api/gb28181/sip/service-config/save-alarm-messages' AND [method]=N'GET' AND [title]<>N'读取报警消息存储配置';
UPDATE [sys_api] SET [title]=N'修改报警消息存储配置' WHERE [path]=N'/api/gb28181/sip/service-config/save-alarm-messages' AND [method]=N'PUT' AND [title]<>N'修改报警消息存储配置';
UPDATE [sys_api] SET [title]=N'设置 SDP 扩展参数' WHERE [path]=N'/api/gb28181/sip/service-config/sdp-extension' AND [method]=N'PUT' AND [title]<>N'设置 SDP 扩展参数';
UPDATE [sys_api] SET [title]=N'读取 SIP 命令超时时间' WHERE [path]=N'/api/gb28181/sip/service-config/sip-command-timeout' AND [method]=N'GET' AND [title]<>N'读取 SIP 命令超时时间';
UPDATE [sys_api] SET [title]=N'修改 SIP 命令超时时间' WHERE [path]=N'/api/gb28181/sip/service-config/sip-command-timeout' AND [method]=N'PUT' AND [title]<>N'修改 SIP 命令超时时间';
UPDATE [sys_api] SET [title]=N'读取 SIP 日志配置' WHERE [path]=N'/api/gb28181/sip/service-config/sip-log' AND [method]=N'GET' AND [title]<>N'读取 SIP 日志配置';
UPDATE [sys_api] SET [title]=N'修改 SIP 日志配置' WHERE [path]=N'/api/gb28181/sip/service-config/sip-log' AND [method]=N'PUT' AND [title]<>N'修改 SIP 日志配置';
UPDATE [sys_api] SET [title]=N'读取设备上线同步通道配置' WHERE [path]=N'/api/gb28181/sip/service-config/sync-channels-on-online' AND [method]=N'GET' AND [title]<>N'读取设备上线同步通道配置';
UPDATE [sys_api] SET [title]=N'修改设备上线同步通道配置' WHERE [path]=N'/api/gb28181/sip/service-config/sync-channels-on-online' AND [method]=N'PUT' AND [title]<>N'修改设备上线同步通道配置';
UPDATE [sys_api] SET [title]=N'保存 SIP 配置' WHERE [path]=N'/api/gb28181/sip/setup/config' AND [method]=N'PUT' AND [title]<>N'保存 SIP 配置';
UPDATE [sys_api] SET [title]=N'读取本机网络接口' WHERE [path]=N'/api/gb28181/sip/setup/network-interfaces' AND [method]=N'GET' AND [title]<>N'读取本机网络接口';
UPDATE [sys_api] SET [title]=N'暂缓 SIP 配置' WHERE [path]=N'/api/gb28181/sip/setup/skip' AND [method]=N'POST' AND [title]<>N'暂缓 SIP 配置';
UPDATE [sys_api] SET [title]=N'读取 SIP 配置状态' WHERE [path]=N'/api/gb28181/sip/setup/status' AND [method]=N'GET' AND [title]<>N'读取 SIP 配置状态';
UPDATE [sys_api] SET [title]=N'发起视频探针检测' WHERE [path]=N'/api/gb28181/stream-probes/:streamId' AND [method]=N'POST' AND [title]<>N'发起视频探针检测';
UPDATE [sys_api] SET [title]=N'查询探针检测结果' WHERE [path]=N'/api/gb28181/stream-probes/operations/:operationId' AND [method]=N'GET' AND [title]<>N'查询探针检测结果';
UPDATE [sys_api] SET [title]=N'查看媒体节点列表' WHERE [path]=N'/api/gb28181/zlm/nodes' AND [method]=N'GET' AND [title]<>N'查看媒体节点列表';
UPDATE [sys_api] SET [title]=N'新增媒体节点' WHERE [path]=N'/api/gb28181/zlm/nodes' AND [method]=N'POST' AND [title]<>N'新增媒体节点';
UPDATE [sys_api] SET [title]=N'删除媒体节点' WHERE [path]=N'/api/gb28181/zlm/nodes/:id' AND [method]=N'DELETE' AND [title]<>N'删除媒体节点';
UPDATE [sys_api] SET [title]=N'查看媒体节点详情' WHERE [path]=N'/api/gb28181/zlm/nodes/:id' AND [method]=N'GET' AND [title]<>N'查看媒体节点详情';
UPDATE [sys_api] SET [title]=N'更新媒体节点' WHERE [path]=N'/api/gb28181/zlm/nodes/:id' AND [method]=N'PUT' AND [title]<>N'更新媒体节点';
UPDATE [sys_api] SET [title]=N'激活媒体节点' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/activate' AND [method]=N'POST' AND [title]<>N'激活媒体节点';
UPDATE [sys_api] SET [title]=N'查看媒体服务配置' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/config' AND [method]=N'GET' AND [title]<>N'查看媒体服务配置';
UPDATE [sys_api] SET [title]=N'更新媒体服务配置' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/config' AND [method]=N'PUT' AND [title]<>N'更新媒体服务配置';
UPDATE [sys_api] SET [title]=N'测试媒体节点连接' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/config/test-connection' AND [method]=N'POST' AND [title]<>N'测试媒体节点连接';
UPDATE [sys_api] SET [title]=N'停用媒体节点' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/disable' AND [method]=N'POST' AND [title]<>N'停用媒体节点';
UPDATE [sys_api] SET [title]=N'启用媒体节点' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/enable' AND [method]=N'POST' AND [title]<>N'启用媒体节点';
UPDATE [sys_api] SET [title]=N'查看 FFmpeg 源列表' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/ffmpeg-sources' AND [method]=N'GET' AND [title]<>N'查看 FFmpeg 源列表';
UPDATE [sys_api] SET [title]=N'新增 FFmpeg 源' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/ffmpeg-sources' AND [method]=N'POST' AND [title]<>N'新增 FFmpeg 源';
UPDATE [sys_api] SET [title]=N'删除 FFmpeg 源' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/ffmpeg-sources/:key' AND [method]=N'DELETE' AND [title]<>N'删除 FFmpeg 源';
UPDATE [sys_api] SET [title]=N'FFmpeg 源预检' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/ffmpeg-sources/:key/preflight' AND [method]=N'POST' AND [title]<>N'FFmpeg 源预检';
UPDATE [sys_api] SET [title]=N'踢除节点上的全部会话' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/kick' AND [method]=N'POST' AND [title]<>N'踢除节点上的全部会话';
UPDATE [sys_api] SET [title]=N'媒体节点维护' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/maintenance' AND [method]=N'POST' AND [title]<>N'媒体节点维护';
UPDATE [sys_api] SET [title]=N'查看拉流代理列表' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/proxies/pull' AND [method]=N'GET' AND [title]<>N'查看拉流代理列表';
UPDATE [sys_api] SET [title]=N'新增拉流代理' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/proxies/pull' AND [method]=N'POST' AND [title]<>N'新增拉流代理';
UPDATE [sys_api] SET [title]=N'删除拉流代理' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/proxies/pull/:key' AND [method]=N'DELETE' AND [title]<>N'删除拉流代理';
UPDATE [sys_api] SET [title]=N'查看拉流代理详情' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/proxies/pull/:key' AND [method]=N'GET' AND [title]<>N'查看拉流代理详情';
UPDATE [sys_api] SET [title]=N'拉流代理预检' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/proxies/pull/:key/preflight' AND [method]=N'POST' AND [title]<>N'拉流代理预检';
UPDATE [sys_api] SET [title]=N'查看推流代理列表' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/proxies/push' AND [method]=N'GET' AND [title]<>N'查看推流代理列表';
UPDATE [sys_api] SET [title]=N'新增推流代理' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/proxies/push' AND [method]=N'POST' AND [title]<>N'新增推流代理';
UPDATE [sys_api] SET [title]=N'删除推流代理' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/proxies/push/:key' AND [method]=N'DELETE' AND [title]<>N'删除推流代理';
UPDATE [sys_api] SET [title]=N'查看推流代理详情' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/proxies/push/:key' AND [method]=N'GET' AND [title]<>N'查看推流代理详情';
UPDATE [sys_api] SET [title]=N'推流代理预检' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/proxies/push/:key/preflight' AND [method]=N'POST' AND [title]<>N'推流代理预检';
UPDATE [sys_api] SET [title]=N'强制停止录制' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/recordings/runtime/force-stop' AND [method]=N'POST' AND [title]<>N'强制停止录制';
UPDATE [sys_api] SET [title]=N'强制停止录制预检' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/recordings/runtime/force-stop/preflight' AND [method]=N'POST' AND [title]<>N'强制停止录制预检';
UPDATE [sys_api] SET [title]=N'开始录制' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/recordings/runtime/start' AND [method]=N'POST' AND [title]<>N'开始录制';
UPDATE [sys_api] SET [title]=N'开始录制预检' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/recordings/runtime/start/preflight' AND [method]=N'POST' AND [title]<>N'开始录制预检';
UPDATE [sys_api] SET [title]=N'查询录制运行状态' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/recordings/runtime/status' AND [method]=N'GET' AND [title]<>N'查询录制运行状态';
UPDATE [sys_api] SET [title]=N'停止录制' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/recordings/runtime/stop' AND [method]=N'POST' AND [title]<>N'停止录制';
UPDATE [sys_api] SET [title]=N'停止录制预检' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/recordings/runtime/stop/preflight' AND [method]=N'POST' AND [title]<>N'停止录制预检';
UPDATE [sys_api] SET [title]=N'查询媒体服务重启状态' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/restart' AND [method]=N'GET' AND [title]<>N'查询媒体服务重启状态';
UPDATE [sys_api] SET [title]=N'重启媒体服务' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/restart' AND [method]=N'POST' AND [title]<>N'重启媒体服务';
UPDATE [sys_api] SET [title]=N'查看 RTP 服务列表' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/rtp-servers' AND [method]=N'GET' AND [title]<>N'查看 RTP 服务列表';
UPDATE [sys_api] SET [title]=N'新增 RTP 服务' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/rtp-servers' AND [method]=N'POST' AND [title]<>N'新增 RTP 服务';
UPDATE [sys_api] SET [title]=N'关闭 RTP 服务' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/rtp-servers/close' AND [method]=N'POST' AND [title]<>N'关闭 RTP 服务';
UPDATE [sys_api] SET [title]=N'关闭 RTP 服务预检' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/rtp-servers/close/preflight' AND [method]=N'POST' AND [title]<>N'关闭 RTP 服务预检';
UPDATE [sys_api] SET [title]=N'强制关闭 RTP 服务' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/rtp-servers/force-close' AND [method]=N'POST' AND [title]<>N'强制关闭 RTP 服务';
UPDATE [sys_api] SET [title]=N'查询媒体节点运行状态' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/runtime' AND [method]=N'GET' AND [title]<>N'查询媒体节点运行状态';
UPDATE [sys_api] SET [title]=N'踢除指定播放会话' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/sessions/kick' AND [method]=N'POST' AND [title]<>N'踢除指定播放会话';
UPDATE [sys_api] SET [title]=N'查询会话网络信息' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/sessions/network' AND [method]=N'GET' AND [title]<>N'查询会话网络信息';
UPDATE [sys_api] SET [title]=N'查看节点会话观看者' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/sessions/viewers' AND [method]=N'GET' AND [title]<>N'查看节点会话观看者';
UPDATE [sys_api] SET [title]=N'查看媒体节点流列表' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/streams' AND [method]=N'GET' AND [title]<>N'查看媒体节点流列表';
UPDATE [sys_api] SET [title]=N'关闭媒体流' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/streams/close' AND [method]=N'POST' AND [title]<>N'关闭媒体流';
UPDATE [sys_api] SET [title]=N'批量关闭媒体流' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/streams/close/batch' AND [method]=N'POST' AND [title]<>N'批量关闭媒体流';
UPDATE [sys_api] SET [title]=N'批量关闭媒体流预检' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/streams/close/batch/preflight' AND [method]=N'POST' AND [title]<>N'批量关闭媒体流预检';
UPDATE [sys_api] SET [title]=N'关闭媒体流预检' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/streams/close/preflight' AND [method]=N'POST' AND [title]<>N'关闭媒体流预检';
UPDATE [sys_api] SET [title]=N'查看媒体流详情' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/streams/detail' AND [method]=N'GET' AND [title]<>N'查看媒体流详情';
UPDATE [sys_api] SET [title]=N'强制关闭媒体流' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/streams/force-close' AND [method]=N'POST' AND [title]<>N'强制关闭媒体流';
UPDATE [sys_api] SET [title]=N'发放播放授权' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/streams/playback-grant' AND [method]=N'POST' AND [title]<>N'发放播放授权';
UPDATE [sys_api] SET [title]=N'截取媒体流快照' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/streams/snapshot' AND [method]=N'GET' AND [title]<>N'截取媒体流快照';
UPDATE [sys_api] SET [title]=N'查询媒体流观看者' WHERE [path]=N'/api/gb28181/zlm/nodes/:id/streams/viewers' AND [method]=N'GET' AND [title]<>N'查询媒体流观看者';
UPDATE [sys_api] SET [title]=N'探测媒体节点' WHERE [path]=N'/api/gb28181/zlm/nodes/probe' AND [method]=N'POST' AND [title]<>N'探测媒体节点';
UPDATE [sys_api] SET [title]=N'查看媒体服务总览' WHERE [path]=N'/api/gb28181/zlm/overview' AND [method]=N'GET' AND [title]<>N'查看媒体服务总览';
UPDATE [sys_api] SET [title]=N'查看媒体调度策略' WHERE [path]=N'/api/gb28181/zlm/scheduler' AND [method]=N'GET' AND [title]<>N'查看媒体调度策略';
UPDATE [sys_api] SET [title]=N'更新媒体调度策略' WHERE [path]=N'/api/gb28181/zlm/scheduler' AND [method]=N'PUT' AND [title]<>N'更新媒体调度策略';
UPDATE [sys_api] SET [title]=N'查询媒体调度日志' WHERE [path]=N'/api/gb28181/zlm/scheduler/logs' AND [method]=N'GET' AND [title]<>N'查询媒体调度日志';
UPDATE [sys_api] SET [title]=N'查看媒体流列表' WHERE [path]=N'/api/gb28181/zlm/streams' AND [method]=N'GET' AND [title]<>N'查看媒体流列表';
UPDATE [sys_api] SET [title]=N'查询单条数据' WHERE [path]=N'/api/plugins/example/:id' AND [method]=N'GET' AND [title]<>N'查询单条数据';
UPDATE [sys_api] SET [title]=N'新增插件示例' WHERE [path]=N'/api/plugins/example/add' AND [method]=N'POST' AND [title]<>N'新增插件示例';
UPDATE [sys_api] SET [title]=N'删除插件示例' WHERE [path]=N'/api/plugins/example/delete' AND [method]=N'DELETE' AND [title]<>N'删除插件示例';
UPDATE [sys_api] SET [title]=N'修改' WHERE [path]=N'/api/plugins/example/edit' AND [method]=N'PUT' AND [title]<>N'修改';
UPDATE [sys_api] SET [title]=N'分片上传取消上传' WHERE [path]=N'/api/sysAffix/chunk/cancel' AND [method]=N'DELETE' AND [title]<>N'分片上传取消上传';
UPDATE [sys_api] SET [title]=N'分片上传初始化' WHERE [path]=N'/api/sysAffix/chunk/init' AND [method]=N'POST' AND [title]<>N'分片上传初始化';
UPDATE [sys_api] SET [title]=N'分片上传合并分片' WHERE [path]=N'/api/sysAffix/chunk/merge' AND [method]=N'POST' AND [title]<>N'分片上传合并分片';
UPDATE [sys_api] SET [title]=N'分片上传上传分片' WHERE [path]=N'/api/sysAffix/chunk/upload' AND [method]=N'POST' AND [title]<>N'分片上传上传分片';
UPDATE [sys_api] SET [title]=N'下载文件' WHERE [path]=N'/api/sysAffix/download/:id' AND [method]=N'GET' AND [title]<>N'下载文件';
UPDATE [sys_api] SET [title]=N'上传文件' WHERE [path]=N'/api/sysAffix/upload' AND [method]=N'POST' AND [title]<>N'上传文件';
UPDATE [sys_api] SET [title]=N'根据ID获取API信息' WHERE [path]=N'/api/sysApi/:id' AND [method]=N'GET' AND [title]<>N'根据ID获取API信息';
UPDATE [sys_api] SET [title]=N'新增API' WHERE [path]=N'/api/sysApi/add' AND [method]=N'POST' AND [title]<>N'新增API';
UPDATE [sys_api] SET [title]=N'删除API' WHERE [path]=N'/api/sysApi/delete' AND [method]=N'DELETE' AND [title]<>N'删除API';
UPDATE [sys_api] SET [title]=N'更新API' WHERE [path]=N'/api/sysApi/edit' AND [method]=N'PUT' AND [title]<>N'更新API';
UPDATE [sys_api] SET [title]=N'API列表' WHERE [path]=N'/api/sysApi/list' AND [method]=N'GET' AND [title]<>N'API列表';
UPDATE [sys_api] SET [title]=N'获取部门列表' WHERE [path]=N'/api/sysDepartment/getDivision' AND [method]=N'GET' AND [title]<>N'获取部门列表';
UPDATE [sys_api] SET [title]=N'新增字典' WHERE [path]=N'/api/sysDict/add' AND [method]=N'POST' AND [title]<>N'新增字典';
UPDATE [sys_api] SET [title]=N'删除字典' WHERE [path]=N'/api/sysDict/delete' AND [method]=N'DELETE' AND [title]<>N'删除字典';
UPDATE [sys_api] SET [title]=N'更新字典' WHERE [path]=N'/api/sysDict/edit' AND [method]=N'PUT' AND [title]<>N'更新字典';
UPDATE [sys_api] SET [title]=N'根据字典编码获取字典项列表' WHERE [path]=N'/api/sysDictItem/getByDictCode/:dictCode' AND [method]=N'GET' AND [title]<>N'根据字典编码获取字典项列表';
UPDATE [sys_api] SET [title]=N'删除代码生成配置和字段信息' WHERE [path]=N'/api/sysGen/:id' AND [method]=N'DELETE' AND [title]<>N'删除代码生成配置和字段信息';
UPDATE [sys_api] SET [title]=N'获取代码生成配置详情' WHERE [path]=N'/api/sysGen/:id' AND [method]=N'GET' AND [title]<>N'获取代码生成配置详情';
UPDATE [sys_api] SET [title]=N' 批量创建代码生成配置' WHERE [path]=N'/api/sysGen/batchInsert' AND [method]=N'POST' AND [title]<>N' 批量创建代码生成配置';
UPDATE [sys_api] SET [title]=N'更新代码生成配置和字段信息' WHERE [path]=N'/api/sysGen/update' AND [method]=N'PUT' AND [title]<>N'更新代码生成配置和字段信息';
UPDATE [sys_api] SET [title]=N'定时任务日志删除' WHERE [path]=N'/api/sysJobResults/delete' AND [method]=N'DELETE' AND [title]<>N'定时任务日志删除';
UPDATE [sys_api] SET [title]=N'定时任务获取数据' WHERE [path]=N'/api/sysJobs/:id' AND [method]=N'GET' AND [title]<>N'定时任务获取数据';
UPDATE [sys_api] SET [title]=N'定时任务新增' WHERE [path]=N'/api/sysJobs/add' AND [method]=N'POST' AND [title]<>N'定时任务新增';
UPDATE [sys_api] SET [title]=N'定时任务删除' WHERE [path]=N'/api/sysJobs/delete' AND [method]=N'DELETE' AND [title]<>N'定时任务删除';
UPDATE [sys_api] SET [title]=N'定时任务编辑' WHERE [path]=N'/api/sysJobs/edit' AND [method]=N'PUT' AND [title]<>N'定时任务编辑';
UPDATE [sys_api] SET [title]=N'定时任务设置任务状态' WHERE [path]=N'/api/sysJobs/setStatus' AND [method]=N'PUT' AND [title]<>N'定时任务设置任务状态';
UPDATE [sys_api] SET [title]=N'新增菜单' WHERE [path]=N'/api/sysMenu/add' AND [method]=N'POST' AND [title]<>N'新增菜单';
UPDATE [sys_api] SET [title]=N'根据菜单ID获取API的ID集合' WHERE [path]=N'/api/sysMenu/apis/:id' AND [method]=N'GET' AND [title]<>N'根据菜单ID获取API的ID集合';
UPDATE [sys_api] SET [title]=N'批量删除' WHERE [path]=N'/api/sysMenu/batchDelete' AND [method]=N'DELETE' AND [title]<>N'批量删除';
UPDATE [sys_api] SET [title]=N'删除菜单' WHERE [path]=N'/api/sysMenu/delete' AND [method]=N'DELETE' AND [title]<>N'删除菜单';
UPDATE [sys_api] SET [title]=N'更新菜单' WHERE [path]=N'/api/sysMenu/edit' AND [method]=N'PUT' AND [title]<>N'更新菜单';
UPDATE [sys_api] SET [title]=N'导出菜单' WHERE [path]=N'/api/sysMenu/export' AND [method]=N'GET' AND [title]<>N'导出菜单';
UPDATE [sys_api] SET [title]=N'获取完整菜单列表' WHERE [path]=N'/api/sysMenu/getMenuList' AND [method]=N'GET' AND [title]<>N'获取完整菜单列表';
UPDATE [sys_api] SET [title]=N'获取用户权限菜单' WHERE [path]=N'/api/sysMenu/getRouters' AND [method]=N'GET' AND [title]<>N'获取用户权限菜单';
UPDATE [sys_api] SET [title]=N'设置菜单API权限' WHERE [path]=N'/api/sysMenu/setApis' AND [method]=N'POST' AND [title]<>N'设置菜单API权限';
UPDATE [sys_api] SET [title]=N'日志删除' WHERE [path]=N'/api/sysOperationLog/delete' AND [method]=N'DELETE' AND [title]<>N'日志删除';
UPDATE [sys_api] SET [title]=N'日志导出' WHERE [path]=N'/api/sysOperationLog/export' AND [method]=N'GET' AND [title]<>N'日志导出';
UPDATE [sys_api] SET [title]=N'新增角色' WHERE [path]=N'/api/sysRole/add' AND [method]=N'POST' AND [title]<>N'新增角色';
UPDATE [sys_api] SET [title]=N'添加角色的菜单权限' WHERE [path]=N'/api/sysRole/addRoleMenu' AND [method]=N'POST' AND [title]<>N'添加角色的菜单权限';
UPDATE [sys_api] SET [title]=N'设置数据权限' WHERE [path]=N'/api/sysRole/dataScope' AND [method]=N'PUT' AND [title]<>N'设置数据权限';
UPDATE [sys_api] SET [title]=N'删除角色' WHERE [path]=N'/api/sysRole/delete' AND [method]=N'DELETE' AND [title]<>N'删除角色';
UPDATE [sys_api] SET [title]=N'更新角色' WHERE [path]=N'/api/sysRole/edit' AND [method]=N'PUT' AND [title]<>N'更新角色';
UPDATE [sys_api] SET [title]=N'根据角色ID获取角色菜单权限' WHERE [path]=N'/api/sysRole/getUserPermission/:roleId' AND [method]=N'GET' AND [title]<>N'根据角色ID获取角色菜单权限';
UPDATE [sys_api] SET [title]=N'新增用户' WHERE [path]=N'/api/users/add' AND [method]=N'POST' AND [title]<>N'新增用户';
UPDATE [sys_api] SET [title]=N'删除用户' WHERE [path]=N'/api/users/delete' AND [method]=N'DELETE' AND [title]<>N'删除用户';
UPDATE [sys_api] SET [title]=N'更新用户信息' WHERE [path]=N'/api/users/edit' AND [method]=N'PUT' AND [title]<>N'更新用户信息';
UPDATE [sys_api] SET [title]=N'用户登出' WHERE [path]=N'/api/users/logout' AND [method]=N'POST' AND [title]<>N'用户登出';
UPDATE [sys_api] SET [title]=N'获取当前用户信息' WHERE [path]=N'/api/users/profile' AND [method]=N'GET' AND [title]<>N'获取当前用户信息';
