IF OBJECT_ID(N'sys_login_logs', N'U') IS NULL
BEGIN
  CREATE TABLE [sys_login_logs] ([id] BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,[user_id] BIGINT NULL,[username] NVARCHAR(100) NOT NULL,[result] NVARCHAR(16) NOT NULL,[failure_reason] NVARCHAR(48) NULL,[ip] NVARCHAR(50) NOT NULL DEFAULT N'',[location] NVARCHAR(100) NOT NULL DEFAULT N'未知',[user_agent] NVARCHAR(500) NOT NULL DEFAULT N'',[browser] NVARCHAR(100) NOT NULL DEFAULT N'未知',[os] NVARCHAR(100) NOT NULL DEFAULT N'未知',[created_at] DATETIME2 NOT NULL,[updated_at] DATETIME2 NULL,[deleted_at] DATETIME2 NULL);
END;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'idx_login_logs_user_id' AND object_id=OBJECT_ID(N'sys_login_logs')) CREATE INDEX idx_login_logs_user_id ON sys_login_logs(user_id);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'idx_login_logs_username' AND object_id=OBJECT_ID(N'sys_login_logs')) CREATE INDEX idx_login_logs_username ON sys_login_logs(username);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'idx_login_logs_result' AND object_id=OBJECT_ID(N'sys_login_logs')) CREATE INDEX idx_login_logs_result ON sys_login_logs(result);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'idx_login_logs_failure_reason' AND object_id=OBJECT_ID(N'sys_login_logs')) CREATE INDEX idx_login_logs_failure_reason ON sys_login_logs(failure_reason);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'idx_login_logs_ip' AND object_id=OBJECT_ID(N'sys_login_logs')) CREATE INDEX idx_login_logs_ip ON sys_login_logs(ip);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name=N'idx_login_logs_created_at' AND object_id=OBJECT_ID(N'sys_login_logs')) CREATE INDEX idx_login_logs_created_at ON sys_login_logs(created_at);
IF NOT EXISTS (SELECT 1 FROM sys_api WHERE path=N'/api/sysLoginLog/list' AND method=N'GET' AND deleted_at IS NULL) INSERT INTO sys_api(title,path,method,api_group,created_at,updated_at,created_by) VALUES(N'登录日志列表',N'/api/sysLoginLog/list',N'GET',N'日志管理',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1);
IF NOT EXISTS (SELECT 1 FROM sys_api WHERE path=N'/api/sysLoginLog/:id' AND method=N'GET' AND deleted_at IS NULL) INSERT INTO sys_api(title,path,method,api_group,created_at,updated_at,created_by) VALUES(N'登录日志详情',N'/api/sysLoginLog/:id',N'GET',N'日志管理',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1);
IF NOT EXISTS (SELECT 1 FROM sys_api WHERE path=N'/api/sysLoginLog/delete' AND method=N'DELETE' AND deleted_at IS NULL) INSERT INTO sys_api(title,path,method,api_group,created_at,updated_at,created_by) VALUES(N'删除登录日志',N'/api/sysLoginLog/delete',N'DELETE',N'日志管理',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1);
IF NOT EXISTS (SELECT 1 FROM sys_api WHERE path=N'/api/sysLoginLog/clear' AND method=N'POST' AND deleted_at IS NULL) INSERT INTO sys_api(title,path,method,api_group,created_at,updated_at,created_by) VALUES(N'清空登录日志',N'/api/sysLoginLog/clear',N'POST',N'日志管理',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1);
IF NOT EXISTS (SELECT 1 FROM sys_api WHERE path=N'/api/sysLoginLog/unlock' AND method=N'POST' AND deleted_at IS NULL) INSERT INTO sys_api(title,path,method,api_group,created_at,updated_at,created_by) VALUES(N'解锁登录账号',N'/api/sysLoginLog/unlock',N'POST',N'日志管理',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1);
IF NOT EXISTS (SELECT 1 FROM sys_menu WHERE path=N'/system/login-log' AND deleted_at IS NULL) INSERT INTO sys_menu(parent_id,path,name,component,title,hide,disable,sort,type,permission,icon,created_at,updated_at,created_by) SELECT TOP 1 id,N'/system/login-log',N'SystemLoginLog',N'system/login-log/index',N'登录日志',0,0,1,2,N'system:login-log:list',N'lucide:FileClock',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1 FROM sys_menu WHERE path=N'/system' AND type=1 AND deleted_at IS NULL;
INSERT INTO sys_menu(parent_id,path,name,title,hide,disable,sort,type,permission,created_at,updated_at,created_by) SELECT m.id,N'',N'SystemLoginLogDelete',N'删除登录日志',1,0,1,3,N'system:login-log:delete',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1 FROM sys_menu m WHERE m.permission=N'system:login-log:list' AND m.deleted_at IS NULL AND NOT EXISTS (SELECT 1 FROM sys_menu WHERE permission=N'system:login-log:delete' AND deleted_at IS NULL);
INSERT INTO sys_menu(parent_id,path,name,title,hide,disable,sort,type,permission,created_at,updated_at,created_by) SELECT m.id,N'',N'SystemLoginLogClear',N'清空登录日志',1,0,2,3,N'system:login-log:clear',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1 FROM sys_menu m WHERE m.permission=N'system:login-log:list' AND m.deleted_at IS NULL AND NOT EXISTS (SELECT 1 FROM sys_menu WHERE permission=N'system:login-log:clear' AND deleted_at IS NULL);
INSERT INTO sys_menu(parent_id,path,name,title,hide,disable,sort,type,permission,created_at,updated_at,created_by) SELECT m.id,N'',N'SystemLoginLogUnlock',N'解锁登录账号',1,0,3,3,N'system:login-log:unlock',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1 FROM sys_menu m WHERE m.permission=N'system:login-log:list' AND m.deleted_at IS NULL AND NOT EXISTS (SELECT 1 FROM sys_menu WHERE permission=N'system:login-log:unlock' AND deleted_at IS NULL);
INSERT INTO sys_role_menu(role_id,menu_id) SELECT 1,id FROM sys_menu m WHERE m.path=N'/system/login-log' AND m.deleted_at IS NULL AND NOT EXISTS (SELECT 1 FROM sys_role_menu x WHERE x.role_id=1 AND x.menu_id=m.id);
INSERT INTO sys_role_menu(role_id,menu_id) SELECT 1,id FROM sys_menu m WHERE m.permission IN (N'system:login-log:delete',N'system:login-log:clear',N'system:login-log:unlock') AND m.deleted_at IS NULL AND NOT EXISTS (SELECT 1 FROM sys_role_menu x WHERE x.role_id=1 AND x.menu_id=m.id);
INSERT INTO sys_menu_api(menu_id,api_id) SELECT m.id,a.id FROM sys_menu m JOIN sys_api a ON a.path IN (N'/api/sysLoginLog/list',N'/api/sysLoginLog/:id') AND a.method=N'GET' AND a.deleted_at IS NULL WHERE m.permission=N'system:login-log:list' AND NOT EXISTS (SELECT 1 FROM sys_menu_api x WHERE x.menu_id=m.id AND x.api_id=a.id);
INSERT INTO sys_menu_api(menu_id,api_id) SELECT m.id,a.id FROM sys_menu m JOIN sys_api a ON ((m.permission=N'system:login-log:delete' AND a.path=N'/api/sysLoginLog/delete' AND a.method=N'DELETE') OR (m.permission=N'system:login-log:clear' AND a.path=N'/api/sysLoginLog/clear' AND a.method=N'POST') OR (m.permission=N'system:login-log:unlock' AND a.path=N'/api/sysLoginLog/unlock' AND a.method=N'POST')) WHERE m.permission IN (N'system:login-log:delete',N'system:login-log:clear',N'system:login-log:unlock') AND a.deleted_at IS NULL AND NOT EXISTS (SELECT 1 FROM sys_menu_api x WHERE x.menu_id=m.id AND x.api_id=a.id);
INSERT INTO sys_casbin_rule(ptype,v0,v1,v2,v3,v4,v5) SELECT N'p',CONCAT(N'role_',rm.role_id),a.path,a.method,N'*',N'',N'' FROM sys_role_menu rm JOIN sys_menu m ON m.id=rm.menu_id JOIN sys_menu_api ma ON ma.menu_id=m.id JOIN sys_api a ON a.id=ma.api_id WHERE m.permission IN (N'system:login-log:list',N'system:login-log:delete',N'system:login-log:clear',N'system:login-log:unlock') AND NOT EXISTS (SELECT 1 FROM sys_casbin_rule c WHERE c.ptype=N'p' AND c.v0=CONCAT(N'role_',rm.role_id) AND c.v1=a.path AND c.v2=a.method AND c.v3=N'*');
