-- 回退「接口标题归一化」：把 title 改回本迁移执行前的值。
-- 旧值取自 220 的 sys_api_title_backup_20260921（标题归一化前的一次性快照），
-- 因此对**客户存量库**而言，down 只应作为「大致还原」参考，
-- 它未必等于那些库自己的旧值。

UPDATE `sys_api` SET `title`='设备、通道、目录与地图只读查询' WHERE `path`='/api/gb28181/device-mgmt/catalog/tree' AND `method`='GET' AND `title`<>'设备、通道、目录与地图只读查询';
UPDATE `sys_api` SET `title`='设备、通道、目录与地图只读查询' WHERE `path`='/api/gb28181/device-mgmt/catalog/tree/:id' AND `method`='GET' AND `title`<>'设备、通道、目录与地图只读查询';
UPDATE `sys_api` SET `title`='设备、通道、目录与地图只读查询' WHERE `path`='/api/gb28181/device-mgmt/catalog/tree/:id/children' AND `method`='GET' AND `title`<>'设备、通道、目录与地图只读查询';
UPDATE `sys_api` SET `title`='删除通道（单个/批量）' WHERE `path`='/api/gb28181/device-mgmt/channel/:id' AND `method`='DELETE' AND `title`<>'删除通道（单个/批量）';
UPDATE `sys_api` SET `title`='设备、通道、目录与地图只读查询' WHERE `path`='/api/gb28181/device-mgmt/channel/:id' AND `method`='GET' AND `title`<>'设备、通道、目录与地图只读查询';
UPDATE `sys_api` SET `title`='云台能力、状态与预置/巡航资源读取' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/control-capabilities' AND `method`='GET' AND `title`<>'云台能力、状态与预置/巡航资源读取';
UPDATE `sys_api` SET `title`='云台能力、状态与预置/巡航资源读取' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/device-status' AND `method`='GET' AND `title`<>'云台能力、状态与预置/巡航资源读取';
UPDATE `sys_api` SET `title`='设备、通道、目录与地图只读查询' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/mounts' AND `method`='GET' AND `title`<>'设备、通道、目录与地图只读查询';
UPDATE `sys_api` SET `title`='设备录像回放会话（播放、暂停/续播、倍速、停止）' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/playback-sessions' AND `method`='POST' AND `title`<>'设备录像回放会话（播放、暂停/续播、倍速、停止）';
UPDATE `sys_api` SET `title`='设备录像回放会话（播放、暂停/续播、倍速、停止）' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/playback-sessions/:sessionId' AND `method`='DELETE' AND `title`<>'设备录像回放会话（播放、暂停/续播、倍速、停止）';
UPDATE `sys_api` SET `title`='设备录像回放会话（播放、暂停/续播、倍速、停止）' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/playback-sessions/:sessionId' AND `method`='GET' AND `title`<>'设备录像回放会话（播放、暂停/续播、倍速、停止）';
UPDATE `sys_api` SET `title`='设备录像回放会话（播放、暂停/续播、倍速、停止）' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/playback-sessions/:sessionId/actions' AND `method`='POST' AND `title`<>'设备录像回放会话（播放、暂停/续播、倍速、停止）';
UPDATE `sys_api` SET `title`='云台移动、变倍、聚焦、光圈（基础/精准/扩展）' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/ptz' AND `method`='POST' AND `title`<>'云台移动、变倍、聚焦、光圈（基础/精准/扩展）';
UPDATE `sys_api` SET `title`='云台巡航轨迹创建、启动、停止与删除' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/ptz/cruise' AND `method`='POST' AND `title`<>'云台巡航轨迹创建、启动、停止与删除';
UPDATE `sys_api` SET `title`='云台能力、状态与预置/巡航资源读取' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/ptz/cruise-tracks' AND `method`='GET' AND `title`<>'云台能力、状态与预置/巡航资源读取';
UPDATE `sys_api` SET `title`='云台能力、状态与预置/巡航资源读取' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/ptz/cruise-tracks/:trackId' AND `method`='GET' AND `title`<>'云台能力、状态与预置/巡航资源读取';
UPDATE `sys_api` SET `title`='云台巡航轨迹创建、启动、停止与删除' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/ptz/cruise/tracks' AND `method`='POST' AND `title`<>'云台巡航轨迹创建、启动、停止与删除';
UPDATE `sys_api` SET `title`='云台移动、变倍、聚焦、光圈（基础/精准/扩展）' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/ptz/extended' AND `method`='POST' AND `title`<>'云台移动、变倍、聚焦、光圈（基础/精准/扩展）';
UPDATE `sys_api` SET `title`='云台能力、状态与预置/巡航资源读取' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/ptz/home-position' AND `method`='GET' AND `title`<>'云台能力、状态与预置/巡航资源读取';
UPDATE `sys_api` SET `title`='云台能力、状态与预置/巡航资源读取' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/ptz/operations/:operationId' AND `method`='GET' AND `title`<>'云台能力、状态与预置/巡航资源读取';
UPDATE `sys_api` SET `title`='云台移动、变倍、聚焦、光圈（基础/精准/扩展）' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/ptz/precise' AND `method`='POST' AND `title`<>'云台移动、变倍、聚焦、光圈（基础/精准/扩展）';
UPDATE `sys_api` SET `title`='云台能力、状态与预置/巡航资源读取' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/ptz/precise-status' AND `method`='GET' AND `title`<>'云台能力、状态与预置/巡航资源读取';
UPDATE `sys_api` SET `title`='云台能力、状态与预置/巡航资源读取' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/ptz/presets' AND `method`='GET' AND `title`<>'云台能力、状态与预置/巡航资源读取';
UPDATE `sys_api` SET `title`='查询设备录像' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/record-query/options' AND `method`='GET' AND `title`<>'查询设备录像';
UPDATE `sys_api` SET `title`='设备图像抓拍会话' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/snapshot-sessions' AND `method`='POST' AND `title`<>'设备图像抓拍会话';
UPDATE `sys_api` SET `title`='设备图像抓拍会话' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/snapshot-sessions/:sessionId' AND `method`='GET' AND `title`<>'设备图像抓拍会话';
UPDATE `sys_api` SET `title`='语音对讲与广播会话' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/talk-sessions' AND `method`='POST' AND `title`<>'语音对讲与广播会话';
UPDATE `sys_api` SET `title`='语音对讲与广播会话' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/talk-sessions/:sessionId' AND `method`='DELETE' AND `title`<>'语音对讲与广播会话';
UPDATE `sys_api` SET `title`='语音对讲与广播会话' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/talk-sessions/:sessionId' AND `method`='GET' AND `title`<>'语音对讲与广播会话';
UPDATE `sys_api` SET `title`='设备、通道、目录与地图只读查询' WHERE `path`='/api/gb28181/device-mgmt/channel/:id/timeline' AND `method`='GET' AND `title`<>'设备、通道、目录与地图只读查询';
UPDATE `sys_api` SET `title`='删除通道（单个/批量）' WHERE `path`='/api/gb28181/device-mgmt/channel/batch-delete' AND `method`='POST' AND `title`<>'删除通道（单个/批量）';
UPDATE `sys_api` SET `title`='设备、通道、目录与地图只读查询' WHERE `path`='/api/gb28181/device-mgmt/channels' AND `method`='GET' AND `title`<>'设备、通道、目录与地图只读查询';
UPDATE `sys_api` SET `title`='删除设备（单个/批量）' WHERE `path`='/api/gb28181/device-mgmt/device/:id' AND `method`='DELETE' AND `title`<>'删除设备（单个/批量）';
UPDATE `sys_api` SET `title`='设备、通道、目录与地图只读查询' WHERE `path`='/api/gb28181/device-mgmt/device/:id' AND `method`='GET' AND `title`<>'设备、通道、目录与地图只读查询';
UPDATE `sys_api` SET `title`='查看设备维护' WHERE `path`='/api/gb28181/device-mgmt/device/:id/maintenance-operations' AND `method`='GET' AND `title`<>'查看设备维护';
UPDATE `sys_api` SET `title`='设备、通道、目录与地图只读查询' WHERE `path`='/api/gb28181/device-mgmt/device/:id/status-events' AND `method`='GET' AND `title`<>'设备、通道、目录与地图只读查询';
UPDATE `sys_api` SET `title`='设备订阅读取、更新与续订' WHERE `path`='/api/gb28181/device-mgmt/device/:id/subscriptions' AND `method`='GET' AND `title`<>'设备订阅读取、更新与续订';
UPDATE `sys_api` SET `title`='设备订阅读取、更新与续订' WHERE `path`='/api/gb28181/device-mgmt/device/:id/subscriptions/:kind' AND `method`='PATCH' AND `title`<>'设备订阅读取、更新与续订';
UPDATE `sys_api` SET `title`='设备订阅读取、更新与续订' WHERE `path`='/api/gb28181/device-mgmt/device/:id/subscriptions/:kind/renew' AND `method`='POST' AND `title`<>'设备订阅读取、更新与续订';
UPDATE `sys_api` SET `title`='删除设备（单个/批量）' WHERE `path`='/api/gb28181/device-mgmt/device/batch-delete' AND `method`='POST' AND `title`<>'删除设备（单个/批量）';
UPDATE `sys_api` SET `title`='设备、通道、目录与地图只读查询' WHERE `path`='/api/gb28181/device-mgmt/devices' AND `method`='GET' AND `title`<>'设备、通道、目录与地图只读查询';
UPDATE `sys_api` SET `title`='设备、通道、目录与地图只读查询' WHERE `path`='/api/gb28181/device-mgmt/directory/tree' AND `method`='GET' AND `title`<>'设备、通道、目录与地图只读查询';
UPDATE `sys_api` SET `title`='设备、通道、目录与地图只读查询' WHERE `path`='/api/gb28181/device-mgmt/map/clusters' AND `method`='GET' AND `title`<>'设备、通道、目录与地图只读查询';
UPDATE `sys_api` SET `title`='设备、通道、目录与地图只读查询' WHERE `path`='/api/gb28181/device-mgmt/map/markers' AND `method`='GET' AND `title`<>'设备、通道、目录与地图只读查询';
UPDATE `sys_api` SET `title`='查看仪表盘' WHERE `path`='/api/gb28181/home/drilldown/play' AND `method`='GET' AND `title`<>'查看仪表盘';
UPDATE `sys_api` SET `title`='查看仪表盘' WHERE `path`='/api/gb28181/home/drilldown/sip' AND `method`='GET' AND `title`<>'查看仪表盘';
UPDATE `sys_api` SET `title`='查看仪表盘' WHERE `path`='/api/gb28181/home/drilldown/traffic' AND `method`='GET' AND `title`<>'查看仪表盘';
UPDATE `sys_api` SET `title`='查看仪表盘' WHERE `path`='/api/gb28181/home/layout' AND `method`='GET' AND `title`<>'查看仪表盘';
UPDATE `sys_api` SET `title`='查看仪表盘' WHERE `path`='/api/gb28181/home/summary' AND `method`='GET' AND `title`<>'查看仪表盘';
UPDATE `sys_api` SET `title`='分配录像计划' WHERE `path`='/api/gb28181/recording-plans/:id/assignments' AND `method`='POST' AND `title`<>'分配录像计划';
UPDATE `sys_api` SET `title`='查看与观看依赖' WHERE `path`='/api/gb28181/sip/dashboard/snapshot' AND `method`='GET' AND `title`<>'查看与观看依赖';
UPDATE `sys_api` SET `title`='修改 SIP 配置' WHERE `path`='/api/gb28181/sip/service-config/default-channel-stream-transport' AND `method`='PUT' AND `title`<>'修改 SIP 配置';
UPDATE `sys_api` SET `title`='查看与观看依赖' WHERE `path`='/api/gb28181/sip/service-config/playback-settings' AND `method`='GET' AND `title`<>'查看与观看依赖';
UPDATE `sys_api` SET `title`='修改 SIP 配置' WHERE `path`='/api/gb28181/sip/service-config/playback-settings' AND `method`='PUT' AND `title`<>'修改 SIP 配置';
UPDATE `sys_api` SET `title`='修改 SIP 配置' WHERE `path`='/api/gb28181/sip/service-config/sdp-extension' AND `method`='PUT' AND `title`<>'修改 SIP 配置';
UPDATE `sys_api` SET `title`='视频探针诊断' WHERE `path`='/api/gb28181/stream-probes/:streamId' AND `method`='POST' AND `title`<>'视频探针诊断';
UPDATE `sys_api` SET `title`='查询视频探针任务' WHERE `path`='/api/gb28181/stream-probes/operations/:operationId' AND `method`='GET' AND `title`<>'查询视频探针任务';
UPDATE `sys_api` SET `title`='媒体管理 GET zlm/nodes' WHERE `path`='/api/gb28181/zlm/nodes' AND `method`='GET' AND `title`<>'媒体管理 GET zlm/nodes';
UPDATE `sys_api` SET `title`='媒体管理 POST zlm/nodes' WHERE `path`='/api/gb28181/zlm/nodes' AND `method`='POST' AND `title`<>'媒体管理 POST zlm/nodes';
UPDATE `sys_api` SET `title`='媒体管理 DELETE zlm/nodes/:id' WHERE `path`='/api/gb28181/zlm/nodes/:id' AND `method`='DELETE' AND `title`<>'媒体管理 DELETE zlm/nodes/:id';
UPDATE `sys_api` SET `title`='媒体管理 GET zlm/nodes/:id' WHERE `path`='/api/gb28181/zlm/nodes/:id' AND `method`='GET' AND `title`<>'媒体管理 GET zlm/nodes/:id';
UPDATE `sys_api` SET `title`='媒体管理 PUT zlm/nodes/:id' WHERE `path`='/api/gb28181/zlm/nodes/:id' AND `method`='PUT' AND `title`<>'媒体管理 PUT zlm/nodes/:id';
UPDATE `sys_api` SET `title`='媒体管理 POST zlm/nodes/:id/activate' WHERE `path`='/api/gb28181/zlm/nodes/:id/activate' AND `method`='POST' AND `title`<>'媒体管理 POST zlm/nodes/:id/activate';
UPDATE `sys_api` SET `title`='媒体管理 GET zlm/nodes/:id/config' WHERE `path`='/api/gb28181/zlm/nodes/:id/config' AND `method`='GET' AND `title`<>'媒体管理 GET zlm/nodes/:id/config';
UPDATE `sys_api` SET `title`='媒体管理 PUT zlm/nodes/:id/config' WHERE `path`='/api/gb28181/zlm/nodes/:id/config' AND `method`='PUT' AND `title`<>'媒体管理 PUT zlm/nodes/:id/config';
UPDATE `sys_api` SET `title`='媒体管理 POST zlm/nodes/:id/config/test-connection' WHERE `path`='/api/gb28181/zlm/nodes/:id/config/test-connection' AND `method`='POST' AND `title`<>'媒体管理 POST zlm/nodes/:id/config/test-connection';
UPDATE `sys_api` SET `title`='媒体管理 GET zlm/nodes/:id/ffmpeg-sources' WHERE `path`='/api/gb28181/zlm/nodes/:id/ffmpeg-sources' AND `method`='GET' AND `title`<>'媒体管理 GET zlm/nodes/:id/ffmpeg-sources';
UPDATE `sys_api` SET `title`='媒体管理 POST zlm/nodes/:id/ffmpeg-sources' WHERE `path`='/api/gb28181/zlm/nodes/:id/ffmpeg-sources' AND `method`='POST' AND `title`<>'媒体管理 POST zlm/nodes/:id/ffmpeg-sources';
UPDATE `sys_api` SET `title`='媒体管理 DELETE zlm/nodes/:id/ffmpeg-sources/:key' WHERE `path`='/api/gb28181/zlm/nodes/:id/ffmpeg-sources/:key' AND `method`='DELETE' AND `title`<>'媒体管理 DELETE zlm/nodes/:id/ffmpeg-sources/:key';
UPDATE `sys_api` SET `title`='媒体管理 POST zlm/nodes/:id/ffmpeg-sources/:key/preflight' WHERE `path`='/api/gb28181/zlm/nodes/:id/ffmpeg-sources/:key/preflight' AND `method`='POST' AND `title`<>'媒体管理 POST zlm/nodes/:id/ffmpeg-sources/:key/preflight';
UPDATE `sys_api` SET `title`='媒体管理 POST zlm/nodes/:id/kick' WHERE `path`='/api/gb28181/zlm/nodes/:id/kick' AND `method`='POST' AND `title`<>'媒体管理 POST zlm/nodes/:id/kick';
UPDATE `sys_api` SET `title`='媒体管理 POST zlm/nodes/:id/maintenance' WHERE `path`='/api/gb28181/zlm/nodes/:id/maintenance' AND `method`='POST' AND `title`<>'媒体管理 POST zlm/nodes/:id/maintenance';
UPDATE `sys_api` SET `title`='媒体管理 GET zlm/nodes/:id/proxies/pull' WHERE `path`='/api/gb28181/zlm/nodes/:id/proxies/pull' AND `method`='GET' AND `title`<>'媒体管理 GET zlm/nodes/:id/proxies/pull';
UPDATE `sys_api` SET `title`='媒体管理 POST zlm/nodes/:id/proxies/pull' WHERE `path`='/api/gb28181/zlm/nodes/:id/proxies/pull' AND `method`='POST' AND `title`<>'媒体管理 POST zlm/nodes/:id/proxies/pull';
UPDATE `sys_api` SET `title`='媒体管理 DELETE zlm/nodes/:id/proxies/pull/:key' WHERE `path`='/api/gb28181/zlm/nodes/:id/proxies/pull/:key' AND `method`='DELETE' AND `title`<>'媒体管理 DELETE zlm/nodes/:id/proxies/pull/:key';
UPDATE `sys_api` SET `title`='媒体管理 GET zlm/nodes/:id/proxies/pull/:key' WHERE `path`='/api/gb28181/zlm/nodes/:id/proxies/pull/:key' AND `method`='GET' AND `title`<>'媒体管理 GET zlm/nodes/:id/proxies/pull/:key';
UPDATE `sys_api` SET `title`='媒体管理 POST zlm/nodes/:id/proxies/pull/:key/preflight' WHERE `path`='/api/gb28181/zlm/nodes/:id/proxies/pull/:key/preflight' AND `method`='POST' AND `title`<>'媒体管理 POST zlm/nodes/:id/proxies/pull/:key/preflight';
UPDATE `sys_api` SET `title`='媒体管理 GET zlm/nodes/:id/proxies/push' WHERE `path`='/api/gb28181/zlm/nodes/:id/proxies/push' AND `method`='GET' AND `title`<>'媒体管理 GET zlm/nodes/:id/proxies/push';
UPDATE `sys_api` SET `title`='媒体管理 POST zlm/nodes/:id/proxies/push' WHERE `path`='/api/gb28181/zlm/nodes/:id/proxies/push' AND `method`='POST' AND `title`<>'媒体管理 POST zlm/nodes/:id/proxies/push';
UPDATE `sys_api` SET `title`='媒体管理 DELETE zlm/nodes/:id/proxies/push/:key' WHERE `path`='/api/gb28181/zlm/nodes/:id/proxies/push/:key' AND `method`='DELETE' AND `title`<>'媒体管理 DELETE zlm/nodes/:id/proxies/push/:key';
UPDATE `sys_api` SET `title`='媒体管理 GET zlm/nodes/:id/proxies/push/:key' WHERE `path`='/api/gb28181/zlm/nodes/:id/proxies/push/:key' AND `method`='GET' AND `title`<>'媒体管理 GET zlm/nodes/:id/proxies/push/:key';
UPDATE `sys_api` SET `title`='媒体管理 POST zlm/nodes/:id/proxies/push/:key/preflight' WHERE `path`='/api/gb28181/zlm/nodes/:id/proxies/push/:key/preflight' AND `method`='POST' AND `title`<>'媒体管理 POST zlm/nodes/:id/proxies/push/:key/preflight';
UPDATE `sys_api` SET `title`='媒体管理 POST zlm/nodes/:id/recordings/runtime/force-stop' WHERE `path`='/api/gb28181/zlm/nodes/:id/recordings/runtime/force-stop' AND `method`='POST' AND `title`<>'媒体管理 POST zlm/nodes/:id/recordings/runtime/force-stop';
UPDATE `sys_api` SET `title`='媒体管理 POST zlm/nodes/:id/recordings/runtime/force-stop/preflight' WHERE `path`='/api/gb28181/zlm/nodes/:id/recordings/runtime/force-stop/preflight' AND `method`='POST' AND `title`<>'媒体管理 POST zlm/nodes/:id/recordings/runtime/force-stop/preflight';
UPDATE `sys_api` SET `title`='媒体管理 POST zlm/nodes/:id/recordings/runtime/start' WHERE `path`='/api/gb28181/zlm/nodes/:id/recordings/runtime/start' AND `method`='POST' AND `title`<>'媒体管理 POST zlm/nodes/:id/recordings/runtime/start';
UPDATE `sys_api` SET `title`='媒体管理 POST zlm/nodes/:id/recordings/runtime/start/preflight' WHERE `path`='/api/gb28181/zlm/nodes/:id/recordings/runtime/start/preflight' AND `method`='POST' AND `title`<>'媒体管理 POST zlm/nodes/:id/recordings/runtime/start/preflight';
UPDATE `sys_api` SET `title`='媒体管理 GET zlm/nodes/:id/recordings/runtime/status' WHERE `path`='/api/gb28181/zlm/nodes/:id/recordings/runtime/status' AND `method`='GET' AND `title`<>'媒体管理 GET zlm/nodes/:id/recordings/runtime/status';
UPDATE `sys_api` SET `title`='媒体管理 POST zlm/nodes/:id/recordings/runtime/stop' WHERE `path`='/api/gb28181/zlm/nodes/:id/recordings/runtime/stop' AND `method`='POST' AND `title`<>'媒体管理 POST zlm/nodes/:id/recordings/runtime/stop';
UPDATE `sys_api` SET `title`='媒体管理 POST zlm/nodes/:id/recordings/runtime/stop/preflight' WHERE `path`='/api/gb28181/zlm/nodes/:id/recordings/runtime/stop/preflight' AND `method`='POST' AND `title`<>'媒体管理 POST zlm/nodes/:id/recordings/runtime/stop/preflight';
UPDATE `sys_api` SET `title`='媒体管理 GET zlm/nodes/:id/restart' WHERE `path`='/api/gb28181/zlm/nodes/:id/restart' AND `method`='GET' AND `title`<>'媒体管理 GET zlm/nodes/:id/restart';
UPDATE `sys_api` SET `title`='媒体管理 POST zlm/nodes/:id/restart' WHERE `path`='/api/gb28181/zlm/nodes/:id/restart' AND `method`='POST' AND `title`<>'媒体管理 POST zlm/nodes/:id/restart';
UPDATE `sys_api` SET `title`='媒体管理 GET zlm/nodes/:id/rtp-servers' WHERE `path`='/api/gb28181/zlm/nodes/:id/rtp-servers' AND `method`='GET' AND `title`<>'媒体管理 GET zlm/nodes/:id/rtp-servers';
UPDATE `sys_api` SET `title`='媒体管理 POST zlm/nodes/:id/rtp-servers' WHERE `path`='/api/gb28181/zlm/nodes/:id/rtp-servers' AND `method`='POST' AND `title`<>'媒体管理 POST zlm/nodes/:id/rtp-servers';
UPDATE `sys_api` SET `title`='媒体管理 POST zlm/nodes/:id/rtp-servers/close' WHERE `path`='/api/gb28181/zlm/nodes/:id/rtp-servers/close' AND `method`='POST' AND `title`<>'媒体管理 POST zlm/nodes/:id/rtp-servers/close';
UPDATE `sys_api` SET `title`='媒体管理 POST zlm/nodes/:id/rtp-servers/close/preflight' WHERE `path`='/api/gb28181/zlm/nodes/:id/rtp-servers/close/preflight' AND `method`='POST' AND `title`<>'媒体管理 POST zlm/nodes/:id/rtp-servers/close/preflight';
UPDATE `sys_api` SET `title`='媒体管理 POST zlm/nodes/:id/rtp-servers/force-close' WHERE `path`='/api/gb28181/zlm/nodes/:id/rtp-servers/force-close' AND `method`='POST' AND `title`<>'媒体管理 POST zlm/nodes/:id/rtp-servers/force-close';
UPDATE `sys_api` SET `title`='媒体管理 GET zlm/nodes/:id/runtime' WHERE `path`='/api/gb28181/zlm/nodes/:id/runtime' AND `method`='GET' AND `title`<>'媒体管理 GET zlm/nodes/:id/runtime';
UPDATE `sys_api` SET `title`='媒体管理 POST zlm/nodes/:id/sessions/kick' WHERE `path`='/api/gb28181/zlm/nodes/:id/sessions/kick' AND `method`='POST' AND `title`<>'媒体管理 POST zlm/nodes/:id/sessions/kick';
UPDATE `sys_api` SET `title`='媒体管理 GET zlm/nodes/:id/sessions/network' WHERE `path`='/api/gb28181/zlm/nodes/:id/sessions/network' AND `method`='GET' AND `title`<>'媒体管理 GET zlm/nodes/:id/sessions/network';
UPDATE `sys_api` SET `title`='媒体管理 GET zlm/nodes/:id/sessions/viewers' WHERE `path`='/api/gb28181/zlm/nodes/:id/sessions/viewers' AND `method`='GET' AND `title`<>'媒体管理 GET zlm/nodes/:id/sessions/viewers';
UPDATE `sys_api` SET `title`='媒体管理 GET zlm/nodes/:id/streams' WHERE `path`='/api/gb28181/zlm/nodes/:id/streams' AND `method`='GET' AND `title`<>'媒体管理 GET zlm/nodes/:id/streams';
UPDATE `sys_api` SET `title`='媒体管理 POST zlm/nodes/:id/streams/close' WHERE `path`='/api/gb28181/zlm/nodes/:id/streams/close' AND `method`='POST' AND `title`<>'媒体管理 POST zlm/nodes/:id/streams/close';
UPDATE `sys_api` SET `title`='媒体管理 POST zlm/nodes/:id/streams/close/batch' WHERE `path`='/api/gb28181/zlm/nodes/:id/streams/close/batch' AND `method`='POST' AND `title`<>'媒体管理 POST zlm/nodes/:id/streams/close/batch';
UPDATE `sys_api` SET `title`='媒体管理 POST zlm/nodes/:id/streams/close/batch/preflight' WHERE `path`='/api/gb28181/zlm/nodes/:id/streams/close/batch/preflight' AND `method`='POST' AND `title`<>'媒体管理 POST zlm/nodes/:id/streams/close/batch/preflight';
UPDATE `sys_api` SET `title`='媒体管理 POST zlm/nodes/:id/streams/close/preflight' WHERE `path`='/api/gb28181/zlm/nodes/:id/streams/close/preflight' AND `method`='POST' AND `title`<>'媒体管理 POST zlm/nodes/:id/streams/close/preflight';
UPDATE `sys_api` SET `title`='媒体管理 GET zlm/nodes/:id/streams/detail' WHERE `path`='/api/gb28181/zlm/nodes/:id/streams/detail' AND `method`='GET' AND `title`<>'媒体管理 GET zlm/nodes/:id/streams/detail';
UPDATE `sys_api` SET `title`='媒体管理 POST zlm/nodes/:id/streams/force-close' WHERE `path`='/api/gb28181/zlm/nodes/:id/streams/force-close' AND `method`='POST' AND `title`<>'媒体管理 POST zlm/nodes/:id/streams/force-close';
UPDATE `sys_api` SET `title`='媒体管理 POST zlm/nodes/:id/streams/playback-grant' WHERE `path`='/api/gb28181/zlm/nodes/:id/streams/playback-grant' AND `method`='POST' AND `title`<>'媒体管理 POST zlm/nodes/:id/streams/playback-grant';
UPDATE `sys_api` SET `title`='媒体管理 GET zlm/nodes/:id/streams/snapshot' WHERE `path`='/api/gb28181/zlm/nodes/:id/streams/snapshot' AND `method`='GET' AND `title`<>'媒体管理 GET zlm/nodes/:id/streams/snapshot';
UPDATE `sys_api` SET `title`='媒体管理 GET zlm/nodes/:id/streams/viewers' WHERE `path`='/api/gb28181/zlm/nodes/:id/streams/viewers' AND `method`='GET' AND `title`<>'媒体管理 GET zlm/nodes/:id/streams/viewers';
UPDATE `sys_api` SET `title`='管理节点' WHERE `path`='/api/gb28181/zlm/nodes/probe' AND `method`='POST' AND `title`<>'管理节点';
UPDATE `sys_api` SET `title`='媒体管理 GET zlm/overview' WHERE `path`='/api/gb28181/zlm/overview' AND `method`='GET' AND `title`<>'媒体管理 GET zlm/overview';
UPDATE `sys_api` SET `title`='媒体管理 GET zlm/scheduler' WHERE `path`='/api/gb28181/zlm/scheduler' AND `method`='GET' AND `title`<>'媒体管理 GET zlm/scheduler';
UPDATE `sys_api` SET `title`='媒体管理 PUT zlm/scheduler' WHERE `path`='/api/gb28181/zlm/scheduler' AND `method`='PUT' AND `title`<>'媒体管理 PUT zlm/scheduler';
UPDATE `sys_api` SET `title`='媒体管理 GET zlm/scheduler/logs' WHERE `path`='/api/gb28181/zlm/scheduler/logs' AND `method`='GET' AND `title`<>'媒体管理 GET zlm/scheduler/logs';
UPDATE `sys_api` SET `title`='媒体管理 GET zlm/streams' WHERE `path`='/api/gb28181/zlm/streams' AND `method`='GET' AND `title`<>'媒体管理 GET zlm/streams';
UPDATE `sys_api` SET `title`='新增' WHERE `path`='/api/plugins/example/add' AND `method`='POST' AND `title`<>'新增';
UPDATE `sys_api` SET `title`='删除' WHERE `path`='/api/plugins/example/delete' AND `method`='DELETE' AND `title`<>'删除';
