-- retire-legacy-media-menus:down:start
-- 回滚:恢复 13 条兼容跳转壳菜单行、角色绑定与原始读接口归属,并把实时日志控制台移回流媒体管理(MySQL)。
-- 注意:前端兼容层(LegacyMediaRoute.vue / mediaRoutes.ts)与 RecordingCenter.vue 已随本次清理删除,
-- 回滚后需从 git 历史恢复这些文件,跳转壳菜单才可正常打开。
-- 读接口归属按「菜单 path + 接口 path」恢复:api_id 为自增列,跨库会漂移,不能硬编码。
DELETE ma FROM `sys_menu_api` ma JOIN `sys_menu` m ON m.`id`=ma.`menu_id` JOIN `sys_api` a ON a.`id`=ma.`api_id` WHERE m.`path` IN ('/media/overview','/media/monitoring','/media/ingress','/media/nodes','/media/scheduling') AND a.`path` LIKE '/api/gb28181/zlm/%';
INSERT INTO `sys_menu` (`id`,`parent_id`,`path`,`name`,`redirect`,`component`,`title`,`is_full`,`hide`,`disable`,`keep_alive`,`affix`,`link`,`iframe`,`svg_icon`,`icon`,`sort`,`type`,`is_link`,`permission`,`created_by`,`created_at`,`updated_at`) SELECT 140351,140355,'/gb28181/zlm/nodes','gb28181-zlm-nodes','','gb28181/zlm/workbench/LegacyMediaRoute','节点管理',0,0,0,0,0,'',0,'','lucide:Server',20,2,0,'',0,NOW(),NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_menu` WHERE `id`=140351);
INSERT INTO `sys_menu` (`id`,`parent_id`,`path`,`name`,`redirect`,`component`,`title`,`is_full`,`hide`,`disable`,`keep_alive`,`affix`,`link`,`iframe`,`svg_icon`,`icon`,`sort`,`type`,`is_link`,`permission`,`created_by`,`created_at`,`updated_at`) SELECT 140352,0,'/gb28181/zlm/nodes/:id','gb28181-zlm-node-detail','','gb28181/zlm/workbench/LegacyMediaRoute','节点详情',0,0,0,0,0,'',0,'','lucide:Server',6,2,0,'',0,NOW(),NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_menu` WHERE `id`=140352);
INSERT INTO `sys_menu` (`id`,`parent_id`,`path`,`name`,`redirect`,`component`,`title`,`is_full`,`hide`,`disable`,`keep_alive`,`affix`,`link`,`iframe`,`svg_icon`,`icon`,`sort`,`type`,`is_link`,`permission`,`created_by`,`created_at`,`updated_at`) SELECT 140353,140355,'/gb28181/zlm/scheduler','gb28181-zlm-scheduler-strategy','','gb28181/zlm/workbench/LegacyMediaRoute','调度策略',0,0,0,0,0,'',0,'','lucide:Workflow',100,2,0,'',0,NOW(),NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_menu` WHERE `id`=140353);
INSERT INTO `sys_menu` (`id`,`parent_id`,`path`,`name`,`redirect`,`component`,`title`,`is_full`,`hide`,`disable`,`keep_alive`,`affix`,`link`,`iframe`,`svg_icon`,`icon`,`sort`,`type`,`is_link`,`permission`,`created_by`,`created_at`,`updated_at`) SELECT 140354,140355,'/gb28181/zlm/scheduler/logs','gb28181-zlm-scheduler-log','','gb28181/zlm/workbench/LegacyMediaRoute','调度日志',0,0,0,0,0,'',0,'','lucide:History',110,2,0,'',0,NOW(),NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_menu` WHERE `id`=140354);
INSERT INTO `sys_menu` (`id`,`parent_id`,`path`,`name`,`redirect`,`component`,`title`,`is_full`,`hide`,`disable`,`keep_alive`,`affix`,`link`,`iframe`,`svg_icon`,`icon`,`sort`,`type`,`is_link`,`permission`,`created_by`,`created_at`,`updated_at`) SELECT 140403,140355,'/gb28181/zlm/overview','gb28181-zlm-overview','','gb28181/zlm/workbench/LegacyMediaRoute','总览',0,0,0,0,0,'',0,'','lucide:LayoutDashboard',10,2,0,'',0,NOW(),NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_menu` WHERE `id`=140403);
INSERT INTO `sys_menu` (`id`,`parent_id`,`path`,`name`,`redirect`,`component`,`title`,`is_full`,`hide`,`disable`,`keep_alive`,`affix`,`link`,`iframe`,`svg_icon`,`icon`,`sort`,`type`,`is_link`,`permission`,`created_by`,`created_at`,`updated_at`) SELECT 140404,140355,'/gb28181/zlm/runtime','gb28181-zlm-runtime','','gb28181/zlm/workbench/LegacyMediaRoute','总览',0,0,0,0,0,'',0,'','lucide:Gauge',30,2,0,'',0,NOW(),NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_menu` WHERE `id`=140404);
INSERT INTO `sys_menu` (`id`,`parent_id`,`path`,`name`,`redirect`,`component`,`title`,`is_full`,`hide`,`disable`,`keep_alive`,`affix`,`link`,`iframe`,`svg_icon`,`icon`,`sort`,`type`,`is_link`,`permission`,`created_by`,`created_at`,`updated_at`) SELECT 140405,140355,'/gb28181/zlm/streams','gb28181-zlm-streams','','gb28181/zlm/workbench/LegacyMediaRoute','流管理',0,0,0,0,0,'',0,'','lucide:RadioTower',40,2,0,'',0,NOW(),NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_menu` WHERE `id`=140405);
INSERT INTO `sys_menu` (`id`,`parent_id`,`path`,`name`,`redirect`,`component`,`title`,`is_full`,`hide`,`disable`,`keep_alive`,`affix`,`link`,`iframe`,`svg_icon`,`icon`,`sort`,`type`,`is_link`,`permission`,`created_by`,`created_at`,`updated_at`) SELECT 140406,140355,'/gb28181/zlm/sessions','gb28181-zlm-sessions','','gb28181/zlm/workbench/LegacyMediaRoute','会话管理',0,0,0,0,0,'',0,'','lucide:Users',50,2,0,'',0,NOW(),NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_menu` WHERE `id`=140406);
INSERT INTO `sys_menu` (`id`,`parent_id`,`path`,`name`,`redirect`,`component`,`title`,`is_full`,`hide`,`disable`,`keep_alive`,`affix`,`link`,`iframe`,`svg_icon`,`icon`,`sort`,`type`,`is_link`,`permission`,`created_by`,`created_at`,`updated_at`) SELECT 140407,140355,'/gb28181/zlm/proxies','gb28181-zlm-proxies','','gb28181/zlm/workbench/LegacyMediaRoute','拉流/推流代理',0,0,0,0,0,'',0,'','lucide:Network',60,2,0,'',0,NOW(),NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_menu` WHERE `id`=140407);
INSERT INTO `sys_menu` (`id`,`parent_id`,`path`,`name`,`redirect`,`component`,`title`,`is_full`,`hide`,`disable`,`keep_alive`,`affix`,`link`,`iframe`,`svg_icon`,`icon`,`sort`,`type`,`is_link`,`permission`,`created_by`,`created_at`,`updated_at`) SELECT 140408,140355,'/gb28181/zlm/ffmpeg-sources','gb28181-zlm-ffmpeg-sources','','gb28181/zlm/workbench/LegacyMediaRoute','FFmpeg 源',0,0,0,0,0,'',0,'','lucide:Clapperboard',70,2,0,'',0,NOW(),NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_menu` WHERE `id`=140408);
INSERT INTO `sys_menu` (`id`,`parent_id`,`path`,`name`,`redirect`,`component`,`title`,`is_full`,`hide`,`disable`,`keep_alive`,`affix`,`link`,`iframe`,`svg_icon`,`icon`,`sort`,`type`,`is_link`,`permission`,`created_by`,`created_at`,`updated_at`) SELECT 140409,140355,'/gb28181/zlm/rtp-servers','gb28181-zlm-rtp-servers','','gb28181/zlm/workbench/LegacyMediaRoute','RTP 服务',0,0,0,0,0,'',0,'','lucide:Waypoints',80,2,0,'',0,NOW(),NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_menu` WHERE `id`=140409);
INSERT INTO `sys_menu` (`id`,`parent_id`,`path`,`name`,`redirect`,`component`,`title`,`is_full`,`hide`,`disable`,`keep_alive`,`affix`,`link`,`iframe`,`svg_icon`,`icon`,`sort`,`type`,`is_link`,`permission`,`created_by`,`created_at`,`updated_at`) SELECT 140410,140355,'/gb28181/zlm/config','gb28181-zlm-config','','gb28181/zlm/workbench/LegacyMediaRoute','服务器配置',0,0,0,0,0,'',0,'','lucide:Settings2',90,2,0,'',0,NOW(),NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_menu` WHERE `id`=140410);
INSERT INTO `sys_menu` (`id`,`parent_id`,`path`,`name`,`redirect`,`component`,`title`,`is_full`,`hide`,`disable`,`keep_alive`,`affix`,`link`,`iframe`,`svg_icon`,`icon`,`sort`,`type`,`is_link`,`permission`,`created_by`,`created_at`,`updated_at`) SELECT 140429,140355,'/media/recordings','media-recordings','','gb28181/zlm/workbench/LegacyMediaRoute','录制中心',0,0,0,1,0,'',0,'','lucide:Cloud',40,2,0,'',0,NOW(),NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `sys_menu` WHERE `id`=140429);
INSERT IGNORE INTO `sys_role_menu` (`role_id`,`menu_id`) SELECT 1,m.`id` FROM `sys_menu` m WHERE m.`id` IN (140351,140352,140353,140354,140403,140404,140405,140406,140407,140408,140409,140410,140429);
INSERT IGNORE INTO `sys_menu_api` (`menu_id`,`api_id`) SELECT m.`id`,a.`id` FROM `sys_menu` m JOIN `sys_api` a ON a.`path` LIKE '/api/gb28181/zlm/%' AND a.`method`='GET' WHERE (m.`path`='/gb28181/zlm/overview' AND a.`path` IN ('/api/gb28181/zlm/overview','/api/gb28181/zlm/nodes','/api/gb28181/zlm/nodes/:id/runtime')) OR (m.`path`='/gb28181/zlm/nodes' AND a.`path` IN ('/api/gb28181/zlm/nodes','/api/gb28181/zlm/nodes/:id','/api/gb28181/zlm/nodes/:id/config')) OR (m.`path`='/gb28181/zlm/runtime' AND a.`path` IN ('/api/gb28181/zlm/nodes','/api/gb28181/zlm/nodes/:id/runtime')) OR (m.`path`='/gb28181/zlm/streams' AND a.`path` IN ('/api/gb28181/zlm/nodes','/api/gb28181/zlm/streams','/api/gb28181/zlm/nodes/:id/streams','/api/gb28181/zlm/nodes/:id/streams/detail','/api/gb28181/zlm/nodes/:id/streams/viewers')) OR (m.`path`='/gb28181/zlm/sessions' AND a.`path` IN ('/api/gb28181/zlm/nodes','/api/gb28181/zlm/nodes/:id/sessions/network','/api/gb28181/zlm/nodes/:id/sessions/viewers')) OR (m.`path`='/gb28181/zlm/proxies' AND a.`path` IN ('/api/gb28181/zlm/nodes','/api/gb28181/zlm/nodes/:id/proxies/pull','/api/gb28181/zlm/nodes/:id/proxies/pull/:key','/api/gb28181/zlm/nodes/:id/proxies/push','/api/gb28181/zlm/nodes/:id/proxies/push/:key')) OR (m.`path`='/gb28181/zlm/ffmpeg-sources' AND a.`path` IN ('/api/gb28181/zlm/nodes','/api/gb28181/zlm/nodes/:id/ffmpeg-sources')) OR (m.`path`='/gb28181/zlm/rtp-servers' AND a.`path` IN ('/api/gb28181/zlm/nodes','/api/gb28181/zlm/nodes/:id/rtp-servers')) OR (m.`path`='/gb28181/zlm/config' AND a.`path` IN ('/api/gb28181/zlm/nodes','/api/gb28181/zlm/nodes/:id/config')) OR (m.`path`='/gb28181/zlm/scheduler' AND a.`path`='/api/gb28181/zlm/scheduler') OR (m.`path`='/gb28181/zlm/scheduler/logs' AND a.`path` IN ('/api/gb28181/zlm/nodes','/api/gb28181/zlm/scheduler/logs'));
UPDATE `sys_menu` SET `parent_id`=140355,`path`='/gb28181/realtime-log',`sort`=6,`updated_at`=NOW() WHERE `path`='/system/realtime-log' AND `deleted_at` IS NULL;
-- retire-legacy-media-menus:down:end
