CREATE TABLE IF NOT EXISTS gb_sip_trace_session_diagnosis (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    session_day DATE NOT NULL,
    observed_at DATETIME(6) NOT NULL,
    correlation_key VARCHAR(128) NOT NULL,
    state VARCHAR(16) NOT NULL DEFAULT 'active',
    category VARCHAR(32) NOT NULL,
    code VARCHAR(64) NOT NULL,
    stage VARCHAR(32) NOT NULL,
    source VARCHAR(32) NOT NULL,
    device_id VARCHAR(64) NOT NULL DEFAULT '',
    channel_id VARCHAR(64) NOT NULL DEFAULT '',
    call_id VARCHAR(255) NOT NULL DEFAULT '',
    cseq INT UNSIGNED NOT NULL DEFAULT 0,
    method VARCHAR(32) NOT NULL DEFAULT '',
    status_code SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    stream_id VARCHAR(255) NOT NULL DEFAULT '',
    resolved_at DATETIME(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_sip_trace_diagnosis_session (session_day, category, correlation_key),
    KEY idx_sip_trace_diagnosis_category_state_observed (session_day, category, state, observed_at),
    KEY idx_sip_trace_diagnosis_device_observed (device_id, observed_at),
    KEY idx_sip_trace_diagnosis_call_cseq (call_id, cseq)
) ENGINE=InnoDB;
