-- guest-readonly:start

-- Generated from guest-permissions.json. Configure guest only; keep other roles and user assignments.

INSERT INTO sys_menu(parent_id,path,name,component,title,hide,disable,sort,type,permission,icon,created_at,updated_at,created_by) SELECT m.id,'','Permission_gb28181_play_share','','复制或分享播放地址',1,0,100,3,'gb28181:play:share','',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1 FROM sys_menu m WHERE m.path='/gb28181/multi-screen-playback' AND m.type=2 AND m.deleted_at IS NULL AND NOT EXISTS(SELECT 1 FROM sys_menu x WHERE x.permission='gb28181:play:share' AND x.deleted_at IS NULL);

INSERT INTO sys_menu(parent_id,path,name,component,title,hide,disable,sort,type,permission,icon,created_at,updated_at,created_by) SELECT m.id,'','Permission_gb28181_play_snapshot','','播放器本地图像截图',1,0,100,3,'gb28181:play:snapshot','',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1 FROM sys_menu m WHERE m.path='/gb28181/multi-screen-playback' AND m.type=2 AND m.deleted_at IS NULL AND NOT EXISTS(SELECT 1 FROM sys_menu x WHERE x.permission='gb28181:play:snapshot' AND x.deleted_at IS NULL);

INSERT INTO sys_api(title,path,method,api_group,created_at,updated_at,created_by) SELECT '视频探针诊断','/api/gb28181/stream-probes/:streamId','POST','按钮权限目录',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1 WHERE NOT EXISTS(SELECT 1 FROM sys_api WHERE path='/api/gb28181/stream-probes/:streamId' AND method='POST' AND deleted_at IS NULL);

INSERT INTO sys_menu_api(menu_id,api_id) SELECT DISTINCT ma.menu_id,n.id FROM sys_menu_api ma JOIN sys_api o ON o.id=ma.api_id CROSS JOIN sys_api n WHERE o.path='/api/gb28181/play/:deviceId/probe' AND o.method='POST' AND n.path='/api/gb28181/stream-probes/:streamId' AND n.method='POST' AND n.deleted_at IS NULL AND NOT EXISTS(SELECT 1 FROM sys_menu_api x WHERE x.menu_id=ma.menu_id AND x.api_id=n.id);

DELETE FROM sys_menu_api WHERE api_id IN(SELECT id FROM sys_api WHERE path='/api/gb28181/play/:deviceId/probe' AND method='POST');

UPDATE sys_api SET deleted_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE path='/api/gb28181/play/:deviceId/probe' AND method='POST' AND deleted_at IS NULL;

INSERT INTO sys_casbin_rule(ptype,v0,v1,v2,v3,v4,v5) SELECT DISTINCT p.ptype,p.v0,'/api/gb28181/stream-probes/:streamId',p.v2,p.v3,p.v4,p.v5 FROM (SELECT DISTINCT ptype,v0,v2,v3,v4,v5 FROM sys_casbin_rule WHERE ptype='p' AND v1='/api/gb28181/play/:deviceId/probe' AND v2='POST') p WHERE NOT EXISTS(SELECT 1 FROM sys_casbin_rule n WHERE n.ptype=p.ptype AND n.v0=p.v0 AND n.v1='/api/gb28181/stream-probes/:streamId' AND n.v2=p.v2 AND n.v3=p.v3);

DELETE FROM sys_casbin_rule WHERE ptype='p' AND v1='/api/gb28181/play/:deviceId/probe' AND v2='POST';

INSERT INTO sys_role_menu(role_id,menu_id) SELECT DISTINCT r.role_id,d.id FROM sys_role_menu r JOIN sys_menu v ON v.id=r.menu_id CROSS JOIN sys_menu d JOIN sys_role sr ON sr.id=r.role_id WHERE v.permission='gb28181:recording:view' AND v.deleted_at IS NULL AND d.permission='gb28181:recording:download' AND d.deleted_at IS NULL AND sr.name<>'游客' AND EXISTS(SELECT 1 FROM sys_menu_api ma JOIN sys_api a ON a.id=ma.api_id WHERE ma.menu_id=v.id AND a.path='/api/gb28181/cloud-recordings/files/:id/downloads') AND NOT EXISTS(SELECT 1 FROM sys_role_menu x WHERE x.role_id=r.role_id AND x.menu_id=d.id);

DELETE FROM sys_menu_api WHERE menu_id IN(SELECT id FROM sys_menu WHERE permission='gb28181:recording:view') AND api_id IN(SELECT id FROM sys_api WHERE (path='/api/gb28181/cloud-recordings/files/:id/downloads' AND method='POST') OR (path='/api/gb28181/cloud-recordings/downloads/:taskId' AND method IN('GET','DELETE')));

INSERT INTO sys_api(title,path,method,api_group,created_at,updated_at,created_by) SELECT '查看与观看依赖','/api/users/profile','GET','游客权限依赖',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1 WHERE NOT EXISTS(SELECT 1 FROM sys_api WHERE path='/api/users/profile' AND method='GET' AND deleted_at IS NULL);

INSERT INTO sys_menu_api(menu_id,api_id) SELECT m.id,a.id FROM sys_menu m CROSS JOIN sys_api a WHERE m.path='/home' AND m.type=2 AND m.deleted_at IS NULL AND a.path='/api/users/profile' AND a.method='GET' AND a.deleted_at IS NULL AND NOT EXISTS(SELECT 1 FROM sys_menu_api x WHERE x.menu_id=m.id AND x.api_id=a.id);

INSERT INTO sys_api(title,path,method,api_group,created_at,updated_at,created_by) SELECT '查看与观看依赖','/api/sysMenu/getRouters','GET','游客权限依赖',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1 WHERE NOT EXISTS(SELECT 1 FROM sys_api WHERE path='/api/sysMenu/getRouters' AND method='GET' AND deleted_at IS NULL);

INSERT INTO sys_menu_api(menu_id,api_id) SELECT m.id,a.id FROM sys_menu m CROSS JOIN sys_api a WHERE m.path='/home' AND m.type=2 AND m.deleted_at IS NULL AND a.path='/api/sysMenu/getRouters' AND a.method='GET' AND a.deleted_at IS NULL AND NOT EXISTS(SELECT 1 FROM sys_menu_api x WHERE x.menu_id=m.id AND x.api_id=a.id);

INSERT INTO sys_api(title,path,method,api_group,created_at,updated_at,created_by) SELECT '查看与观看依赖','/api/users/logout','POST','游客权限依赖',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1 WHERE NOT EXISTS(SELECT 1 FROM sys_api WHERE path='/api/users/logout' AND method='POST' AND deleted_at IS NULL);

INSERT INTO sys_menu_api(menu_id,api_id) SELECT m.id,a.id FROM sys_menu m CROSS JOIN sys_api a WHERE m.path='/home' AND m.type=2 AND m.deleted_at IS NULL AND a.path='/api/users/logout' AND a.method='POST' AND a.deleted_at IS NULL AND NOT EXISTS(SELECT 1 FROM sys_menu_api x WHERE x.menu_id=m.id AND x.api_id=a.id);

INSERT INTO sys_api(title,path,method,api_group,created_at,updated_at,created_by) SELECT '查看与观看依赖','/api/gb28181/sip/dashboard/snapshot','GET','游客权限依赖',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1 WHERE NOT EXISTS(SELECT 1 FROM sys_api WHERE path='/api/gb28181/sip/dashboard/snapshot' AND method='GET' AND deleted_at IS NULL);

INSERT INTO sys_menu_api(menu_id,api_id) SELECT m.id,a.id FROM sys_menu m CROSS JOIN sys_api a WHERE m.permission='gb28181:home:view' AND m.type=3 AND m.deleted_at IS NULL AND a.path='/api/gb28181/sip/dashboard/snapshot' AND a.method='GET' AND a.deleted_at IS NULL AND NOT EXISTS(SELECT 1 FROM sys_menu_api x WHERE x.menu_id=m.id AND x.api_id=a.id);

INSERT INTO sys_api(title,path,method,api_group,created_at,updated_at,created_by) SELECT '查看与观看依赖','/api/gb28181/zlm/overview','GET','游客权限依赖',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1 WHERE NOT EXISTS(SELECT 1 FROM sys_api WHERE path='/api/gb28181/zlm/overview' AND method='GET' AND deleted_at IS NULL);

INSERT INTO sys_menu_api(menu_id,api_id) SELECT m.id,a.id FROM sys_menu m CROSS JOIN sys_api a WHERE m.permission='gb28181:home:view' AND m.type=3 AND m.deleted_at IS NULL AND a.path='/api/gb28181/zlm/overview' AND a.method='GET' AND a.deleted_at IS NULL AND NOT EXISTS(SELECT 1 FROM sys_menu_api x WHERE x.menu_id=m.id AND x.api_id=a.id);

INSERT INTO sys_api(title,path,method,api_group,created_at,updated_at,created_by) SELECT '查看与观看依赖','/api/gb28181/sip/service-config/default-playback-protocol','GET','游客权限依赖',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1 WHERE NOT EXISTS(SELECT 1 FROM sys_api WHERE path='/api/gb28181/sip/service-config/default-playback-protocol' AND method='GET' AND deleted_at IS NULL);

INSERT INTO sys_menu_api(menu_id,api_id) SELECT m.id,a.id FROM sys_menu m CROSS JOIN sys_api a WHERE m.permission='gb28181:play:start' AND m.type=3 AND m.deleted_at IS NULL AND a.path='/api/gb28181/sip/service-config/default-playback-protocol' AND a.method='GET' AND a.deleted_at IS NULL AND NOT EXISTS(SELECT 1 FROM sys_menu_api x WHERE x.menu_id=m.id AND x.api_id=a.id);

INSERT INTO sys_api(title,path,method,api_group,created_at,updated_at,created_by) SELECT '查看与观看依赖','/api/gb28181/sip/service-config/playback-settings','GET','游客权限依赖',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1 WHERE NOT EXISTS(SELECT 1 FROM sys_api WHERE path='/api/gb28181/sip/service-config/playback-settings' AND method='GET' AND deleted_at IS NULL);

INSERT INTO sys_menu_api(menu_id,api_id) SELECT m.id,a.id FROM sys_menu m CROSS JOIN sys_api a WHERE m.permission='gb28181:play:start' AND m.type=3 AND m.deleted_at IS NULL AND a.path='/api/gb28181/sip/service-config/playback-settings' AND a.method='GET' AND a.deleted_at IS NULL AND NOT EXISTS(SELECT 1 FROM sys_menu_api x WHERE x.menu_id=m.id AND x.api_id=a.id);

INSERT INTO sys_api(title,path,method,api_group,created_at,updated_at,created_by) SELECT '查看与观看依赖','/api/gb28181/sip/service-config/fixed-address-playback','GET','游客权限依赖',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1 WHERE NOT EXISTS(SELECT 1 FROM sys_api WHERE path='/api/gb28181/sip/service-config/fixed-address-playback' AND method='GET' AND deleted_at IS NULL);

INSERT INTO sys_menu_api(menu_id,api_id) SELECT m.id,a.id FROM sys_menu m CROSS JOIN sys_api a WHERE m.permission='gb28181:play:start' AND m.type=3 AND m.deleted_at IS NULL AND a.path='/api/gb28181/sip/service-config/fixed-address-playback' AND a.method='GET' AND a.deleted_at IS NULL AND NOT EXISTS(SELECT 1 FROM sys_menu_api x WHERE x.menu_id=m.id AND x.api_id=a.id);

INSERT INTO sys_role(name,sort,status,description,parent_id,data_scope,checked_depts,created_at,updated_at,created_by) SELECT '游客',100,1,'只读游客：允许业务查看、实时观看和录像回放；禁止下载、控制与修改',0,4,'',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1 WHERE NOT EXISTS(SELECT 1 FROM sys_role WHERE name='游客' AND deleted_at IS NULL);

UPDATE sys_role SET description='只读游客：允许业务查看、实时观看和录像回放；禁止下载、控制与修改',parent_id=0,status=1,updated_at=CURRENT_TIMESTAMP WHERE name='游客' AND deleted_at IS NULL AND (COALESCE(description,'')<>'只读游客：允许业务查看、实时观看和录像回放；禁止下载、控制与修改' OR parent_id<>0 OR status<>1);

DELETE FROM sys_role_menu WHERE role_id=(SELECT MIN(id) FROM sys_role WHERE name='游客' AND deleted_at IS NULL) AND menu_id NOT IN(SELECT m.id FROM sys_menu m WHERE m.deleted_at IS NULL AND m.disable=0 AND ((m.type=2 AND m.path IN ('/home','/gb28181/device-mgmt/index','/gb28181/multi-screen-playback','/gb28181/device-record-playback/:channelId','/gb28181/cloud-recordings','/gb28181/alarm-management')) OR (m.type=3 AND m.permission IN ('gb28181:home:view','gb28181:device:view','gb28181:play:start','gb28181:play:monitor','gb28181:device-record:query','gb28181:device-record:play'))));

INSERT INTO sys_role_menu(role_id,menu_id) SELECT (SELECT MIN(id) FROM sys_role WHERE name='游客' AND deleted_at IS NULL),m.id FROM sys_menu m WHERE m.deleted_at IS NULL AND m.disable=0 AND ((m.type=2 AND m.path IN ('/home','/gb28181/device-mgmt/index','/gb28181/multi-screen-playback','/gb28181/device-record-playback/:channelId','/gb28181/cloud-recordings','/gb28181/alarm-management')) OR (m.type=3 AND m.permission IN ('gb28181:home:view','gb28181:device:view','gb28181:play:start','gb28181:play:monitor','gb28181:device-record:query','gb28181:device-record:play'))) AND NOT EXISTS(SELECT 1 FROM sys_role_menu x WHERE x.role_id=(SELECT MIN(id) FROM sys_role WHERE name='游客' AND deleted_at IS NULL) AND x.menu_id=m.id);

DELETE FROM sys_casbin_rule WHERE v0=CONCAT('role_',(SELECT MIN(id) FROM sys_role WHERE name='游客' AND deleted_at IS NULL)) AND ((ptype='p' AND (v3<>'*' OR NOT ((v1='/api/gb28181/device-mgmt/channel/:id/playback-sessions/:sessionId' AND v2='DELETE') OR (v1='/api/gb28181/alarms' AND v2='GET') OR (v1='/api/gb28181/alarms/:id' AND v2='GET') OR (v1='/api/gb28181/cloud-recordings/active' AND v2='GET') OR (v1='/api/gb28181/cloud-recordings/files' AND v2='GET') OR (v1='/api/gb28181/cloud-recordings/files/:id' AND v2='GET') OR (v1='/api/gb28181/cloud-recordings/files/options' AND v2='GET') OR (v1='/api/gb28181/device-mgmt/catalog/tree' AND v2='GET') OR (v1='/api/gb28181/device-mgmt/catalog/tree/:id' AND v2='GET') OR (v1='/api/gb28181/device-mgmt/catalog/tree/:id/children' AND v2='GET') OR (v1='/api/gb28181/device-mgmt/channel/:id' AND v2='GET') OR (v1='/api/gb28181/device-mgmt/channel/:id/mounts' AND v2='GET') OR (v1='/api/gb28181/device-mgmt/channel/:id/playback-sessions/:sessionId' AND v2='GET') OR (v1='/api/gb28181/device-mgmt/channel/:id/record-query/options' AND v2='GET') OR (v1='/api/gb28181/device-mgmt/channel/:id/timeline' AND v2='GET') OR (v1='/api/gb28181/device-mgmt/channels' AND v2='GET') OR (v1='/api/gb28181/device-mgmt/device/:id' AND v2='GET') OR (v1='/api/gb28181/device-mgmt/device/:id/status-events' AND v2='GET') OR (v1='/api/gb28181/device-mgmt/devices' AND v2='GET') OR (v1='/api/gb28181/device-mgmt/directory/tree' AND v2='GET') OR (v1='/api/gb28181/device-mgmt/map/clusters' AND v2='GET') OR (v1='/api/gb28181/device-mgmt/map/markers' AND v2='GET') OR (v1='/api/gb28181/home/drilldown/play' AND v2='GET') OR (v1='/api/gb28181/home/drilldown/sip' AND v2='GET') OR (v1='/api/gb28181/home/drilldown/traffic' AND v2='GET') OR (v1='/api/gb28181/home/layout' AND v2='GET') OR (v1='/api/gb28181/home/summary' AND v2='GET') OR (v1='/api/gb28181/play/:streamId/monitor' AND v2='GET') OR (v1='/api/gb28181/sip/dashboard/snapshot' AND v2='GET') OR (v1='/api/gb28181/sip/service-config/default-playback-protocol' AND v2='GET') OR (v1='/api/gb28181/sip/service-config/fixed-address-playback' AND v2='GET') OR (v1='/api/gb28181/sip/service-config/playback-settings' AND v2='GET') OR (v1='/api/gb28181/zlm/nodes' AND v2='GET') OR (v1='/api/gb28181/zlm/nodes/:id/recordings/runtime/status' AND v2='GET') OR (v1='/api/gb28181/zlm/overview' AND v2='GET') OR (v1='/api/sysMenu/getRouters' AND v2='GET') OR (v1='/api/users/profile' AND v2='GET') OR (v1='/api/gb28181/cloud-recordings/files/:id/access' AND v2='POST') OR (v1='/api/gb28181/device-mgmt/channel/:id/playback-sessions' AND v2='POST') OR (v1='/api/gb28181/device-mgmt/channel/:id/playback-sessions/:sessionId/actions' AND v2='POST') OR (v1='/api/gb28181/device-mgmt/channel/:id/record-query' AND v2='POST') OR (v1='/api/gb28181/play/:deviceId/:channelId' AND v2='POST') OR (v1='/api/gb28181/play/:deviceId/:channelId/authorization' AND v2='POST') OR (v1='/api/users/logout' AND v2='POST')))) OR ptype='g');

INSERT INTO sys_casbin_rule(ptype,v0,v1,v2,v3,v4,v5) SELECT DISTINCT 'p',CONCAT('role_',(SELECT MIN(id) FROM sys_role WHERE name='游客' AND deleted_at IS NULL)),a.path,a.method,'*','','' FROM sys_role_menu rm JOIN sys_menu m ON m.id=rm.menu_id JOIN sys_menu_api ma ON ma.menu_id=m.id JOIN sys_api a ON a.id=ma.api_id WHERE rm.role_id=(SELECT MIN(id) FROM sys_role WHERE name='游客' AND deleted_at IS NULL) AND m.deleted_at IS NULL AND a.deleted_at IS NULL AND NOT EXISTS(SELECT 1 FROM sys_casbin_rule p WHERE p.ptype='p' AND p.v0=CONCAT('role_',(SELECT MIN(id) FROM sys_role WHERE name='游客' AND deleted_at IS NULL)) AND p.v1=a.path AND p.v2=a.method AND p.v3='*');
-- guest-readonly:end
