-- retire-legacy-media-menus:down:start
-- 回滚:恢复 13 条兼容跳转壳菜单行、角色绑定与原始读接口归属,并把实时日志控制台移回流媒体管理(PostgreSQL)。
-- 注意:前端兼容层(LegacyMediaRoute.vue / mediaRoutes.ts)与 RecordingCenter.vue 已随本次清理删除,
-- 回滚后需从 git 历史恢复这些文件,跳转壳菜单才可正常打开。
-- 读接口归属按「菜单 path + 接口 path」恢复:api_id 为自增列,跨库会漂移,不能硬编码。
DELETE FROM sys_menu_api ma USING sys_menu m, sys_api a WHERE m.id=ma.menu_id AND a.id=ma.api_id AND m.path IN ('/media/overview','/media/monitoring','/media/ingress','/media/nodes','/media/scheduling') AND a.path LIKE '/api/gb28181/zlm/%';
INSERT INTO sys_menu (id,parent_id,path,name,redirect,component,title,is_full,hide,disable,keep_alive,affix,link,iframe,svg_icon,icon,sort,type,is_link,permission,created_by,created_at,updated_at) SELECT 140351,140355,'/gb28181/zlm/nodes','gb28181-zlm-nodes','','gb28181/zlm/workbench/LegacyMediaRoute','节点管理',false,false,false,false,false,'',false,'','lucide:Server',20,2,false,'',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE id=140351);
INSERT INTO sys_menu (id,parent_id,path,name,redirect,component,title,is_full,hide,disable,keep_alive,affix,link,iframe,svg_icon,icon,sort,type,is_link,permission,created_by,created_at,updated_at) SELECT 140352,0,'/gb28181/zlm/nodes/:id','gb28181-zlm-node-detail','','gb28181/zlm/workbench/LegacyMediaRoute','节点详情',false,false,false,false,false,'',false,'','lucide:Server',6,2,false,'',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE id=140352);
INSERT INTO sys_menu (id,parent_id,path,name,redirect,component,title,is_full,hide,disable,keep_alive,affix,link,iframe,svg_icon,icon,sort,type,is_link,permission,created_by,created_at,updated_at) SELECT 140353,140355,'/gb28181/zlm/scheduler','gb28181-zlm-scheduler-strategy','','gb28181/zlm/workbench/LegacyMediaRoute','调度策略',false,false,false,false,false,'',false,'','lucide:Workflow',100,2,false,'',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE id=140353);
INSERT INTO sys_menu (id,parent_id,path,name,redirect,component,title,is_full,hide,disable,keep_alive,affix,link,iframe,svg_icon,icon,sort,type,is_link,permission,created_by,created_at,updated_at) SELECT 140354,140355,'/gb28181/zlm/scheduler/logs','gb28181-zlm-scheduler-log','','gb28181/zlm/workbench/LegacyMediaRoute','调度日志',false,false,false,false,false,'',false,'','lucide:History',110,2,false,'',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE id=140354);
INSERT INTO sys_menu (id,parent_id,path,name,redirect,component,title,is_full,hide,disable,keep_alive,affix,link,iframe,svg_icon,icon,sort,type,is_link,permission,created_by,created_at,updated_at) SELECT 140403,140355,'/gb28181/zlm/overview','gb28181-zlm-overview','','gb28181/zlm/workbench/LegacyMediaRoute','总览',false,false,false,false,false,'',false,'','lucide:LayoutDashboard',10,2,false,'',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE id=140403);
INSERT INTO sys_menu (id,parent_id,path,name,redirect,component,title,is_full,hide,disable,keep_alive,affix,link,iframe,svg_icon,icon,sort,type,is_link,permission,created_by,created_at,updated_at) SELECT 140404,140355,'/gb28181/zlm/runtime','gb28181-zlm-runtime','','gb28181/zlm/workbench/LegacyMediaRoute','总览',false,false,false,false,false,'',false,'','lucide:Gauge',30,2,false,'',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE id=140404);
INSERT INTO sys_menu (id,parent_id,path,name,redirect,component,title,is_full,hide,disable,keep_alive,affix,link,iframe,svg_icon,icon,sort,type,is_link,permission,created_by,created_at,updated_at) SELECT 140405,140355,'/gb28181/zlm/streams','gb28181-zlm-streams','','gb28181/zlm/workbench/LegacyMediaRoute','流管理',false,false,false,false,false,'',false,'','lucide:RadioTower',40,2,false,'',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE id=140405);
INSERT INTO sys_menu (id,parent_id,path,name,redirect,component,title,is_full,hide,disable,keep_alive,affix,link,iframe,svg_icon,icon,sort,type,is_link,permission,created_by,created_at,updated_at) SELECT 140406,140355,'/gb28181/zlm/sessions','gb28181-zlm-sessions','','gb28181/zlm/workbench/LegacyMediaRoute','会话管理',false,false,false,false,false,'',false,'','lucide:Users',50,2,false,'',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE id=140406);
INSERT INTO sys_menu (id,parent_id,path,name,redirect,component,title,is_full,hide,disable,keep_alive,affix,link,iframe,svg_icon,icon,sort,type,is_link,permission,created_by,created_at,updated_at) SELECT 140407,140355,'/gb28181/zlm/proxies','gb28181-zlm-proxies','','gb28181/zlm/workbench/LegacyMediaRoute','拉流/推流代理',false,false,false,false,false,'',false,'','lucide:Network',60,2,false,'',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE id=140407);
INSERT INTO sys_menu (id,parent_id,path,name,redirect,component,title,is_full,hide,disable,keep_alive,affix,link,iframe,svg_icon,icon,sort,type,is_link,permission,created_by,created_at,updated_at) SELECT 140408,140355,'/gb28181/zlm/ffmpeg-sources','gb28181-zlm-ffmpeg-sources','','gb28181/zlm/workbench/LegacyMediaRoute','FFmpeg 源',false,false,false,false,false,'',false,'','lucide:Clapperboard',70,2,false,'',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE id=140408);
INSERT INTO sys_menu (id,parent_id,path,name,redirect,component,title,is_full,hide,disable,keep_alive,affix,link,iframe,svg_icon,icon,sort,type,is_link,permission,created_by,created_at,updated_at) SELECT 140409,140355,'/gb28181/zlm/rtp-servers','gb28181-zlm-rtp-servers','','gb28181/zlm/workbench/LegacyMediaRoute','RTP 服务',false,false,false,false,false,'',false,'','lucide:Waypoints',80,2,false,'',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE id=140409);
INSERT INTO sys_menu (id,parent_id,path,name,redirect,component,title,is_full,hide,disable,keep_alive,affix,link,iframe,svg_icon,icon,sort,type,is_link,permission,created_by,created_at,updated_at) SELECT 140410,140355,'/gb28181/zlm/config','gb28181-zlm-config','','gb28181/zlm/workbench/LegacyMediaRoute','服务器配置',false,false,false,false,false,'',false,'','lucide:Settings2',90,2,false,'',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE id=140410);
INSERT INTO sys_menu (id,parent_id,path,name,redirect,component,title,is_full,hide,disable,keep_alive,affix,link,iframe,svg_icon,icon,sort,type,is_link,permission,created_by,created_at,updated_at) SELECT 140429,140355,'/media/recordings','media-recordings','','gb28181/zlm/workbench/LegacyMediaRoute','录制中心',false,false,false,true,false,'',false,'','lucide:Cloud',40,2,false,'',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE id=140429);
INSERT INTO sys_role_menu (role_id,menu_id) SELECT 1,m.id FROM sys_menu m WHERE m.id IN (140351,140352,140353,140354,140403,140404,140405,140406,140407,140408,140409,140410,140429) ON CONFLICT DO NOTHING;
INSERT INTO sys_menu_api (menu_id,api_id) SELECT m.id,a.id FROM sys_menu m JOIN sys_api a ON a.path LIKE '/api/gb28181/zlm/%' AND a.method='GET' WHERE (m.path='/gb28181/zlm/overview' AND a.path IN ('/api/gb28181/zlm/overview','/api/gb28181/zlm/nodes','/api/gb28181/zlm/nodes/:id/runtime')) OR (m.path='/gb28181/zlm/nodes' AND a.path IN ('/api/gb28181/zlm/nodes','/api/gb28181/zlm/nodes/:id','/api/gb28181/zlm/nodes/:id/config')) OR (m.path='/gb28181/zlm/runtime' AND a.path IN ('/api/gb28181/zlm/nodes','/api/gb28181/zlm/nodes/:id/runtime')) OR (m.path='/gb28181/zlm/streams' AND a.path IN ('/api/gb28181/zlm/nodes','/api/gb28181/zlm/streams','/api/gb28181/zlm/nodes/:id/streams','/api/gb28181/zlm/nodes/:id/streams/detail','/api/gb28181/zlm/nodes/:id/streams/viewers')) OR (m.path='/gb28181/zlm/sessions' AND a.path IN ('/api/gb28181/zlm/nodes','/api/gb28181/zlm/nodes/:id/sessions/network','/api/gb28181/zlm/nodes/:id/sessions/viewers')) OR (m.path='/gb28181/zlm/proxies' AND a.path IN ('/api/gb28181/zlm/nodes','/api/gb28181/zlm/nodes/:id/proxies/pull','/api/gb28181/zlm/nodes/:id/proxies/pull/:key','/api/gb28181/zlm/nodes/:id/proxies/push','/api/gb28181/zlm/nodes/:id/proxies/push/:key')) OR (m.path='/gb28181/zlm/ffmpeg-sources' AND a.path IN ('/api/gb28181/zlm/nodes','/api/gb28181/zlm/nodes/:id/ffmpeg-sources')) OR (m.path='/gb28181/zlm/rtp-servers' AND a.path IN ('/api/gb28181/zlm/nodes','/api/gb28181/zlm/nodes/:id/rtp-servers')) OR (m.path='/gb28181/zlm/config' AND a.path IN ('/api/gb28181/zlm/nodes','/api/gb28181/zlm/nodes/:id/config')) OR (m.path='/gb28181/zlm/scheduler' AND a.path='/api/gb28181/zlm/scheduler') OR (m.path='/gb28181/zlm/scheduler/logs' AND a.path IN ('/api/gb28181/zlm/nodes','/api/gb28181/zlm/scheduler/logs')) ON CONFLICT DO NOTHING;
UPDATE sys_menu SET parent_id=140355, path='/gb28181/realtime-log', sort=6, updated_at=CURRENT_TIMESTAMP WHERE path='/system/realtime-log' AND deleted_at IS NULL;
-- retire-legacy-media-menus:down:end
