CREATE TABLE `gb_talk_session` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `session_id` varchar(64) NOT NULL,
  `channel_id` int unsigned NOT NULL,
  `device_id` varchar(20) NOT NULL,
  `actor_id` bigint unsigned NOT NULL DEFAULT '0',
  `actor_dept_id` bigint unsigned NOT NULL DEFAULT '0',
  `node_id` bigint NOT NULL DEFAULT '0',
  `app` varchar(64) NOT NULL DEFAULT 'talk',
  `source_stream` varchar(128) NOT NULL,
  `recv_stream` varchar(128) NOT NULL DEFAULT '',
  `ssrc` varchar(32) NOT NULL DEFAULT '',
  `state` varchar(20) NOT NULL,
  `lease_key` int unsigned DEFAULT NULL,
  `source_key` varchar(128) DEFAULT NULL,
  `recv_key` varchar(128) DEFAULT NULL,
  `ssrc_key` varchar(32) DEFAULT NULL,
  `expires_at` datetime NOT NULL,
  `publish_token_hash` char(64) NOT NULL,
  `token_consumed_at` datetime DEFAULT NULL,
  `publish_id` varchar(255) NOT NULL DEFAULT '',
  `local_port` int NOT NULL DEFAULT '0',
  `call_id` varchar(255) NOT NULL DEFAULT '',
  `dialog_local_tag` varchar(128) NOT NULL DEFAULT '',
  `dialog_remote_tag` varchar(128) NOT NULL DEFAULT '',
  `dialog_remote_uri` varchar(512) NOT NULL DEFAULT '',
  `dialog_cseq` int unsigned NOT NULL DEFAULT '0',
  `error` varchar(500) NOT NULL DEFAULT '',
  `started_at` datetime DEFAULT NULL,
  `ended_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_talk_session_session_id` (`session_id`),
  UNIQUE KEY `uk_talk_session_lease` (`lease_key`),
  UNIQUE KEY `uk_talk_session_source_key` (`source_key`),
  UNIQUE KEY `uk_talk_session_recv_key` (`recv_key`),
  UNIQUE KEY `uk_talk_session_ssrc_key` (`ssrc_key`),
  KEY `idx_talk_session_channel_created` (`channel_id`,`created_at`),
  KEY `idx_talk_session_state_expires` (`state`,`expires_at`),
  KEY `idx_talk_session_source` (`node_id`,`app`,`source_stream`),
  KEY `idx_talk_session_recv` (`node_id`,`recv_stream`),
  KEY `idx_talk_session_call_id` (`call_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='GB28181 语音对讲会话历史';
