-- Original PTZ authorization; historical rows deliberately remain NULL.
SET @ptz_epoch_column = (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'gb_ptz_operation' AND column_name = 'device_epoch');
SET @ptz_epoch_sql = IF(@ptz_epoch_column = 0, 'ALTER TABLE gb_ptz_operation ADD COLUMN device_epoch BIGINT NULL', 'SELECT 1');
PREPARE ptz_epoch_stmt FROM @ptz_epoch_sql;
EXECUTE ptz_epoch_stmt;
DEALLOCATE PREPARE ptz_epoch_stmt;
SET @ptz_intent_column = (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'gb_ptz_operation' AND column_name = 'device_intent_id');
SET @ptz_intent_sql = IF(@ptz_intent_column = 0, 'ALTER TABLE gb_ptz_operation ADD COLUMN device_intent_id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL', 'SELECT 1');
PREPARE ptz_intent_stmt FROM @ptz_intent_sql;
EXECUTE ptz_intent_stmt;
DEALLOCATE PREPARE ptz_intent_stmt;
SET @ptz_owner_column = (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'gb_ptz_operation_attempt' AND column_name = 'owner_process_id');
SET @ptz_owner_sql = IF(@ptz_owner_column = 0, 'ALTER TABLE gb_ptz_operation_attempt ADD COLUMN owner_process_id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL', 'SELECT 1');
PREPARE ptz_owner_stmt FROM @ptz_owner_sql;
EXECUTE ptz_owner_stmt;
DEALLOCATE PREPARE ptz_owner_stmt;
SET @ptz_owner_column = (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'gb_ptz_operation_attempt' AND column_name = 'owner_run_id');
SET @ptz_owner_sql = IF(@ptz_owner_column = 0, 'ALTER TABLE gb_ptz_operation_attempt ADD COLUMN owner_run_id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL', 'SELECT 1');
PREPARE ptz_owner_stmt FROM @ptz_owner_sql;
EXECUTE ptz_owner_stmt;
DEALLOCATE PREPARE ptz_owner_stmt;
SET @ptz_owner_column = (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'gb_ptz_operation_attempt' AND column_name = 'local_quiesced_at');
SET @ptz_owner_sql = IF(@ptz_owner_column = 0, 'ALTER TABLE gb_ptz_operation_attempt ADD COLUMN local_quiesced_at DATETIME(6) NULL', 'SELECT 1');
PREPARE ptz_owner_stmt FROM @ptz_owner_sql;
EXECUTE ptz_owner_stmt;
DEALLOCATE PREPARE ptz_owner_stmt;
SET @ptz_intent_index = (SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema = DATABASE() AND table_name = 'gb_ptz_operation' AND index_name = 'uk_ptz_device_intent');
SET @ptz_intent_index_sql = IF(@ptz_intent_index = 0, 'CREATE UNIQUE INDEX uk_ptz_device_intent ON gb_ptz_operation(device_intent_id)', 'SELECT 1');
PREPARE ptz_intent_index_stmt FROM @ptz_intent_index_sql;
EXECUTE ptz_intent_index_stmt;
DEALLOCATE PREPARE ptz_intent_index_stmt;
