-- API 分组重定口径：判定键从「按钮所在页面」改为「接口自己的路径」。
--
-- 背景：sys_api.api_group 是「接口管理」页唯一的可读组织维度。上一版按
-- **按钮所挂页面**推分组，把整片通道级设备操作算进了「多屏播放」——
-- 播放控制台是工作台页面，云台/对讲/抓拍/配置下发/视频参数/目标跟踪的按钮
-- 全摆在它上面，于是 34 个接口（含「下发目标跟踪」「下发设备配置」这种
-- 路径明明写着 device-mgmt 的）被判成「多屏播放」。
--
-- 新口径：**分组 = 接口所属的功能模块**，由接口路径前缀（最长匹配）判定；
-- 新增独立分组「设备控制」承载通道级操作。规则真源见：
--   scripts/api_groups.py 的 API_GROUP_RULES（生成器共用）
--   server/app/models/sysapigroup.go 的 sysApiGroups（受控清单）
--
-- 2026-09-21 就地修正（同一迁移内，因为它尚未交付给任何库）：
--   `stream-probes` ×2 与 `play/:streamId/monitor` ×1 原被判进「多屏播放」，
--   理由是「按钮也挂在多屏播放页」—— 与本次确立的判定键自相矛盾。
--   播放控制台是 layout 级全局宿主（`layout/components/PlaybackConsoleHost.vue`），
--   从任何页面都能唤起，「按钮在哪页」不构成模块归属。三者改归「流媒体管理」
--   （探针/监控在后端是 streamprobe / streammonitor 独立子包，与 zlm 同级 = 媒体流层）。
--
-- ⛔ 定位键是 (path, method) 而**不是 id**：各库 id 不同，path+method 才跨库稳定。
-- ⛔ casbin 会拦？不会 —— api_group 不参与鉴权（Go 侧零引用），纯展示元数据。
--
-- up  : 把分组设为路径推导值（带 `<> 目标值` 守卫，重跑无写）。
-- down: 回退到本次重定口径之前的值（上一版 30 组口径；旧值取自执行前建的
--       带内快照表 sys_api_apigroup_backup_reroute_20260921）。
--       ⛔ 无法还原到更早的 39 个自由文本分组 —— 那需要各库各自的快照。
--
-- 幂等：每条 UPDATE 都带 `<> 目标值` 守卫，连跑两遍第二遍写 0 行。

-- api-group-reroute:start
UPDATE "sys_api" SET "api_group"='认证管理' WHERE "path"='/api/login' AND "method"='POST' AND "api_group"<>'认证管理';
UPDATE "sys_api" SET "api_group"='认证管理' WHERE "path"='/api/refreshToken' AND "method"='POST' AND "api_group"<>'认证管理';
UPDATE "sys_api" SET "api_group"='认证管理' WHERE "path"='/api/captcha/id' AND "method"='GET' AND "api_group"<>'认证管理';
UPDATE "sys_api" SET "api_group"='认证管理' WHERE "path"='/api/captcha/image' AND "method"='GET' AND "api_group"<>'认证管理';
UPDATE "sys_api" SET "api_group"='认证管理' WHERE "path"='/api/users/logout' AND "method"='POST' AND "api_group"<>'认证管理';
UPDATE "sys_api" SET "api_group"='个人中心' WHERE "path"='/api/users/profile' AND "method"='GET' AND "api_group"<>'个人中心';
UPDATE "sys_api" SET "api_group"='用户管理' WHERE "path"='/api/users/:id' AND "method"='GET' AND "api_group"<>'用户管理';
UPDATE "sys_api" SET "api_group"='用户管理' WHERE "path"='/api/users/list' AND "method"='GET' AND "api_group"<>'用户管理';
UPDATE "sys_api" SET "api_group"='用户管理' WHERE "path"='/api/users/add' AND "method"='POST' AND "api_group"<>'用户管理';
UPDATE "sys_api" SET "api_group"='用户管理' WHERE "path"='/api/users/edit' AND "method"='PUT' AND "api_group"<>'用户管理';
UPDATE "sys_api" SET "api_group"='用户管理' WHERE "path"='/api/users/delete' AND "method"='DELETE' AND "api_group"<>'用户管理';
UPDATE "sys_api" SET "api_group"='菜单管理' WHERE "path"='/api/sysMenu/getRouters' AND "method"='GET' AND "api_group"<>'菜单管理';
UPDATE "sys_api" SET "api_group"='菜单管理' WHERE "path"='/api/sysMenu/getMenuList' AND "method"='GET' AND "api_group"<>'菜单管理';
UPDATE "sys_api" SET "api_group"='菜单管理' WHERE "path"='/api/sysMenu/:id' AND "method"='GET' AND "api_group"<>'菜单管理';
UPDATE "sys_api" SET "api_group"='菜单管理' WHERE "path"='/api/sysMenu/add' AND "method"='POST' AND "api_group"<>'菜单管理';
UPDATE "sys_api" SET "api_group"='菜单管理' WHERE "path"='/api/sysMenu/edit' AND "method"='PUT' AND "api_group"<>'菜单管理';
UPDATE "sys_api" SET "api_group"='菜单管理' WHERE "path"='/api/sysMenu/delete' AND "method"='DELETE' AND "api_group"<>'菜单管理';
UPDATE "sys_api" SET "api_group"='部门管理' WHERE "path"='/api/sysDepartment/getDivision' AND "method"='GET' AND "api_group"<>'部门管理';
UPDATE "sys_api" SET "api_group"='角色管理' WHERE "path"='/api/sysRole/getRoles' AND "method"='GET' AND "api_group"<>'角色管理';
UPDATE "sys_api" SET "api_group"='角色管理' WHERE "path"='/api/sysRole/getUserPermission/:roleId' AND "method"='GET' AND "api_group"<>'角色管理';
UPDATE "sys_api" SET "api_group"='角色管理' WHERE "path"='/api/sysRole/addRoleMenu' AND "method"='POST' AND "api_group"<>'角色管理';
UPDATE "sys_api" SET "api_group"='角色管理' WHERE "path"='/api/sysRole/list' AND "method"='GET' AND "api_group"<>'角色管理';
UPDATE "sys_api" SET "api_group"='角色管理' WHERE "path"='/api/sysRole/:id' AND "method"='GET' AND "api_group"<>'角色管理';
UPDATE "sys_api" SET "api_group"='角色管理' WHERE "path"='/api/sysRole/add' AND "method"='POST' AND "api_group"<>'角色管理';
UPDATE "sys_api" SET "api_group"='角色管理' WHERE "path"='/api/sysRole/edit' AND "method"='PUT' AND "api_group"<>'角色管理';
UPDATE "sys_api" SET "api_group"='角色管理' WHERE "path"='/api/sysRole/delete' AND "method"='DELETE' AND "api_group"<>'角色管理';
UPDATE "sys_api" SET "api_group"='字典管理' WHERE "path"='/api/sysDict/getAllDicts' AND "method"='GET' AND "api_group"<>'字典管理';
UPDATE "sys_api" SET "api_group"='字典管理' WHERE "path"='/api/sysDict/getByCode/:code' AND "method"='GET' AND "api_group"<>'字典管理';
UPDATE "sys_api" SET "api_group"='接口管理' WHERE "path"='/api/sysApi/list' AND "method"='GET' AND "api_group"<>'接口管理';
UPDATE "sys_api" SET "api_group"='接口管理' WHERE "path"='/api/sysApi/:id' AND "method"='GET' AND "api_group"<>'接口管理';
UPDATE "sys_api" SET "api_group"='接口管理' WHERE "path"='/api/sysApi/add' AND "method"='POST' AND "api_group"<>'接口管理';
UPDATE "sys_api" SET "api_group"='接口管理' WHERE "path"='/api/sysApi/edit' AND "method"='PUT' AND "api_group"<>'接口管理';
UPDATE "sys_api" SET "api_group"='接口管理' WHERE "path"='/api/sysApi/delete' AND "method"='DELETE' AND "api_group"<>'接口管理';
UPDATE "sys_api" SET "api_group"='菜单管理' WHERE "path"='/api/sysMenu/apis/:id' AND "method"='GET' AND "api_group"<>'菜单管理';
UPDATE "sys_api" SET "api_group"='菜单管理' WHERE "path"='/api/sysMenu/setApis' AND "method"='POST' AND "api_group"<>'菜单管理';
UPDATE "sys_api" SET "api_group"='部门管理' WHERE "path"='/api/sysDepartment/:id' AND "method"='GET' AND "api_group"<>'部门管理';
UPDATE "sys_api" SET "api_group"='部门管理' WHERE "path"='/api/sysDepartment/add' AND "method"='POST' AND "api_group"<>'部门管理';
UPDATE "sys_api" SET "api_group"='部门管理' WHERE "path"='/api/sysDepartment/edit' AND "method"='PUT' AND "api_group"<>'部门管理';
UPDATE "sys_api" SET "api_group"='部门管理' WHERE "path"='/api/sysDepartment/delete' AND "method"='DELETE' AND "api_group"<>'部门管理';
UPDATE "sys_api" SET "api_group"='字典管理' WHERE "path"='/api/sysDict/list' AND "method"='GET' AND "api_group"<>'字典管理';
UPDATE "sys_api" SET "api_group"='字典管理' WHERE "path"='/api/sysDict/:id' AND "method"='GET' AND "api_group"<>'字典管理';
UPDATE "sys_api" SET "api_group"='字典管理' WHERE "path"='/api/sysDict/add' AND "method"='POST' AND "api_group"<>'字典管理';
UPDATE "sys_api" SET "api_group"='字典管理' WHERE "path"='/api/sysDict/edit' AND "method"='PUT' AND "api_group"<>'字典管理';
UPDATE "sys_api" SET "api_group"='字典管理' WHERE "path"='/api/sysDict/delete' AND "method"='DELETE' AND "api_group"<>'字典管理';
UPDATE "sys_api" SET "api_group"='字典管理' WHERE "path"='/api/sysDictItem/list' AND "method"='GET' AND "api_group"<>'字典管理';
UPDATE "sys_api" SET "api_group"='字典管理' WHERE "path"='/api/sysDictItem/:id' AND "method"='GET' AND "api_group"<>'字典管理';
UPDATE "sys_api" SET "api_group"='字典管理' WHERE "path"='/api/sysDictItem/getByDictId/:dictId' AND "method"='GET' AND "api_group"<>'字典管理';
UPDATE "sys_api" SET "api_group"='字典管理' WHERE "path"='/api/sysDictItem/getByDictCode/:dictCode' AND "method"='GET' AND "api_group"<>'字典管理';
UPDATE "sys_api" SET "api_group"='字典管理' WHERE "path"='/api/sysDictItem/add' AND "method"='POST' AND "api_group"<>'字典管理';
UPDATE "sys_api" SET "api_group"='字典管理' WHERE "path"='/api/sysDictItem/edit' AND "method"='PUT' AND "api_group"<>'字典管理';
UPDATE "sys_api" SET "api_group"='字典管理' WHERE "path"='/api/sysDictItem/delete' AND "method"='DELETE' AND "api_group"<>'字典管理';
UPDATE "sys_api" SET "api_group"='个人中心' WHERE "path"='/api/users/updateAccount' AND "method"='PUT' AND "api_group"<>'个人中心';
UPDATE "sys_api" SET "api_group"='个人中心' WHERE "path"='/api/users/uploadAvatar' AND "method"='POST' AND "api_group"<>'个人中心';
UPDATE "sys_api" SET "api_group"='文件管理' WHERE "path"='/api/sysAffix/upload' AND "method"='POST' AND "api_group"<>'文件管理';
UPDATE "sys_api" SET "api_group"='文件管理' WHERE "path"='/api/sysAffix/delete' AND "method"='DELETE' AND "api_group"<>'文件管理';
UPDATE "sys_api" SET "api_group"='文件管理' WHERE "path"='/api/sysAffix/updateName' AND "method"='PUT' AND "api_group"<>'文件管理';
UPDATE "sys_api" SET "api_group"='文件管理' WHERE "path"='/api/sysAffix/list' AND "method"='GET' AND "api_group"<>'文件管理';
UPDATE "sys_api" SET "api_group"='文件管理' WHERE "path"='/api/sysAffix/:id' AND "method"='GET' AND "api_group"<>'文件管理';
UPDATE "sys_api" SET "api_group"='文件管理' WHERE "path"='/api/sysAffix/download/:id' AND "method"='GET' AND "api_group"<>'文件管理';
UPDATE "sys_api" SET "api_group"='角色管理' WHERE "path"='/api/sysRole/dataScope' AND "method"='PUT' AND "api_group"<>'角色管理';
UPDATE "sys_api" SET "api_group"='系统配置' WHERE "path"='/api/config/get' AND "method"='GET' AND "api_group"<>'系统配置';
UPDATE "sys_api" SET "api_group"='系统配置' WHERE "path"='/api/config/update' AND "method"='PUT' AND "api_group"<>'系统配置';
UPDATE "sys_api" SET "api_group"='系统配置' WHERE "path"='/api/config/viewCache' AND "method"='GET' AND "api_group"<>'系统配置';
UPDATE "sys_api" SET "api_group"='插件示例' WHERE "path"='/api/plugins/example/list' AND "method"='GET' AND "api_group"<>'插件示例';
UPDATE "sys_api" SET "api_group"='插件示例' WHERE "path"='/api/plugins/example/add' AND "method"='POST' AND "api_group"<>'插件示例';
UPDATE "sys_api" SET "api_group"='插件示例' WHERE "path"='/api/plugins/example/edit' AND "method"='PUT' AND "api_group"<>'插件示例';
UPDATE "sys_api" SET "api_group"='插件示例' WHERE "path"='/api/plugins/example/delete' AND "method"='DELETE' AND "api_group"<>'插件示例';
UPDATE "sys_api" SET "api_group"='插件示例' WHERE "path"='/api/plugins/example/:id' AND "method"='GET' AND "api_group"<>'插件示例';
UPDATE "sys_api" SET "api_group"='日志中心' WHERE "path"='/api/sysOperationLog/list' AND "method"='GET' AND "api_group"<>'日志中心';
UPDATE "sys_api" SET "api_group"='日志中心' WHERE "path"='/api/sysOperationLog/delete' AND "method"='DELETE' AND "api_group"<>'日志中心';
UPDATE "sys_api" SET "api_group"='日志中心' WHERE "path"='/api/sysOperationLog/export' AND "method"='GET' AND "api_group"<>'日志中心';
UPDATE "sys_api" SET "api_group"='菜单管理' WHERE "path"='/api/sysMenu/export' AND "method"='GET' AND "api_group"<>'菜单管理';
UPDATE "sys_api" SET "api_group"='菜单管理' WHERE "path"='/api/sysMenu/import' AND "method"='POST' AND "api_group"<>'菜单管理';
UPDATE "sys_api" SET "api_group"='个人中心' WHERE "path"='/api/users/updateBasicInfo' AND "method"='PUT' AND "api_group"<>'个人中心';
UPDATE "sys_api" SET "api_group"='代码生成' WHERE "path"='/api/codegen/generate' AND "method"='POST' AND "api_group"<>'代码生成';
UPDATE "sys_api" SET "api_group"='代码生成' WHERE "path"='/api/codegen/columns' AND "method"='GET' AND "api_group"<>'代码生成';
UPDATE "sys_api" SET "api_group"='代码生成' WHERE "path"='/api/codegen/databases' AND "method"='GET' AND "api_group"<>'代码生成';
UPDATE "sys_api" SET "api_group"='代码生成' WHERE "path"='/api/codegen/tables' AND "method"='GET' AND "api_group"<>'代码生成';
UPDATE "sys_api" SET "api_group"='代码生成' WHERE "path"='/api/codegen/preview' AND "method"='GET' AND "api_group"<>'代码生成';
UPDATE "sys_api" SET "api_group"='代码生成' WHERE "path"='/api/sysGen/list' AND "method"='GET' AND "api_group"<>'代码生成';
UPDATE "sys_api" SET "api_group"='代码生成' WHERE "path"='/api/sysGen/batchInsert' AND "method"='POST' AND "api_group"<>'代码生成';
UPDATE "sys_api" SET "api_group"='代码生成' WHERE "path"='/api/sysGen/:id' AND "method"='GET' AND "api_group"<>'代码生成';
UPDATE "sys_api" SET "api_group"='代码生成' WHERE "path"='/api/sysGen/update' AND "method"='PUT' AND "api_group"<>'代码生成';
UPDATE "sys_api" SET "api_group"='代码生成' WHERE "path"='/api/sysGen/:id' AND "method"='DELETE' AND "api_group"<>'代码生成';
UPDATE "sys_api" SET "api_group"='代码生成' WHERE "path"='/api/sysGen/refreshFields' AND "method"='PUT' AND "api_group"<>'代码生成';
UPDATE "sys_api" SET "api_group"='代码生成' WHERE "path"='/api/codegen/insertmenuandapi' AND "method"='POST' AND "api_group"<>'代码生成';
UPDATE "sys_api" SET "api_group"='菜单管理' WHERE "path"='/api/sysMenu/batchDelete' AND "method"='DELETE' AND "api_group"<>'菜单管理';
UPDATE "sys_api" SET "api_group"='插件管理' WHERE "path"='/api/pluginsmanager/exports' AND "method"='GET' AND "api_group"<>'插件管理';
UPDATE "sys_api" SET "api_group"='插件管理' WHERE "path"='/api/pluginsmanager/export' AND "method"='POST' AND "api_group"<>'插件管理';
UPDATE "sys_api" SET "api_group"='插件管理' WHERE "path"='/api/pluginsmanager/import' AND "method"='POST' AND "api_group"<>'插件管理';
UPDATE "sys_api" SET "api_group"='插件管理' WHERE "path"='/api/pluginsmanager/uninstall' AND "method"='DELETE' AND "api_group"<>'插件管理';
UPDATE "sys_api" SET "api_group"='用户管理' WHERE "path"='/api/users/switchTenant/:tenantld' AND "method"='GET' AND "api_group"<>'用户管理';
UPDATE "sys_api" SET "api_group"='定时任务' WHERE "path"='/api/sysJobs/list' AND "method"='GET' AND "api_group"<>'定时任务';
UPDATE "sys_api" SET "api_group"='定时任务' WHERE "path"='/api/sysJobs/executors' AND "method"='GET' AND "api_group"<>'定时任务';
UPDATE "sys_api" SET "api_group"='定时任务' WHERE "path"='/api/sysJobs/add' AND "method"='POST' AND "api_group"<>'定时任务';
UPDATE "sys_api" SET "api_group"='定时任务' WHERE "path"='/api/sysJobs/edit' AND "method"='PUT' AND "api_group"<>'定时任务';
UPDATE "sys_api" SET "api_group"='定时任务' WHERE "path"='/api/sysJobs/:id' AND "method"='GET' AND "api_group"<>'定时任务';
UPDATE "sys_api" SET "api_group"='定时任务' WHERE "path"='/api/sysJobs/setStatus' AND "method"='PUT' AND "api_group"<>'定时任务';
UPDATE "sys_api" SET "api_group"='定时任务' WHERE "path"='/api/sysJobs/delete' AND "method"='DELETE' AND "api_group"<>'定时任务';
UPDATE "sys_api" SET "api_group"='定时任务' WHERE "path"='/api/sysJobs/executeNow' AND "method"='POST' AND "api_group"<>'定时任务';
UPDATE "sys_api" SET "api_group"='日志中心' WHERE "path"='/api/sysJobResults/list' AND "method"='GET' AND "api_group"<>'日志中心';
UPDATE "sys_api" SET "api_group"='日志中心' WHERE "path"='/api/sysJobResults/delete' AND "method"='DELETE' AND "api_group"<>'日志中心';
UPDATE "sys_api" SET "api_group"='文件管理' WHERE "path"='/api/sysAffix/chunk/init' AND "method"='POST' AND "api_group"<>'文件管理';
UPDATE "sys_api" SET "api_group"='文件管理' WHERE "path"='/api/sysAffix/chunk/upload' AND "method"='POST' AND "api_group"<>'文件管理';
UPDATE "sys_api" SET "api_group"='文件管理' WHERE "path"='/api/sysAffix/chunk/merge' AND "method"='POST' AND "api_group"<>'文件管理';
UPDATE "sys_api" SET "api_group"='文件管理' WHERE "path"='/api/sysAffix/chunk/cancel' AND "method"='DELETE' AND "api_group"<>'文件管理';
UPDATE "sys_api" SET "api_group"='SIP 接入信息' WHERE "path"='/api/gb28181/sip/setup/status' AND "method"='GET' AND "api_group"<>'SIP 接入信息';
UPDATE "sys_api" SET "api_group"='SIP 接入信息' WHERE "path"='/api/gb28181/sip/setup/network-interfaces' AND "method"='GET' AND "api_group"<>'SIP 接入信息';
UPDATE "sys_api" SET "api_group"='SIP 接入信息' WHERE "path"='/api/gb28181/sip/platform' AND "method"='GET' AND "api_group"<>'SIP 接入信息';
UPDATE "sys_api" SET "api_group"='SIP 接入信息' WHERE "path"='/api/gb28181/sip/setup/config' AND "method"='PUT' AND "api_group"<>'SIP 接入信息';
UPDATE "sys_api" SET "api_group"='SIP 接入信息' WHERE "path"='/api/gb28181/sip/setup/skip' AND "method"='POST' AND "api_group"<>'SIP 接入信息';
UPDATE "sys_api" SET "api_group"='日志中心' WHERE "path"='/api/gb28181/sip-traces/health' AND "method"='GET' AND "api_group"<>'日志中心';
UPDATE "sys_api" SET "api_group"='日志中心' WHERE "path"='/api/gb28181/sip-traces/messages' AND "method"='GET' AND "api_group"<>'日志中心';
UPDATE "sys_api" SET "api_group"='日志中心' WHERE "path"='/api/gb28181/sip-traces/messages/:id' AND "method"='GET' AND "api_group"<>'日志中心';
UPDATE "sys_api" SET "api_group"='日志中心' WHERE "path"='/api/gb28181/sip-traces/sessions' AND "method"='GET' AND "api_group"<>'日志中心';
UPDATE "sys_api" SET "api_group"='日志中心' WHERE "path"='/api/gb28181/sip-traces/sessions/:callId/messages' AND "method"='GET' AND "api_group"<>'日志中心';
UPDATE "sys_api" SET "api_group"='日志中心' WHERE "path"='/api/gb28181/device-mgmt/device/:id/sip-trace-capture' AND "method"='GET' AND "api_group"<>'日志中心';
UPDATE "sys_api" SET "api_group"='日志中心' WHERE "path"='/api/gb28181/device-mgmt/device/:id/sip-trace-captures' AND "method"='POST' AND "api_group"<>'日志中心';
UPDATE "sys_api" SET "api_group"='日志中心' WHERE "path"='/api/gb28181/sip-traces/captures/:id/stop' AND "method"='POST' AND "api_group"<>'日志中心';
UPDATE "sys_api" SET "api_group"='SIP 接入信息' WHERE "path"='/api/gb28181/sip/qr/token' AND "method"='POST' AND "api_group"<>'SIP 接入信息';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/custom-groups' AND "method"='POST' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/custom-groups/:id' AND "method"='PATCH' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/custom-groups/:id/move' AND "method"='POST' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/custom-groups/:id' AND "method"='DELETE' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/custom-groups/:id/devices' AND "method"='POST' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/custom-groups/:id/devices/remove' AND "method"='POST' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='告警管理' WHERE "path"='/api/gb28181/alarms' AND "method"='GET' AND "api_group"<>'告警管理';
UPDATE "sys_api" SET "api_group"='告警管理' WHERE "path"='/api/gb28181/alarms/:id' AND "method"='GET' AND "api_group"<>'告警管理';
UPDATE "sys_api" SET "api_group"='告警管理' WHERE "path"='/api/gb28181/alarms/:id' AND "method"='DELETE' AND "api_group"<>'告警管理';
UPDATE "sys_api" SET "api_group"='告警管理' WHERE "path"='/api/gb28181/alarms/batch-delete' AND "method"='POST' AND "api_group"<>'告警管理';
UPDATE "sys_api" SET "api_group"='国标服务配置' WHERE "path"='/api/gb28181/sip/service-config/position-history' AND "method"='GET' AND "api_group"<>'国标服务配置';
UPDATE "sys_api" SET "api_group"='国标服务配置' WHERE "path"='/api/gb28181/sip/service-config/position-history' AND "method"='PUT' AND "api_group"<>'国标服务配置';
UPDATE "sys_api" SET "api_group"='多屏播放' WHERE "path"='/api/gb28181/playback-schemes' AND "method"='GET' AND "api_group"<>'多屏播放';
UPDATE "sys_api" SET "api_group"='多屏播放' WHERE "path"='/api/gb28181/playback-schemes/:id' AND "method"='GET' AND "api_group"<>'多屏播放';
UPDATE "sys_api" SET "api_group"='多屏播放' WHERE "path"='/api/gb28181/playback-schemes' AND "method"='POST' AND "api_group"<>'多屏播放';
UPDATE "sys_api" SET "api_group"='多屏播放' WHERE "path"='/api/gb28181/playback-schemes/:id' AND "method"='PATCH' AND "api_group"<>'多屏播放';
UPDATE "sys_api" SET "api_group"='多屏播放' WHERE "path"='/api/gb28181/playback-schemes/:id/layout' AND "method"='PUT' AND "api_group"<>'多屏播放';
UPDATE "sys_api" SET "api_group"='多屏播放' WHERE "path"='/api/gb28181/playback-schemes/:id' AND "method"='DELETE' AND "api_group"<>'多屏播放';
UPDATE "sys_api" SET "api_group"='国标服务配置' WHERE "path"='/api/gb28181/sip/service-config/ptz-default-speed' AND "method"='GET' AND "api_group"<>'国标服务配置';
UPDATE "sys_api" SET "api_group"='国标服务配置' WHERE "path"='/api/gb28181/sip/service-config/ptz-default-speed' AND "method"='PUT' AND "api_group"<>'国标服务配置';
UPDATE "sys_api" SET "api_group"='国标服务配置' WHERE "path"='/api/gb28181/sip/service-config/sync-channels-on-online' AND "method"='GET' AND "api_group"<>'国标服务配置';
UPDATE "sys_api" SET "api_group"='国标服务配置' WHERE "path"='/api/gb28181/sip/service-config/sync-channels-on-online' AND "method"='PUT' AND "api_group"<>'国标服务配置';
UPDATE "sys_api" SET "api_group"='国标服务配置' WHERE "path"='/api/gb28181/sip/service-config/sip-log' AND "method"='GET' AND "api_group"<>'国标服务配置';
UPDATE "sys_api" SET "api_group"='国标服务配置' WHERE "path"='/api/gb28181/sip/service-config/sip-log' AND "method"='PUT' AND "api_group"<>'国标服务配置';
UPDATE "sys_api" SET "api_group"='国标服务配置' WHERE "path"='/api/gb28181/sip/service-config/ignore-channel-offline-status-notify' AND "method"='GET' AND "api_group"<>'国标服务配置';
UPDATE "sys_api" SET "api_group"='国标服务配置' WHERE "path"='/api/gb28181/sip/service-config/ignore-channel-offline-status-notify' AND "method"='PUT' AND "api_group"<>'国标服务配置';
UPDATE "sys_api" SET "api_group"='国标服务配置' WHERE "path"='/api/gb28181/sip/service-config/online-on-heartbeat' AND "method"='GET' AND "api_group"<>'国标服务配置';
UPDATE "sys_api" SET "api_group"='国标服务配置' WHERE "path"='/api/gb28181/sip/service-config/online-on-heartbeat' AND "method"='PUT' AND "api_group"<>'国标服务配置';
UPDATE "sys_api" SET "api_group"='国标服务配置' WHERE "path"='/api/gb28181/sip/service-config/save-alarm-messages' AND "method"='GET' AND "api_group"<>'国标服务配置';
UPDATE "sys_api" SET "api_group"='国标服务配置' WHERE "path"='/api/gb28181/sip/service-config/save-alarm-messages' AND "method"='PUT' AND "api_group"<>'国标服务配置';
UPDATE "sys_api" SET "api_group"='国标服务配置' WHERE "path"='/api/gb28181/sip/service-config/sip-command-timeout' AND "method"='GET' AND "api_group"<>'国标服务配置';
UPDATE "sys_api" SET "api_group"='国标服务配置' WHERE "path"='/api/gb28181/sip/service-config/sip-command-timeout' AND "method"='PUT' AND "api_group"<>'国标服务配置';
UPDATE "sys_api" SET "api_group"='国标服务配置' WHERE "path"='/api/gb28181/sip/service-config/preallocation-mode' AND "method"='GET' AND "api_group"<>'国标服务配置';
UPDATE "sys_api" SET "api_group"='国标服务配置' WHERE "path"='/api/gb28181/sip/service-config/preallocation-mode' AND "method"='PUT' AND "api_group"<>'国标服务配置';
UPDATE "sys_api" SET "api_group"='国标接入安全' WHERE "path"='/api/gb28181/security/snapshot' AND "method"='GET' AND "api_group"<>'国标接入安全';
UPDATE "sys_api" SET "api_group"='国标接入安全' WHERE "path"='/api/gb28181/security/events' AND "method"='GET' AND "api_group"<>'国标接入安全';
UPDATE "sys_api" SET "api_group"='国标接入安全' WHERE "path"='/api/gb28181/security/bans' AND "method"='GET' AND "api_group"<>'国标接入安全';
UPDATE "sys_api" SET "api_group"='国标接入安全' WHERE "path"='/api/gb28181/security/bans/:id/unban' AND "method"='POST' AND "api_group"<>'国标接入安全';
UPDATE "sys_api" SET "api_group"='国标接入安全' WHERE "path"='/api/gb28181/security/policy' AND "method"='GET' AND "api_group"<>'国标接入安全';
UPDATE "sys_api" SET "api_group"='国标接入安全' WHERE "path"='/api/gb28181/security/policy' AND "method"='PUT' AND "api_group"<>'国标接入安全';
UPDATE "sys_api" SET "api_group"='国标接入安全' WHERE "path"='/api/gb28181/security/agent/health' AND "method"='GET' AND "api_group"<>'国标接入安全';
UPDATE "sys_api" SET "api_group"='国标接入安全' WHERE "path"='/api/gb28181/security/stream' AND "method"='GET' AND "api_group"<>'国标接入安全';
UPDATE "sys_api" SET "api_group"='国标接入安全' WHERE "path"='/api/gb28181/security/access-rules' AND "method"='GET' AND "api_group"<>'国标接入安全';
UPDATE "sys_api" SET "api_group"='国标接入安全' WHERE "path"='/api/gb28181/security/access-rules' AND "method"='POST' AND "api_group"<>'国标接入安全';
UPDATE "sys_api" SET "api_group"='国标接入安全' WHERE "path"='/api/gb28181/security/access-rules/:id' AND "method"='PUT' AND "api_group"<>'国标接入安全';
UPDATE "sys_api" SET "api_group"='国标接入安全' WHERE "path"='/api/gb28181/security/access-rules/:id' AND "method"='DELETE' AND "api_group"<>'国标接入安全';
UPDATE "sys_api" SET "api_group"='国标服务配置' WHERE "path"='/api/gb28181/sip/service-config/global-subscriptions' AND "method"='GET' AND "api_group"<>'国标服务配置';
UPDATE "sys_api" SET "api_group"='国标服务配置' WHERE "path"='/api/gb28181/sip/service-config/global-subscriptions' AND "method"='PUT' AND "api_group"<>'国标服务配置';
UPDATE "sys_api" SET "api_group"='国标服务配置' WHERE "path"='/api/gb28181/sip/service-config/default-channel-audio' AND "method"='GET' AND "api_group"<>'国标服务配置';
UPDATE "sys_api" SET "api_group"='国标服务配置' WHERE "path"='/api/gb28181/sip/service-config/default-channel-audio' AND "method"='PUT' AND "api_group"<>'国标服务配置';
UPDATE "sys_api" SET "api_group"='国标服务配置' WHERE "path"='/api/gb28181/sip/service-config/default-playback-protocol' AND "method"='GET' AND "api_group"<>'国标服务配置';
UPDATE "sys_api" SET "api_group"='国标服务配置' WHERE "path"='/api/gb28181/sip/service-config/default-playback-protocol' AND "method"='PUT' AND "api_group"<>'国标服务配置';
UPDATE "sys_api" SET "api_group"='国标服务配置' WHERE "path"='/api/gb28181/sip/service-config/fixed-address-playback' AND "method"='GET' AND "api_group"<>'国标服务配置';
UPDATE "sys_api" SET "api_group"='国标服务配置' WHERE "path"='/api/gb28181/sip/service-config/fixed-address-playback' AND "method"='PUT' AND "api_group"<>'国标服务配置';
UPDATE "sys_api" SET "api_group"='云端录像' WHERE "path"='/api/gb28181/cloud-recordings/files' AND "method"='GET' AND "api_group"<>'云端录像';
UPDATE "sys_api" SET "api_group"='云端录像' WHERE "path"='/api/gb28181/cloud-recordings/files/options' AND "method"='GET' AND "api_group"<>'云端录像';
UPDATE "sys_api" SET "api_group"='云端录像' WHERE "path"='/api/gb28181/cloud-recordings/files/:id' AND "method"='GET' AND "api_group"<>'云端录像';
UPDATE "sys_api" SET "api_group"='云端录像' WHERE "path"='/api/gb28181/cloud-recordings/files/:id/access' AND "method"='POST' AND "api_group"<>'云端录像';
UPDATE "sys_api" SET "api_group"='云端录像' WHERE "path"='/api/gb28181/cloud-recordings/active' AND "method"='GET' AND "api_group"<>'云端录像';
UPDATE "sys_api" SET "api_group"='云端录像' WHERE "path"='/api/gb28181/cloud-recordings/reconciliations' AND "method"='GET' AND "api_group"<>'云端录像';
UPDATE "sys_api" SET "api_group"='云端录像' WHERE "path"='/api/gb28181/cloud-recordings/reconciliations' AND "method"='POST' AND "api_group"<>'云端录像';
UPDATE "sys_api" SET "api_group"='国标级联' WHERE "path"='/api/gb28181/cascade/platforms' AND "method"='GET' AND "api_group"<>'国标级联';
UPDATE "sys_api" SET "api_group"='国标级联' WHERE "path"='/api/gb28181/cascade/platforms' AND "method"='POST' AND "api_group"<>'国标级联';
UPDATE "sys_api" SET "api_group"='国标级联' WHERE "path"='/api/gb28181/cascade/platforms/:id' AND "method"='GET' AND "api_group"<>'国标级联';
UPDATE "sys_api" SET "api_group"='国标级联' WHERE "path"='/api/gb28181/cascade/platforms/:id' AND "method"='PUT' AND "api_group"<>'国标级联';
UPDATE "sys_api" SET "api_group"='国标级联' WHERE "path"='/api/gb28181/cascade/platforms/:id' AND "method"='DELETE' AND "api_group"<>'国标级联';
UPDATE "sys_api" SET "api_group"='国标级联' WHERE "path"='/api/gb28181/cascade/platforms/:id/enable' AND "method"='POST' AND "api_group"<>'国标级联';
UPDATE "sys_api" SET "api_group"='国标级联' WHERE "path"='/api/gb28181/cascade/platforms/:id/disable' AND "method"='POST' AND "api_group"<>'国标级联';
UPDATE "sys_api" SET "api_group"='国标级联' WHERE "path"='/api/gb28181/cascade/platforms/:id/enabled' AND "method"='PUT' AND "api_group"<>'国标级联';
UPDATE "sys_api" SET "api_group"='国标级联' WHERE "path"='/api/gb28181/cascade/platforms/:id/shares' AND "method"='GET' AND "api_group"<>'国标级联';
UPDATE "sys_api" SET "api_group"='国标级联' WHERE "path"='/api/gb28181/cascade/platforms/:id/shares' AND "method"='PUT' AND "api_group"<>'国标级联';
UPDATE "sys_api" SET "api_group"='国标服务配置' WHERE "path"='/api/gb28181/sip/service-config/play-auth' AND "method"='GET' AND "api_group"<>'国标服务配置';
UPDATE "sys_api" SET "api_group"='国标服务配置' WHERE "path"='/api/gb28181/sip/service-config/play-auth' AND "method"='PUT' AND "api_group"<>'国标服务配置';
UPDATE "sys_api" SET "api_group"='多屏播放' WHERE "path"='/api/gb28181/play/:deviceId/:channelId/authorization' AND "method"='POST' AND "api_group"<>'多屏播放';
UPDATE "sys_api" SET "api_group"='多屏播放' WHERE "path"='/api/gb28181/play/:deviceId/:channelId' AND "method"='POST' AND "api_group"<>'多屏播放';
UPDATE "sys_api" SET "api_group"='云端录像' WHERE "path"='/api/gb28181/cloud-recordings/files/:id/downloads' AND "method"='POST' AND "api_group"<>'云端录像';
UPDATE "sys_api" SET "api_group"='云端录像' WHERE "path"='/api/gb28181/cloud-recordings/downloads/:taskId' AND "method"='GET' AND "api_group"<>'云端录像';
UPDATE "sys_api" SET "api_group"='云端录像' WHERE "path"='/api/gb28181/cloud-recordings/downloads/:taskId' AND "method"='DELETE' AND "api_group"<>'云端录像';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-traffic/summary' AND "method"='GET' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-traffic/trend' AND "method"='GET' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-traffic/realtime' AND "method"='GET' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-traffic/sessions' AND "method"='GET' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-traffic/coverage' AND "method"='GET' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-traffic/viewers' AND "method"='GET' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-traffic/viewers/kick' AND "method"='POST' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='在线用户' WHERE "path"='/api/sysOnlineUser/list' AND "method"='GET' AND "api_group"<>'在线用户';
UPDATE "sys_api" SET "api_group"='在线用户' WHERE "path"='/api/sysOnlineUser/forceLogout' AND "method"='POST' AND "api_group"<>'在线用户';
UPDATE "sys_api" SET "api_group"='日志中心' WHERE "path"='/api/sysLoginLog/list' AND "method"='GET' AND "api_group"<>'日志中心';
UPDATE "sys_api" SET "api_group"='日志中心' WHERE "path"='/api/sysLoginLog/:id' AND "method"='GET' AND "api_group"<>'日志中心';
UPDATE "sys_api" SET "api_group"='日志中心' WHERE "path"='/api/sysLoginLog/delete' AND "method"='DELETE' AND "api_group"<>'日志中心';
UPDATE "sys_api" SET "api_group"='日志中心' WHERE "path"='/api/sysLoginLog/clear' AND "method"='POST' AND "api_group"<>'日志中心';
UPDATE "sys_api" SET "api_group"='日志中心' WHERE "path"='/api/sysLoginLog/unlock' AND "method"='POST' AND "api_group"<>'日志中心';
UPDATE "sys_api" SET "api_group"='多屏播放' WHERE "path"='/api/gb28181/channel-favorite-groups' AND "method"='GET' AND "api_group"<>'多屏播放';
UPDATE "sys_api" SET "api_group"='多屏播放' WHERE "path"='/api/gb28181/channel-favorite-groups' AND "method"='POST' AND "api_group"<>'多屏播放';
UPDATE "sys_api" SET "api_group"='多屏播放' WHERE "path"='/api/gb28181/channel-favorite-groups/:id/channels' AND "method"='POST' AND "api_group"<>'多屏播放';
UPDATE "sys_api" SET "api_group"='多屏播放' WHERE "path"='/api/gb28181/channel-favorite-groups/:id/channels' AND "method"='DELETE' AND "api_group"<>'多屏播放';
UPDATE "sys_api" SET "api_group"='多屏播放' WHERE "path"='/api/gb28181/channel-favorite-groups/:id' AND "method"='DELETE' AND "api_group"<>'多屏播放';
UPDATE "sys_api" SET "api_group"='设备权限工作台' WHERE "path"='/api/gb28181/device-mgmt/permission-workbench/summary' AND "method"='GET' AND "api_group"<>'设备权限工作台';
UPDATE "sys_api" SET "api_group"='设备权限工作台' WHERE "path"='/api/gb28181/device-mgmt/permission-workbench/devices/resolve' AND "method"='POST' AND "api_group"<>'设备权限工作台';
UPDATE "sys_api" SET "api_group"='设备权限工作台' WHERE "path"='/api/gb28181/device-mgmt/permission-workbench/grants/query' AND "method"='POST' AND "api_group"<>'设备权限工作台';
UPDATE "sys_api" SET "api_group"='设备权限工作台' WHERE "path"='/api/gb28181/device-mgmt/permission-workbench/grant-targets' AND "method"='GET' AND "api_group"<>'设备权限工作台';
UPDATE "sys_api" SET "api_group"='设备权限工作台' WHERE "path"='/api/gb28181/device-mgmt/permission-workbench/assignments' AND "method"='POST' AND "api_group"<>'设备权限工作台';
UPDATE "sys_api" SET "api_group"='设备权限工作台' WHERE "path"='/api/gb28181/device-mgmt/permission-workbench/assignments/departments' AND "method"='POST' AND "api_group"<>'设备权限工作台';
UPDATE "sys_api" SET "api_group"='设备权限工作台' WHERE "path"='/api/gb28181/device-mgmt/permission-workbench/grants/apply' AND "method"='POST' AND "api_group"<>'设备权限工作台';
UPDATE "sys_api" SET "api_group"='云端录像' WHERE "path"='/api/gb28181/cloud-recordings/files/:id' AND "method"='DELETE' AND "api_group"<>'云端录像';
UPDATE "sys_api" SET "api_group"='云端录像' WHERE "path"='/api/gb28181/cloud-recordings/files/batch-delete' AND "method"='POST' AND "api_group"<>'云端录像';
UPDATE "sys_api" SET "api_group"='云端录像' WHERE "path"='/api/gb28181/cloud-recordings/active/:id/stop' AND "method"='POST' AND "api_group"<>'云端录像';
UPDATE "sys_api" SET "api_group"='录像计划' WHERE "path"='/api/gb28181/recording-plans' AND "method"='GET' AND "api_group"<>'录像计划';
UPDATE "sys_api" SET "api_group"='录像计划' WHERE "path"='/api/gb28181/recording-plans' AND "method"='POST' AND "api_group"<>'录像计划';
UPDATE "sys_api" SET "api_group"='录像计划' WHERE "path"='/api/gb28181/recording-plans/:id' AND "method"='GET' AND "api_group"<>'录像计划';
UPDATE "sys_api" SET "api_group"='录像计划' WHERE "path"='/api/gb28181/recording-plans/:id' AND "method"='PUT' AND "api_group"<>'录像计划';
UPDATE "sys_api" SET "api_group"='录像计划' WHERE "path"='/api/gb28181/recording-plans/:id' AND "method"='DELETE' AND "api_group"<>'录像计划';
UPDATE "sys_api" SET "api_group"='录像计划' WHERE "path"='/api/gb28181/recording-plans/:id/status' AND "method"='PATCH' AND "api_group"<>'录像计划';
UPDATE "sys_api" SET "api_group"='录像计划' WHERE "path"='/api/gb28181/recording-plans/:id/assignment-options/devices' AND "method"='GET' AND "api_group"<>'录像计划';
UPDATE "sys_api" SET "api_group"='录像计划' WHERE "path"='/api/gb28181/recording-plans/:id/assignment-options/channels' AND "method"='GET' AND "api_group"<>'录像计划';
UPDATE "sys_api" SET "api_group"='录像计划' WHERE "path"='/api/gb28181/recording-plans/:id/assignments' AND "method"='POST' AND "api_group"<>'录像计划';
UPDATE "sys_api" SET "api_group"='录像计划' WHERE "path"='/api/gb28181/recording-plans/channels/:channelId/recording-mode' AND "method"='PATCH' AND "api_group"<>'录像计划';
UPDATE "sys_api" SET "api_group"='录像计划' WHERE "path"='/api/gb28181/recording-plans/:id/channels' AND "method"='GET' AND "api_group"<>'录像计划';
UPDATE "sys_api" SET "api_group"='录像计划' WHERE "path"='/api/gb28181/recording-plans/channels/:channelId/diagnosis' AND "method"='GET' AND "api_group"<>'录像计划';
UPDATE "sys_api" SET "api_group"='录像计划' WHERE "path"='/api/gb28181/recording-plans/channels/:channelId/timeline' AND "method"='GET' AND "api_group"<>'录像计划';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/overview' AND "method"='GET' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes' AND "method"='GET' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id' AND "method"='GET' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/config' AND "method"='GET' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/scheduler' AND "method"='GET' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/scheduler/logs' AND "method"='GET' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/runtime' AND "method"='GET' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/streams' AND "method"='GET' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/streams' AND "method"='GET' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/streams/detail' AND "method"='GET' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/streams/viewers' AND "method"='GET' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/sessions/network' AND "method"='GET' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/sessions/viewers' AND "method"='GET' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/proxies/pull' AND "method"='GET' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/proxies/pull/:key' AND "method"='GET' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/proxies/push' AND "method"='GET' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/proxies/push/:key' AND "method"='GET' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/ffmpeg-sources' AND "method"='GET' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/rtp-servers' AND "method"='GET' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/recordings/runtime/status' AND "method"='GET' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes' AND "method"='POST' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id' AND "method"='PUT' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id' AND "method"='DELETE' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/maintenance' AND "method"='POST' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/activate' AND "method"='POST' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/kick' AND "method"='POST' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/scheduler' AND "method"='PUT' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/streams/playback-grant' AND "method"='POST' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/streams/snapshot' AND "method"='GET' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/streams/close/preflight' AND "method"='POST' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/streams/close' AND "method"='POST' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/streams/close/batch/preflight' AND "method"='POST' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/streams/close/batch' AND "method"='POST' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/streams/force-close' AND "method"='POST' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/sessions/kick' AND "method"='POST' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/proxies/pull' AND "method"='POST' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/proxies/pull/:key/preflight' AND "method"='POST' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/proxies/pull/:key' AND "method"='DELETE' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/proxies/push' AND "method"='POST' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/proxies/push/:key/preflight' AND "method"='POST' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/proxies/push/:key' AND "method"='DELETE' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/ffmpeg-sources' AND "method"='POST' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/ffmpeg-sources/:key/preflight' AND "method"='POST' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/ffmpeg-sources/:key' AND "method"='DELETE' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/rtp-servers' AND "method"='POST' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/rtp-servers/close/preflight' AND "method"='POST' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/rtp-servers/close' AND "method"='POST' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/rtp-servers/force-close' AND "method"='POST' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/recordings/runtime/start/preflight' AND "method"='POST' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/recordings/runtime/start' AND "method"='POST' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/recordings/runtime/stop/preflight' AND "method"='POST' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/recordings/runtime/stop' AND "method"='POST' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/recordings/runtime/force-stop/preflight' AND "method"='POST' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/recordings/runtime/force-stop' AND "method"='POST' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/config' AND "method"='PUT' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/config/test-connection' AND "method"='POST' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/restart' AND "method"='GET' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/restart' AND "method"='POST' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/device/:id/maintenance-operations' AND "method"='GET' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/device/:id/reboot' AND "method"='POST' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/device/:id/firmware-upgrades' AND "method"='GET' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/device/:id/firmware-upgrade' AND "method"='POST' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/channel/:id' AND "method"='DELETE' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/playback-sessions/:sessionId' AND "method"='DELETE' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/ptz/presets/:presetId' AND "method"='DELETE' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/talk-sessions/:sessionId' AND "method"='DELETE' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/device/:id' AND "method"='DELETE' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='仪表盘' WHERE "path"='/api/gb28181/home/layout' AND "method"='DELETE' AND "api_group"<>'仪表盘';
UPDATE "sys_api" SET "api_group"='多屏播放' WHERE "path"='/api/gb28181/play/:streamId' AND "method"='DELETE' AND "api_group"<>'多屏播放';
UPDATE "sys_api" SET "api_group"='系统配置' WHERE "path"='/api/sysParam/delete' AND "method"='DELETE' AND "api_group"<>'系统配置';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/catalog/tree' AND "method"='GET' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/catalog/tree/:id' AND "method"='GET' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/catalog/tree/:id/children' AND "method"='GET' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/channel/:id' AND "method"='GET' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/control-capabilities' AND "method"='GET' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/device-status' AND "method"='GET' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/mounts' AND "method"='GET' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/playback-sessions/:sessionId' AND "method"='GET' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/ptz/cruise-tracks' AND "method"='GET' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/ptz/cruise-tracks/:trackId' AND "method"='GET' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/ptz/home-position' AND "method"='GET' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/ptz/operations/:operationId' AND "method"='GET' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/ptz/precise-status' AND "method"='GET' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/ptz/presets' AND "method"='GET' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/record-query/options' AND "method"='GET' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/snapshot-sessions/:sessionId' AND "method"='GET' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/talk-sessions/:sessionId' AND "method"='GET' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/timeline' AND "method"='GET' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/channels' AND "method"='GET' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/device/:id' AND "method"='GET' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/device/:id/status-events' AND "method"='GET' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/device/:id/subscriptions' AND "method"='GET' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/devices' AND "method"='GET' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/directory/tree' AND "method"='GET' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/map/clusters' AND "method"='GET' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/map/markers' AND "method"='GET' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='仪表盘' WHERE "path"='/api/gb28181/home/drilldown/play' AND "method"='GET' AND "api_group"<>'仪表盘';
UPDATE "sys_api" SET "api_group"='仪表盘' WHERE "path"='/api/gb28181/home/drilldown/sip' AND "method"='GET' AND "api_group"<>'仪表盘';
UPDATE "sys_api" SET "api_group"='仪表盘' WHERE "path"='/api/gb28181/home/drilldown/traffic' AND "method"='GET' AND "api_group"<>'仪表盘';
UPDATE "sys_api" SET "api_group"='仪表盘' WHERE "path"='/api/gb28181/home/layout' AND "method"='GET' AND "api_group"<>'仪表盘';
UPDATE "sys_api" SET "api_group"='仪表盘' WHERE "path"='/api/gb28181/home/summary' AND "method"='GET' AND "api_group"<>'仪表盘';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/play/:streamId/monitor' AND "method"='GET' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/channel/:id' AND "method"='PATCH' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/cloud-recording' AND "method"='PATCH' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/ptz/home-position' AND "method"='PATCH' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/stream-transport' AND "method"='PATCH' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/device/:id/subscriptions/:kind' AND "method"='PATCH' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device/:deviceId' AND "method"='PATCH' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='告警管理' WHERE "path"='/api/gb28181/alarms/clear-all' AND "method"='POST' AND "api_group"<>'告警管理';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/device-control' AND "method"='POST' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/download-sessions' AND "method"='POST' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/playback-sessions' AND "method"='POST' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/playback-sessions/:sessionId/actions' AND "method"='POST' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/ptz' AND "method"='POST' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/ptz/cruise' AND "method"='POST' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/ptz/cruise/tracks' AND "method"='POST' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/ptz/extended' AND "method"='POST' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/ptz/precise' AND "method"='POST' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/ptz/presets' AND "method"='POST' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/ptz/presets/:presetId/call' AND "method"='POST' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/record-query' AND "method"='POST' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/snapshot-sessions' AND "method"='POST' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/talk-sessions' AND "method"='POST' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/channel/batch-delete' AND "method"='POST' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/device' AND "method"='POST' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/device/:id/catalog/refresh' AND "method"='POST' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/device/:id/subscriptions/:kind/renew' AND "method"='POST' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/device/batch-delete' AND "method"='POST' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/probe' AND "method"='POST' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='系统配置' WHERE "path"='/api/sysParam/add' AND "method"='POST' AND "api_group"<>'系统配置';
UPDATE "sys_api" SET "api_group"='仪表盘' WHERE "path"='/api/gb28181/home/layout' AND "method"='PUT' AND "api_group"<>'仪表盘';
UPDATE "sys_api" SET "api_group"='国标服务配置' WHERE "path"='/api/gb28181/sip/service-config/default-channel-stream-transport' AND "method"='PUT' AND "api_group"<>'国标服务配置';
UPDATE "sys_api" SET "api_group"='国标服务配置' WHERE "path"='/api/gb28181/sip/service-config/playback-settings' AND "method"='PUT' AND "api_group"<>'国标服务配置';
UPDATE "sys_api" SET "api_group"='国标服务配置' WHERE "path"='/api/gb28181/sip/service-config/sdp-extension' AND "method"='PUT' AND "api_group"<>'国标服务配置';
UPDATE "sys_api" SET "api_group"='系统配置' WHERE "path"='/api/sysParam/edit' AND "method"='PUT' AND "api_group"<>'系统配置';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/stream-probes/:streamId' AND "method"='POST' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='仪表盘' WHERE "path"='/api/gb28181/sip/dashboard/snapshot' AND "method"='GET' AND "api_group"<>'仪表盘';
UPDATE "sys_api" SET "api_group"='国标服务配置' WHERE "path"='/api/gb28181/sip/service-config/playback-settings' AND "method"='GET' AND "api_group"<>'国标服务配置';
UPDATE "sys_api" SET "api_group"='日志中心' WHERE "path"='/api/gb28181/logs/stream' AND "method"='GET' AND "api_group"<>'日志中心';
UPDATE "sys_api" SET "api_group"='OpenAPI 客户端' WHERE "path"='/api/gb28181/openapi-clients' AND "method"='GET' AND "api_group"<>'OpenAPI 客户端';
UPDATE "sys_api" SET "api_group"='OpenAPI 客户端' WHERE "path"='/api/gb28181/openapi-clients' AND "method"='POST' AND "api_group"<>'OpenAPI 客户端';
UPDATE "sys_api" SET "api_group"='OpenAPI 客户端' WHERE "path"='/api/gb28181/openapi-clients/capabilities' AND "method"='GET' AND "api_group"<>'OpenAPI 客户端';
UPDATE "sys_api" SET "api_group"='OpenAPI 客户端' WHERE "path"='/api/gb28181/openapi-clients/:id' AND "method"='GET' AND "api_group"<>'OpenAPI 客户端';
UPDATE "sys_api" SET "api_group"='OpenAPI 客户端' WHERE "path"='/api/gb28181/openapi-clients/:id/scopes' AND "method"='PUT' AND "api_group"<>'OpenAPI 客户端';
UPDATE "sys_api" SET "api_group"='OpenAPI 客户端' WHERE "path"='/api/gb28181/openapi-clients/:id/rotate-secret' AND "method"='POST' AND "api_group"<>'OpenAPI 客户端';
UPDATE "sys_api" SET "api_group"='OpenAPI 客户端' WHERE "path"='/api/gb28181/openapi-clients/:id/enable' AND "method"='POST' AND "api_group"<>'OpenAPI 客户端';
UPDATE "sys_api" SET "api_group"='OpenAPI 客户端' WHERE "path"='/api/gb28181/openapi-clients/:id/disable' AND "method"='POST' AND "api_group"<>'OpenAPI 客户端';
UPDATE "sys_api" SET "api_group"='OpenAPI 客户端' WHERE "path"='/api/gb28181/openapi-clients/:id/revoke' AND "method"='POST' AND "api_group"<>'OpenAPI 客户端';
UPDATE "sys_api" SET "api_group"='OpenAPI 客户端' WHERE "path"='/api/gb28181/openapi-clients/:id/audits' AND "method"='GET' AND "api_group"<>'OpenAPI 客户端';
UPDATE "sys_api" SET "api_group"='OpenAPI 客户端' WHERE "path"='/api/gb28181/openapi-clients/:id/revocation-status' AND "method"='GET' AND "api_group"<>'OpenAPI 客户端';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/stream-probes/operations/:operationId' AND "method"='GET' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/video-params' AND "method"='GET' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/video-params' AND "method"='POST' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/storage-cards' AND "method"='GET' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/enable' AND "method"='POST' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='流媒体管理' WHERE "path"='/api/gb28181/zlm/nodes/:id/disable' AND "method"='POST' AND "api_group"<>'流媒体管理';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/device-configs' AND "method"='GET' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/device-configs' AND "method"='POST' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='图像库' WHERE "path"='/api/gb28181/device-mgmt/snapshots/:id/content' AND "method"='GET' AND "api_group"<>'图像库';
UPDATE "sys_api" SET "api_group"='设备管理' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/storage-cards/format' AND "method"='POST' AND "api_group"<>'设备管理';
UPDATE "sys_api" SET "api_group"='图像库' WHERE "path"='/api/gb28181/device-mgmt/snapshots' AND "method"='GET' AND "api_group"<>'图像库';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/target-track' AND "method"='GET' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='设备控制' WHERE "path"='/api/gb28181/device-mgmt/channel/:id/target-track' AND "method"='POST' AND "api_group"<>'设备控制';
UPDATE "sys_api" SET "api_group"='国标级联' WHERE "path"='/api/gb28181/cascade/platforms/:id/channels/share' AND "method"='POST' AND "api_group"<>'国标级联';
UPDATE "sys_api" SET "api_group"='国标级联' WHERE "path"='/api/gb28181/cascade/platforms/:id/channels/unshare' AND "method"='POST' AND "api_group"<>'国标级联';
UPDATE "sys_api" SET "api_group"='国标级联' WHERE "path"='/api/gb28181/cascade/platforms/:id/reconnect' AND "method"='POST' AND "api_group"<>'国标级联';
UPDATE "sys_api" SET "api_group"='国标服务配置' WHERE "path"='/api/gb28181/sip/service-config/default-channel-stream-transport' AND "method"='GET' AND "api_group"<>'国标服务配置';
-- api-group-reroute:end
