-- Playback lifecycle log menu and API permissions (PostgreSQL).
INSERT INTO sys_api(title,path,method,api_group,created_at,updated_at,created_by) SELECT '查询播放日志','/api/gb28181/play/lifecycles','GET','播放日志',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1 WHERE NOT EXISTS (SELECT 1 FROM sys_api WHERE path='/api/gb28181/play/lifecycles' AND method='GET' AND deleted_at IS NULL);
INSERT INTO sys_api(title,path,method,api_group,created_at,updated_at,created_by) SELECT '查询播放日志详情','/api/gb28181/play/lifecycles/:lifecycleId','GET','播放日志',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1 WHERE NOT EXISTS (SELECT 1 FROM sys_api WHERE path='/api/gb28181/play/lifecycles/:lifecycleId' AND method='GET' AND deleted_at IS NULL);
INSERT INTO sys_api(title,path,method,api_group,created_at,updated_at,created_by) SELECT '上报播放客户端事实','/api/gb28181/play/lifecycles/:lifecycleId/client-events','POST','播放日志',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1 WHERE NOT EXISTS (SELECT 1 FROM sys_api WHERE path='/api/gb28181/play/lifecycles/:lifecycleId/client-events' AND method='POST' AND deleted_at IS NULL);

INSERT INTO sys_menu(parent_id,path,name,component,title,hide,disable,sort,type,permission,icon,created_at,updated_at,created_by)
SELECT COALESCE((SELECT MIN(id) FROM sys_menu WHERE path='/media' AND type IN (1,2) AND deleted_at IS NULL),0),'/gb28181/playback-log','gb28181-playback-log','gb28181/playback-log/index','播放日志',0,0,7,2,'gb28181:play-log:view','lucide:FileClock',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE path='/gb28181/playback-log' AND deleted_at IS NULL);
INSERT INTO sys_role_menu(role_id,menu_id) SELECT 1,m.id FROM sys_menu m WHERE m.path='/gb28181/playback-log' AND m.deleted_at IS NULL AND NOT EXISTS (SELECT 1 FROM sys_role_menu x WHERE x.role_id=1 AND x.menu_id=m.id);
INSERT INTO sys_role_menu(role_id,menu_id) SELECT DISTINCT rm.role_id,logs.id FROM sys_role_menu rm JOIN sys_menu play_btn ON play_btn.id=rm.menu_id AND play_btn.permission='gb28181:play:start' AND play_btn.type=3 AND play_btn.deleted_at IS NULL CROSS JOIN sys_menu logs WHERE logs.path='/gb28181/playback-log' AND logs.deleted_at IS NULL AND NOT EXISTS (SELECT 1 FROM sys_role_menu x WHERE x.role_id=rm.role_id AND x.menu_id=logs.id);

INSERT INTO sys_menu_api(menu_id,api_id) SELECT m.id,a.id FROM sys_menu m CROSS JOIN sys_api a WHERE m.path='/gb28181/playback-log' AND m.deleted_at IS NULL AND a.path IN ('/api/gb28181/play/lifecycles','/api/gb28181/play/lifecycles/:lifecycleId') AND a.method='GET' AND a.deleted_at IS NULL AND NOT EXISTS (SELECT 1 FROM sys_menu_api x WHERE x.menu_id=m.id AND x.api_id=a.id);
INSERT INTO sys_menu_api(menu_id,api_id) SELECT m.id,a.id FROM sys_menu m CROSS JOIN sys_api a WHERE m.permission='gb28181:play:start' AND m.type=3 AND m.deleted_at IS NULL AND a.path='/api/gb28181/play/lifecycles/:lifecycleId/client-events' AND a.method='POST' AND a.deleted_at IS NULL AND NOT EXISTS (SELECT 1 FROM sys_menu_api x WHERE x.menu_id=m.id AND x.api_id=a.id);
INSERT INTO sys_casbin_rule(ptype,v0,v1,v2,v3,v4,v5) SELECT DISTINCT 'p','role_' || rm.role_id,a.path,a.method,'*','','' FROM sys_role_menu rm JOIN sys_menu m ON m.id=rm.menu_id JOIN sys_menu_api ma ON ma.menu_id=m.id JOIN sys_api a ON a.id=ma.api_id WHERE ((m.path='/gb28181/playback-log' AND a.method='GET') OR (m.permission='gb28181:play:start' AND m.type=3 AND a.method='POST')) AND a.path LIKE '/api/gb28181/play/lifecycles%' AND a.deleted_at IS NULL AND NOT EXISTS (SELECT 1 FROM sys_casbin_rule p WHERE p.ptype='p' AND p.v0='role_' || rm.role_id AND p.v1=a.path AND p.v2=a.method AND p.v3='*');
